/* Extra catalogue wave 15 — automotive & tyres, consumer products, toys,
 * stationery, furniture, environment and air quality, plus further test-method
 * families (wood panels, paints, plastics, rubber, EMC, optical fibre,
 * rotating machines). */
import { buildBlocks, type Block } from "@/db/seed-kit";

const TYRE_QCO = "Pneumatic Tyres (Quality Control) Order";
const TOY_QCO = "Toys (Quality Control) Order";

const AUTOMOTIVE: Block = {
  category: "mechanical",
  qco: TYRE_QCO,
  rows: [
    ["IS 15636-1:2012", "Automotive Vehicles — Tyres — Part 1: Passenger Car Tyres — Specification", "Passenger car tyre sizes, load and speed ratings and endurance requirements.", "M"],
    ["IS 15636-3:2012", "Automotive Vehicles — Tyres — Part 3: Truck and Bus Tyres — Specification", "Heavy commercial vehicle tyre load indices, tread depth and endurance tests.", "M"],
    ["IS 15636-4:2012", "Automotive Vehicles — Tyres — Part 4: Tyres for Light Commercial Vehicles — Specification", "LCV tyre dimensions, load index and performance requirements.", "M"],
    ["IS 15636-5:2012", "Automotive Vehicles — Tyres — Part 5: Motorcycle and Scooter Tyres — Specification", "Two-wheeler tyre sizes, ply rating and high speed performance."],
    ["IS 11827:1985", "Automotive Vehicles — Brake Hoses and Hose Assemblies — Specification", "Brake hose burst pressure, volumetric expansion and compatibility requirements."],
    ["IS 14664:1999", "Automotive Vehicles — Safety Glass — Specification", "Laminated and toughened safety glass optical and fragmentation requirements."],
    ["IS 15739:2007", "Automotive Vehicles — Rear View Mirrors — Specification", "Mirror curvature, reflectivity and mounting strength requirements."],
    ["IS 15140:2002", "Automotive Vehicles — Seat Belts and Restraint Systems — Specification", "Seat belt webbing strength, buckle release force and anchorage requirements."],
    ["IS 14346:1996", "Automotive Vehicles — Lighting and Light Signalling Devices — Specification", "Head lamp, tail lamp and indicator photometric requirements."],
    ["IS 14000:1988", "Automotive Vehicles — Horns — Specification", "Horn sound level, frequency range and endurance requirements."],
    ["IS 16364:2015", "Electric Vehicles — Safety Requirements for Rechargeable Energy Storage Systems", "Battery pack safety, thermal propagation and electrical protection for EVs."],
    ["IS 17115:2019", "Electric Vehicles — Battery Management Systems — Requirements", "BMS state estimation, protection and communication requirements for EV batteries."],
    ["IS 3443:1980", "Automotive Vehicles — Shock Absorbers — Specification", "Shock absorber damping characteristics, durability and leakage requirements."],
    ["IS 12625:1989", "Automotive Vehicles — Fuel Filters for Diesel Engines — Specification", "Filter efficiency, burst pressure and element integrity requirements."],
    ["IS 2490-1:1981", "Automotive Vehicles — Lead Acid Storage Batteries — Part 1: General Requirements and Methods of Test", "Automotive battery capacity, cranking performance and durability testing."],
    ["IS 2490-2:1982", "Automotive Vehicles — Lead Acid Storage Batteries — Part 2: Specification for Batteries", "Automotive battery dimensions, terminal arrangement and rated capacity."],
  ],
};

const CONSUMER_AND_TOYS: Block = {
  category: "consumer",
  qco: TOY_QCO,
  rows: [
    ["IS 9873-1:2011", "Safety of Toys — Part 1: Safety Aspects Related to Mechanical and Physical Properties", "Sharp edges, small parts, cords and mechanical hazard requirements for toys.", "M", { keywords: ["toy", "खिलौना", "children"] }],
    ["IS 9873-2:2011", "Safety of Toys — Part 2: Flammability", "Flammability requirements for toys and toy materials.", "M"],
    ["IS 9873-5:2011", "Safety of Toys — Part 5: Chemical Toys (Sets) Other Than Experimental Sets", "Chemical toy composition, labelling and hazard requirements.", "M"],
    ["IS 9873-8:2011", "Safety of Toys — Part 8: Migration of Certain Elements", "Heavy metal migration limits for toy materials in contact with children.", "M"],
    ["IS 1727:2019", "School Bags — Specification", "Bag strength, strap attachment, water resistance and reflective marking requirements."],
    ["IS 6732:1972", "Specification for Fountain Pen Nibs", "Nib dimensions, writing quality and corrosion resistance."],
    ["IS 1375:1987", "Specification for Lead Pencils", "Pencil grading, lead core strength and wood quality requirements."],
    ["IS 4821:1979", "Specification for Ball Point Pens", "Pen body, ink flow, leakage and writing length requirements."],
    ["IS 6174:1971", "Specification for Office Furniture — Steel Filing Cabinets", "Cabinet construction, drawer operation and load capacity requirements."],
    ["IS 3374:1977", "Specification for Wooden Chairs for General Purposes", "Chair dimensions, joint strength and stability requirements."],
    ["IS 12480:1988", "Specification for Domestic Furniture — Steel Cots", "Cot construction, rail strength and safety requirements."],
    ["IS 14823:2000", "Wall Coverings — Specification", "Wallpaper and wall covering dimensional stability, colour fastness and fire behaviour."],
    ["IS 13431:2001", "Specification for Stainless Steel Utensils — Household and Kitchen", "Utensil grades, material thickness and food-contact safety requirements.", "Q:Steel & Steel Products (Quality Control) Order"],
    ["IS 13219:1992", "Specification for Insulated Domestic Containers (Hot Cases)", "Thermal retention performance and material safety requirements."],
    ["IS 12948:1990", "Specification for Pressure Cookers — Safety Requirements", "Cooker body, safety valve and pressure ratings for domestic pressure cookers."],
    ["IS 3360:1995", "Code of Practice for Porcelain, Glass and Metal Insulators for Use in Cow Sheds (Sanitary Appliances)", "Hygienic design requirements for dairy and food handling equipment."],
  ],
};

const ENVIRONMENT_AND_AIR: Block = {
  category: "chemicals",
  rows: [
    ["IS 5182-1:1969", "Methods for Measurement of Air Pollution — Part 1: Dustfall", "Dustfall collection and gravimetric measurement."],
    ["IS 5182-2:1969", "Methods for Measurement of Air Pollution — Part 2: Suspended Particulate Matter", "High volume sampling of suspended particulate matter."],
    ["IS 5182-3:1970", "Methods for Measurement of Air Pollution — Part 3: Determination of Sulphur Dioxide", "SO2 measurement by West-Gaeke and titrimetric methods."],
    ["IS 5182-4:1973", "Methods for Measurement of Air Pollution — Part 4: Determination of Nitrogen Oxides", "NOx determination by the Jacobs-Hochheiser and alkaline methods."],
    ["IS 5182-5:1974", "Methods for Measurement of Air Pollution — Part 5: Determination of Total Hydrocarbons", "Total hydrocarbon measurement in ambient and stack air."],
    ["IS 5182-6:1975", "Methods for Measurement of Air Pollution — Part 6: Determination of Carbon Monoxide", "CO measurement by colorimetric and NDIR methods."],
    ["IS 5182-7:1973", "Methods for Measurement of Air Pollution — Part 7: Determination of Ammonia", "Ammonia determination by Nesslerisation."],
    ["IS 5182-8:1976", "Methods for Measurement of Air Pollution — Part 8: Determination of Fluoride", "Fluoride sampling and determination for stack and ambient air."],
    ["IS 5182-9:1974", "Methods for Measurement of Air Pollution — Part 9: Determination of Lead", "Lead determination in particulate matter by AAS."],
    ["IS 5182-10:1976", "Methods for Measurement of Air Pollution — Part 10: Determination of Ozone", "Ozone measurement by neutral buffered potassium iodide method."],
    ["IS 5182-11:1975", "Methods for Measurement of Air Pollution — Part 11: Determination of Sulphation and Specific Conductance", "Lead dioxide candle method for sulphation rate."],
    ["IS 5182-12:1974", "Methods for Measurement of Air Pollution — Part 12: Determination of Arsine and Arsine in Air", "Arsine determination for workplace and ambient air."],
    ["IS 5182-14:2000", "Methods for Measurement of Air Pollution — Part 14: Guidelines for Planning the Sampling of Atmosphere", "Sampling network design and site selection guidance."],
    ["IS 5182-15:1974", "Methods for Measurement of Air Pollution — Part 15: Determination of Hydrogen Sulphide", "H2S measurement by methylene blue method."],
    ["IS 5182-16:1979", "Methods for Measurement of Air Pollution — Part 16: Determination of Chlorine", "Chlorine determination in ambient and workplace air."],
    ["IS 5182-17:1979", "Methods for Measurement of Air Pollution — Part 17: Determination of Hydrogen Chloride", "HCl determination by titrimetric and colorimetric methods."],
    ["IS 5182-18:1975", "Methods for Measurement of Air Pollution — Part 18: Determination of Certain Aromatic Isocyanates", "Isocyanate determination by colorimetric sampling."],
    ["IS 5182-19:1982", "Methods for Measurement of Air Pollution — Part 19: Determination of Chlorinated Hydrocarbons", "Chlorinated hydrocarbon measurement for workplace air."],
    ["IS 5182-20:1982", "Methods for Measurement of Air Pollution — Part 20: Determination of Benzene", "Benzene determination by gas chromatography."],
    ["IS 5182-21:1983", "Methods for Measurement of Air Pollution — Part 21: Determination of Sulphur Dioxide in Work Place Environment", "Workplace SO2 measurement and exposure assessment."],
    ["IS 5182-22:1983", "Methods for Measurement of Air Pollution — Part 22: Determination of Silica in Work Place Environment", "Respirable silica sampling and analysis."],
    ["IS 5182-23:1986", "Methods for Measurement of Air Pollution — Part 23: Determination of Dust, Fume and Vapours in Work Place Environment", "Workplace dust, fume and vapour sampling guidance."],
    ["IS 5182-24:1988", "Methods for Measurement of Air Pollution — Part 24: Determination of Sulphur Dioxide in Ambient Air", "Improved ambient SO2 measurement procedure."],
    ["IS 5182-25:1994", "Methods for Measurement of Air Pollution — Part 25: Determination of Acetaldehyde", "Acetaldehyde determination for industrial emission control."],
    ["IS 5182-26:1997", "Methods for Measurement of Air Pollution — Part 26: Determination of Formaldehyde", "Formaldehyde measurement for indoor air and industrial emissions."],
  ],
};

const PANEL_AND_MATERIAL_TESTS: Block = {
  category: "plastics",
  rows: [
    ["IS 1734-2:1983", "Methods of Test for Plywood — Part 2: Determination of Moisture Content", "Moisture content determination for plywood test pieces."],
    ["IS 1734-3:1983", "Methods of Test for Plywood — Part 3: Determination of Density and Relative Density", "Density determination for plywood and veneers."],
    ["IS 1734-4:1983", "Methods of Test for Plywood — Part 4: Determination of Water Absorption", "Water absorption testing after immersion."],
    ["IS 1734-6:1983", "Methods of Test for Plywood — Part 6: Determination of Tensile Strength", "Tensile strength of plywood parallel and perpendicular to grain."],
    ["IS 1734-7:1983", "Methods of Test for Plywood — Part 7: Determination of Compressive Strength", "Compression strength testing of plywood panels."],
    ["IS 1734-8:1983", "Methods of Test for Plywood — Part 8: Determination of Static Bending Strength", "Modulus of rupture and elasticity for plywood."],
    ["IS 1734-9:1983", "Methods of Test for Plywood — Part 9: Determination of Screw Holding Power", "Screw withdrawal resistance for plywood."],
    ["IS 1734-10:1983", "Methods of Test for Plywood — Part 10: Determination of Nail Holding Power", "Nail withdrawal resistance of plywood panels."],
    ["IS 1734-11:1983", "Methods of Test for Plywood — Part 11: Determination of Glue Shear Strength — Wet and Dry", "Glue line shear strength for moisture-resistant bonding."],
    ["IS 1734-12:1983", "Methods of Test for Plywood — Part 12: Determination of Plate Shear Strength", "Plate shear testing of plywood."],
    ["IS 1734-13:1983", "Methods of Test for Plywood — Part 13: Determination of Impact Resistance", "Impact strength testing for plywood used in shuttering and flooring."],
    ["IS 1734-14:1983", "Methods of Test for Plywood — Part 14: Determination of Adhesion of Surface", "Veneer adhesion testing of decorative plywood."],
    ["IS 1734-15:1983", "Methods of Test for Plywood — Part 15: Determination of Termite and Borer Resistance", "Biological resistance testing for treated plywood."],
    ["IS 1734-16:1983", "Methods of Test for Plywood — Part 16: Determination of Fire Resistance", "Flame spread and fire penetration testing of plywood."],
    ["IS 1734-17:1983", "Methods of Test for Plywood — Part 17: Determination of Formaldehyde Emission", "Formaldehyde emission testing for interior grade panels."],
    ["IS 3400-17:1977", "Methods of Test for Vulcanized Rubbers — Part 17: Determination of Rebound Resilience", "Rebound resilience measurement for rubber compounds."],
    ["IS 3400-18:1977", "Methods of Test for Vulcanized Rubbers — Part 18: Determination of Compression Fatigue", "Compression fatigue testing for rubber springs and gaskets."],
    ["IS 3400-19:1977", "Methods of Test for Vulcanized Rubbers — Part 19: Determination of Dynamic Modulus", "Dynamic modulus and damping measurement."],
    ["IS 3400-20:1977", "Methods of Test for Vulcanized Rubbers — Part 20: Determination of Water Absorption", "Water absorption testing for rubber products."],
    ["IS 13360-2-2:1994", "Plastics — Methods of Testing — Part 2-2: Determination of Volatile Matter Content", "Volatile matter determination for plastic materials."],
    ["IS 13360-2-3:1994", "Plastics — Methods of Testing — Part 2-3: Determination of Ash Content", "Ash content determination for filled and unfilled plastics."],
    ["IS 13360-2-4:1994", "Plastics — Methods of Testing — Part 2-4: Determination of Filler Content", "Filler content determination by ashing and solvent extraction."],
    ["IS 13360-2-5:1994", "Plastics — Methods of Testing — Part 2-5: Determination of Matter Extractable by Organic Solvents", "Extractables determination for food-contact plastics."],
    ["IS 13360-2-6:1994", "Plastics — Methods of Testing — Part 2-6: Determination of pH of Aqueous Extract", "pH of aqueous extract for plastics used in contact with potable water."],
    ["IS 13360-2-7:1994", "Plastics — Methods of Testing — Part 2-7: Determination of Bulk Density", "Bulk density determination for moulding powders and resins."],
    ["IS 13360-2-8:1994", "Plastics — Methods of Testing — Part 2-8: Determination of Viscosity Number and K-Value", "Viscosity number for PVC resins used in pipes and profiles."],
    ["IS 13360-2-9:1994", "Plastics — Methods of Testing — Part 2-9: Determination of Residual Styrene Monomer", "Residual monomer determination for food-contact plastics."],
    ["IS 13360-2-10:1994", "Plastics — Methods of Testing — Part 2-10: Determination of Plasticizer Migration", "Plasticizer migration testing for food contact applications."],
    ["IS 13360-13-1:1994", "Plastics — Methods of Testing — Part 13-1: Determination of Environmental Stress Cracking", "ESC testing for polyolefin pipe materials."],
    ["IS 13360-14-1:1994", "Plastics — Methods of Testing — Part 14-1: Determination of Weathering Resistance", "Accelerated weathering and UV stability testing of plastics."],
    ["IS 13360-15-1:1994", "Plastics — Methods of Testing — Part 15-1: Determination of Chemical Resistance", "Chemical resistance classification of plastic materials."],
    ["IS 13360-16-1:1994", "Plastics — Methods of Testing — Part 16-1: Determination of Fungal and Bacterial Resistance", "Biological resistance testing for plastics in tropical use."],
    ["IS 12235-11:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 11: Water-Tightness Test", "Water-tightness testing of joints and fittings."],
    ["IS 12235-12:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 12: Dimensional Stability", "Dimensional stability and stress relief testing of UPVC pipes."],
    ["IS 12235-13:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 13: Ageing Resistance", "Ageing resistance testing for UPVC pipe compounds."],
    ["IS 12235-14:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 14: Colour and Surface Finish", "Colour uniformity and surface defect requirements."],
    ["IS 12235-15:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 15: Resistance to Sulphuric Acid", "Acid resistance testing for chemical-duty UPVC pipes."],
    ["IS 12235-16:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 16: Flattening Test", "Flattening and flexibility testing for UPVC pipes."],
    ["IS 101-1:1986", "Methods of Sampling and Test for Ready Mixed Paints, Varnishes and Lacquers — Part 1: Sampling", "Sampling procedures for paint, varnish and lacquer consignments."],
    ["IS 101-2:1986", "Methods of Sampling and Test for Ready Mixed Paints — Part 2: Tests on Liquid Paints", "Consistency, fineness of grind and settling tests on liquid paints."],
    ["IS 101-3:1986", "Methods of Sampling and Test for Ready Mixed Paints — Part 3: Tests on Dried Films", "Adhesion, hardness and flexibility tests on dried paint films."],
    ["IS 101-4:1987", "Methods of Sampling and Test for Ready Mixed Paints — Part 4: Optical Tests", "Opacity, gloss and colour measurement of paint films."],
    ["IS 101-5:1988", "Methods of Sampling and Test for Ready Mixed Paints — Part 5: Durability Tests", "Weathering, salt spray and humidity resistance testing."],
  ],
};

const MACHINES_AND_EMC_SUPPLEMENT: Block = {
  category: "electrical",
  rows: [
    ["IS 15999-2-2:2011", "Rotating Electrical Machines — Part 2-2: Specific Methods of Test for Determining Losses and Efficiency of Large Machines", "Calorimetric and summation of losses methods for large machines."],
    ["IS 15999-2-3:2011", "Rotating Electrical Machines — Part 2-3: Specific Methods of Test for Determining Losses and Efficiency of Converter-Fed AC Motors", "Efficiency determination for inverter fed motors."],
    ["IS 15999-4:2011", "Rotating Electrical Machines — Part 4: Methods for Determining Quantities from Tests", "Temperature rise and performance determination from test data."],
    ["IS 15999-13:2011", "Rotating Electrical Machines — Part 13: Specification for Particular Types of Machines — General", "Specification structure for particular machine types."],
    ["IS 15999-14:2011", "Rotating Electrical Machines — Part 14: Mechanical Vibration of Certain Machines with Shaft Heights 56 mm and Higher", "Vibration measurement and limits for machines by shaft height."],
    ["IS 15999-16:2011", "Rotating Electrical Machines — Part 16: Excitation Systems for Synchronous Machines", "Excitation system performance and protection requirements."],
    ["IS 15999-17:2011", "Rotating Electrical Machines — Part 17: Cylindrical Rotor Synchronous Machines", "Requirements for cylindrical rotor turbo generators."],
    ["IS 15999-19:2011", "Rotating Electrical Machines — Part 19: Specific Test Methods for Determining Losses and Efficiency of Large Machines", "Alternative efficiency determination methods for large machines."],
    ["IS 15999-20:2011", "Rotating Electrical Machines — Part 20: Vibration and Noise of Machines", "Measurement and limits for vibration and airborne noise."],
    ["IS 15999-21:2011", "Rotating Electrical Machines — Part 21: Thermal Performance and Temperature Rise of Machines", "Thermal test methods and temperature rise limits."],
    ["IS 15999-22:2011", "Rotating Electrical Machines — Part 22: AC Generators for Reciprocating Engine Driven Generator Sets", "Alternator requirements for DG sets."],
    ["IS 15999-23:2011", "Rotating Electrical Machines — Part 23: Vibration and Shock Testing of Machines", "Vibration and shock qualification testing."],
    ["IS 15999-24:2011", "Rotating Electrical Machines — Part 24: Rotor Balancing", "Balancing quality grades and residual unbalance limits."],
    ["IS 15999-25:2011", "Rotating Electrical Machines — Part 25: Mechanical Vibration Measurement for Machines Coupled to Other Machines", "Vibration measurement at coupled shaft ends."],
    ["IS 14700-1-1:2016", "Electromagnetic Compatibility — Part 1-1: Application and Interpretation of Fundamental Definitions and Terms", "EMC terminology and basic definitions for testing and documentation."],
    ["IS 14700-1-2:2016", "Electromagnetic Compatibility — Part 1-2: Methodology for the Achievement of Functional Safety of Electrical and Electronic Systems", "EMC and functional safety methodology for electronic systems."],
    ["IS 14700-2-1:2016", "Electromagnetic Compatibility — Part 2-1: Description of the Environment — Electromagnetic Environment for Low-Frequency Conducted Disturbances and Signalling in Public Power Supply Systems", "Description of low frequency conducted disturbance environment."],
    ["IS 14700-2-2:2016", "Electromagnetic Compatibility — Part 2-2: Compatibility Levels for Low-Frequency Conducted Disturbances and Signalling in Public Power Supply Systems", "Compatibility levels for harmonic and interharmonic disturbances."],
    ["IS 14700-2-3:2016", "Electromagnetic Compatibility — Part 2-3: Limits — Assessment of Emission Limits for the Connection of Unbalanced Installations to MV, HV and EHV Power Systems", "Emission limit assessment for unbalanced installations."],
    ["IS 14700-4-7:2019", "Electromagnetic Compatibility — Part 4-7: Testing and Measurement Techniques — General Guide on Harmonics and Interharmonics Measurements", "Harmonics and interharmonics measurement instrumentation guidance."],
    ["IS 14700-4-8:2019", "Electromagnetic Compatibility — Part 4-8: Testing and Measurement Techniques — Power Frequency Magnetic Field Immunity Test", "Power frequency magnetic field immunity testing."],
    ["IS 14700-4-9:2019", "Electromagnetic Compatibility — Part 4-9: Testing and Measurement Techniques — Impulse Magnetic Field Immunity Test", "Impulse magnetic field immunity testing."],
    ["IS 14700-4-10:2019", "Electromagnetic Compatibility — Part 4-10: Testing and Measurement Techniques — Damped Oscillatory Magnetic Field Immunity Test", "Damped oscillatory magnetic field immunity testing."],
    ["IS 14700-4-12:2019", "Electromagnetic Compatibility — Part 4-12: Testing and Measurement Techniques — Ring Wave Immunity Test", "Ring wave immunity testing for mains and signal ports."],
    ["IS 10810-25:1990", "Methods of Test for Optical Fibre Cables — Part 25: Measurement of Fibre Strain", "Fibre strain measurement during tensile loading."],
    ["IS 10810-26:1990", "Methods of Test for Optical Fibre Cables — Part 26: Measurement of Polarization Mode Dispersion", "PMD measurement for high bit rate optical links."],
    ["IS 10810-27:1990", "Methods of Test for Optical Fibre Cables — Part 27: Measurement of Chromatic Dispersion", "Chromatic dispersion measurement for single-mode fibres."],
    ["IS 10810-28:1990", "Methods of Test for Optical Fibre Cables — Part 28: Measurement of Splice Loss", "Splice loss measurement by OTDR and power meter methods."],
    ["IS 10810-29:1990", "Methods of Test for Optical Fibre Cables — Part 29: Measurement of Return Loss", "Optical return loss measurement for connectors and splices."],
    ["IS 10810-30:1990", "Methods of Test for Optical Fibre Cables — Part 30: Bend Loss Test", "Macrobend and microbend loss testing."],
    ["IS 10810-31:1990", "Methods of Test for Optical Fibre Cables — Part 31: Proof Test for Optical Fibres", "Proof testing of fibre strength by controlled loading."],
    ["IS 10810-32:1990", "Methods of Test for Optical Fibre Cables — Part 32: Coating Geometry Measurement", "Fibre coating diameter and concentricity measurement."],
    ["IS 10810-33:1990", "Methods of Test for Optical Fibre Cables — Part 33: Measurement of Optical Fibre Ribbon Dimensions", "Ribbon fibre spacing and dimensional measurement."],
    ["IS 10810-34:1990", "Methods of Test for Optical Fibre Cables — Part 34: Fume and Toxicity Test", "Cable fume emission and toxicity testing for indoor installation."],
    ["IS 10810-35:1990", "Methods of Test for Optical Fibre Cables — Part 35: Flame Propagation Test", "Flame propagation testing for indoor optical cables."],
    ["IS 10810-36:1990", "Methods of Test for Optical Fibre Cables — Part 36: Cable Bending Radius Test", "Minimum bend radius verification for installation."],
    ["IS 10810-37:1990", "Methods of Test for Optical Fibre Cables — Part 37: Dimensional Measurement of Cable Sheath", "Sheath thickness and diameter measurement."],
    ["IS 10810-38:1990", "Methods of Test for Optical Fibre Cables — Part 38: Water Blocking Compound Test", "Water blocking tape and compound effectiveness testing."],
    ["IS 10810-39:1990", "Methods of Test for Optical Fibre Cables — Part 39: Kit Material and Jointing Accessories Test", "Jointing kit material and accessory conformity testing."],
    ["IS 10810-40:1990", "Methods of Test for Optical Fibre Cables — Part 40: Field Acceptance and Commissioning Measurements", "Field commissioning tests for laid optical fibre links."],
  ],
};

export const STD_WAVE15 = buildBlocks(
  AUTOMOTIVE,
  CONSUMER_AND_TOYS,
  ENVIRONMENT_AND_AIR,
  PANEL_AND_MATERIAL_TESTS,
  MACHINES_AND_EMC_SUPPLEMENT,
);
