/* Extra catalogue wave 13 — chemicals, petroleum products, soaps and
 * cosmetics, plastics and rubber testing, textiles, paper, jute and leather. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const CHEMICAL_QCO = "Chemicals (Quality Control) Order";

const INDUSTRIAL_CHEMICALS: Block = {
  category: "chemicals",
  qco: CHEMICAL_QCO,
  rows: [
    ["IS 266:1993", "Sulphuric Acid — Specification", "Concentration, iron, arsenic and lead limits for technical and battery grade sulphuric acid.", "M"],
    ["IS 267:1993", "Nitric Acid — Specification", "Nitric acid strength, residue on ignition and chloride limits for industrial use.", "M"],
    ["IS 268:1989", "Phosphoric Acid — Specification", "Food and technical grade phosphoric acid assay, fluoride and heavy metal limits.", "M"],
    ["IS 281:1983", "Sodium Hydroxide (Caustic Soda) — Specification", "Caustic soda grades, NaOH content, carbonate, chloride and iron limits."],
    ["IS 283:1979", "Sodium Carbonate (Soda Ash) — Specification", "Soda ash assay, chloride, iron and matter insoluble in water limits."],
    ["IS 286:2001", "Sodium Bicarbonate — Specification", "Sodium bicarbonate purity, alkalinity and heavy metal limits for food and industrial use.", "M"],
    ["IS 288:1981", "Bleaching Powder — Specification", "Available chlorine, moisture and stability requirements for bleaching powder."],
    ["IS 289:1980", "Calcium Carbide — Specification", "Calcium carbide gas yield, phosphine and sulphide limits for acetylene generation."],
    ["IS 252:1991", "Sodium Sulphate — Specification", "Anhydrous sodium sulphate purity and impurity limits for detergents and glass."],
    ["IS 254:1985", "Aluminium Sulphate — Specification", "Alum grade requirements for water treatment including iron and insoluble matter."],
    ["IS 255:1985", "Ferric Alum — Specification", "Ferric alum composition for water clarification and effluent treatment."],
    ["IS 323:1988", "Sodium Tripolyphosphate — Specification", "STPP assay and impurity limits for detergent formulations."],
    ["IS 331:1992", "Sodium Silicate — Specification", "Sodium silicate ratio, total solids and alkalinity for adhesives and detergents."],
    ["IS 332:1983", "Zinc Oxide — Specification", "Zinc oxide grades for rubber, paints and ceramics with purity limits."],
    ["IS 334:1990", "Titanium Dioxide — Specification", "Anatase and rutile grade pigment requirements including whiteness and oil absorption.", "M"],
    ["IS 335:1993", "Lithopone — Specification", "Lithopone pigment composition and hiding power requirements for paints."],
    ["IS 336:1991", "Red Lead — Specification", "Red lead oxide content and fineness for anticorrosive primers."],
    ["IS 337:1992", "Zinc Chromate — Specification", "Zinc chromate primer pigment composition and test requirements."],
    ["IS 338:1992", "Carbon Black — Specification", "Carbon black grades for rubber and inks with iodine adsorption and tint strength."],
    ["IS 339:1991", "Barium Sulphate — Specification", "Blanc fixe composition and brightness for paint and paper applications."],
    ["IS 340:1992", "Calcium Carbonate — Specification", "Precipitated and natural calcium carbonate grades for paint, plastics and paper."],
    ["IS 341:1991", "Whiting and Paris White — Specification", "Chalk whiting fineness and purity requirements for putty and paints."],
    ["IS 342:1992", "Barytes — Specification", "Barytes grading, specific gravity and fineness for paint and drilling applications."],
    ["IS 343:1991", "Red Oxide of Iron — Specification", "Synthetic red iron oxide pigment requirements for paints and cement colouring."],
    ["IS 344:1992", "Talc — Specification", "Talc purity, whiteness and moisture requirements for paint, cosmetic and paper use."],
    ["IS 1460:2017", "Automotive Diesel Fuel — Specification", "Diesel fuel grades by sulphur content, cetane number, density and flash point.", "M", { keywords: ["diesel", "fuel", "डीजल"], related: ["IS 2796:1981"] }],
  ],
};

const PLASTICS_AND_RUBBER: Block = {
  category: "plastics",
  rows: [
    ["IS 3400-1:1987", "Methods of Test for Vulcanized Rubbers — Part 1: Tensile Stress-Strain Properties", "Tensile strength, elongation at break and modulus testing of vulcanized rubber."],
    ["IS 3400-2:1980", "Methods of Test for Vulcanized Rubbers — Part 2: Hardness", "Durometer and IRHD hardness determination for rubber products."],
    ["IS 3400-5:1987", "Methods of Test for Vulcanized Rubbers — Part 5: Accelerated Ageing and Heat Resistance", "Air oven and oxygen bomb ageing tests for rubber compounds."],
    ["IS 3400-7:1987", "Methods of Test for Vulcanized Rubbers — Part 7: Compression Set", "Compression set testing at constant strain for sealing and gasket rubber."],
    ["IS 3400-8:1987", "Methods of Test for Vulcanized Rubbers — Part 8: Tear Strength", "Trouser, angle and crescent tear strength determination."],
    ["IS 3400-9:1987", "Methods of Test for Vulcanized Rubbers — Part 9: Abrasion Resistance", "DIN and Akron abrasion testing for tyre tread and sole compounds."],
    ["IS 3400-10:1977", "Methods of Test for Vulcanized Rubbers — Part 10: Density", "Density determination of rubber compounds and vulcanizates."],
    ["IS 3400-11:1977", "Methods of Test for Vulcanized Rubbers — Part 11: Adhesion to Fabric", "Ply adhesion testing for belting and tyre cord compounds."],
    ["IS 3400-12:1977", "Methods of Test for Vulcanized Rubbers — Part 12: Swelling in Liquids", "Volume swelling tests for rubber in oils, fuels and solvents."],
    ["IS 3400-13:1977", "Methods of Test for Vulcanized Rubbers — Part 13: Electrical Resistivity", "Volume and surface resistivity measurement for insulating rubbers."],
    ["IS 3400-14:1977", "Methods of Test for Vulcanized Rubbers — Part 14: Low Temperature Brittleness", "Brittleness point testing for rubbers used in cold service."],
    ["IS 3400-15:1977", "Methods of Test for Vulcanized Rubbers — Part 15: Flexing and Fatigue", "De Mattia flex cracking and cut growth resistance testing."],
    ["IS 3400-16:1977", "Methods of Test for Vulcanized Rubbers — Part 16: Bond Strength to Metal", "Rubber to metal bond strength determination for engine mounts and anti-vibration parts."],
    ["IS 13360-3-1:1994", "Plastics — Methods of Testing — Part 3-1: Determination of Density of Non-Cellular Plastics", "Density and relative density determination by immersion and pycnometer methods."],
    ["IS 13360-4-1:1994", "Plastics — Methods of Testing — Part 4-1: Determination of Tensile Properties", "Tensile strength, elongation and modulus for rigid and semi-rigid plastics."],
    ["IS 13360-5-1:1994", "Plastics — Methods of Testing — Part 5-1: Determination of Flexural Properties", "Flexural modulus and strength determination for plastic mouldings."],
    ["IS 13360-5-2:1994", "Plastics — Methods of Testing — Part 5-2: Determination of Compressive Properties", "Compressive strength and deformation testing of plastics."],
    ["IS 13360-6-1:1994", "Plastics — Methods of Testing — Part 6-1: Determination of Izod Impact Strength", "Izod impact testing of rigid plastics and moulding compounds."],
    ["IS 13360-6-2:1994", "Plastics — Methods of Testing — Part 6-2: Determination of Charpy Impact Strength", "Charpy impact strength determination for plastic specimens."],
    ["IS 13360-7-1:1994", "Plastics — Methods of Testing — Part 7-1: Determination of Hardness (Rockwell)", "Rockwell hardness testing of plastics and composites."],
    ["IS 13360-8-1:1994", "Plastics — Methods of Testing — Part 8-1: Determination of Water Absorption", "Water absorption testing for plastic materials and products."],
    ["IS 13360-9-1:1994", "Plastics — Methods of Testing — Part 9-1: Determination of Thermal Properties", "Vicat softening temperature and heat deflection testing."],
    ["IS 13360-10-1:1994", "Plastics — Methods of Testing — Part 10-1: Determination of Electrical Properties", "Volume resistivity, surface resistivity and dielectric strength of plastics."],
    ["IS 13360-11-1:1994", "Plastics — Methods of Testing — Part 11-1: Determination of Flammability", "Burning rate and flammability classification tests for plastics."],
    ["IS 13360-12-1:1994", "Plastics — Methods of Testing — Part 12-1: Determination of Optical Properties", "Light transmission, haze and gloss measurement for transparent plastics."],
    ["IS 12235-1:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 1: Sampling", "Sampling procedures for UPVC pipe and fitting consignments."],
    ["IS 12235-2:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 2: Measurement of Dimensions", "Diameter, wall thickness and ovality measurement for UPVC pipes."],
    ["IS 12235-3:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 3: Density and Specific Gravity", "Density determination for UPVC pipe compounds."],
    ["IS 12235-4:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 4: Resistance to Internal Pressure", "Hydrostatic pressure testing to establish pipe pressure class."],
    ["IS 12235-5:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 5: Heat Reversion", "Heat reversion test indicating orientation and moulding stresses."],
    ["IS 12235-6:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 6: Vicat Softening Temperature", "Softening temperature determination for UPVC pipes."],
    ["IS 12235-7:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 7: Impact Strength", "Falling weight impact testing of UPVC pipes."],
    ["IS 12235-8:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 8: Sulphate Resistance", "Sulphate attack resistance testing for drainage pipes."],
    ["IS 12235-9:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 9: Tensile Properties", "Tensile strength and elongation testing of UPVC pipe material."],
    ["IS 12235-10:1985", "Methods of Test for Unplasticized PVC Pipes and Fittings — Part 10: Toxicity and Purity", "Extractability and toxicity checks for pipes used in potable water lines."],
    ["IS 14930-1:2001", "Installation of Unplasticized PVC Pipes — Code of Practice — Part 1: General", "Handling, jointing and laying practice for UPVC pipelines."],
    ["IS 14930-2:2001", "Installation of Unplasticized PVC Pipes — Code of Practice — Part 2: Pressure Piping", "Installation practice for pressure pipelines including thrust blocks."],
    ["IS 13722:1993", "Rubber Gaskets for UPVC Pipes — Specification", "Elastomeric gasket requirements for push-fit pipe joints."],
    ["IS 13158:1991", "Rubber Hoses for Water Suction and Delivery — Specification", "Hose construction, burst pressure and adhesion requirements."],
    ["IS 12456:1988", "Rubber and Plastics — Hoses for Compressed Air Applications — Specification", "Compressed air hose pressure rating, adhesion and ozone resistance."],
    ["IS 15633:2005", "Pneumatic Tyres for Passenger Car Vehicles — Specification", "Passenger car tyre dimensions, load index, speed symbol and endurance requirements.", "Q:Pneumatic Tyres (Quality Control) Order", { keywords: ["tyre", "car tyre", "टायर"] }],
    ["IS 15636-2:2012", "Automotive Vehicles — Tyres — Part 2: General Requirements", "General tyre requirements covering marking, load rating and test criteria.", "Q:Pneumatic Tyres (Quality Control) Order"],
  ],
};

const TEXTILES: Block = {
  category: "consumer",
  rows: [
    ["IS 1770:1976", "Cotton Fabrics — Specification", "Construction, count, width and strength parameters for cotton fabrics."],
    ["IS 3442:1980", "Cotton Canvas — Specification", "Canvas grades by mass, weave and breaking strength for tents and covers."],
    ["IS 10024:1981", "Polyester Blended Fabrics — Specification", "Blend composition, dimensional stability and strength requirements."],
    ["IS 13276:1992", "Terry Towels — Specification", "Towelling mass, absorbency and colour fastness requirements."],
    ["IS 2970:1979", "Fabric for Uniforms — Specification", "Uniform fabric parameters for institutional and industrial clothing."],
    ["IS 3636:1979", "Cotton Durries — Specification", "Durrie dimensions, weave and colour fastness requirements."],
    ["IS 3801:1989", "Method for Determination of Weight of Textile Materials", "Mass per unit area determination for woven and knitted fabrics."],
    ["IS 3916:1985", "Method for Determination of Thread Density in Fabrics", "Ends and picks per unit length measurement for woven fabric."],
    ["IS 4086:1976", "Method for Determination of Weave of Fabrics", "Weave analysis and drafting for woven textile structures."],
    ["IS 4682-1:1974", "Method for Determination of Colour Fastness — Part 1: General Principles", "General test principles for colour fastness testing of textiles."],
    ["IS 4887:1975", "Method for Determination of Colour Fastness to Washing", "Washing fastness grades for dyed and printed textiles."],
    ["IS 5254:1985", "Method for Determination of Colour Fastness to Rubbing", "Crocking fastness by wet and dry rubbing of textiles."],
    ["IS 6144:1971", "Method for Determination of Colour Fastness to Light", "Xenon and carbon arc light fastness testing of textiles."],
    ["IS 7192:1973", "Method for Determination of Colour Fastness to Perspiration", "Acid and alkaline perspiration fastness grading."],
    ["IS 7374:1974", "Method for Determination of Colour Fastness to Bleaching", "Bleaching fastness for dyed yarns and fabrics."],
    ["IS 7710:1975", "Method for Determination of Colour Fastness to Sea Water", "Sea water fastness testing for marine and beachwear textiles."],
    ["IS 7904:1975", "Method for Determination of Shrinkage of Textiles on Washing", "Dimensional change measurement after laundering."],
    ["IS 2617:1971", "Method for Determination of Yarn Count (Folded Yarn)", "Count determination for folded and plied yarns."],
    ["IS 1848:1991", "Method for Determination of Tensile Strength of Yarns", "Single yarn and lea strength testing of spun and filament yarns."],
    ["IS 2654:1978", "Method for Determination of Crimp and Take-Up of Yarn", "Crimp percentage measurement for yarns and fabrics."],
    ["IS 2759:1979", "Method for Determination of Moisture Content and Regain in Textiles", "Moisture regain determination for cotton, wool and man-made fibres."],
    ["IS 6249:1979", "Method for Determination of Thickness of Textile Fabrics", "Fabric thickness measurement under specified pressure."],
    ["IS 5693:1970", "Method for Determination of Air Permeability of Textile Fabrics", "Air flow based permeability measurement for fabric comfort assessment."],
    ["IS 14187:1994", "Insect Repellent Finished Fabrics — Specification", "Performance and wash durability requirements for insect repellent textiles."],
    ["IS 15537:2004", "Fire Retardant Fabrics — Specification", "Flame retardant performance and after-wash retention requirements for protective textiles."],
    ["IS 3431:1984", "Woollen Fabrics — Specification", "Wool content, mass and strength requirements for woollen textiles."],
    ["IS 1943:1982", "Jute Hessian — Specification", "Hessian cloth grades by mass and weave for packaging use.", "Q:Jute Packaging Materials (Quality Control) Order"],
    ["IS 2717:1982", "Jute Sacking Bags — Specification", "Sacking bag size, mass and strength for grain packaging.", "Q:Jute Packaging Materials (Quality Control) Order"],
    ["IS 2840:1965", "Jute Webbing and Twine — Specification", "Webbing and twine strength and mass requirements for agricultural packing."],
  ],
};

const LEATHER_AND_PAPER: Block = {
  category: "consumer",
  rows: [
    ["IS 5812:1970", "Leather — Specification for Upper Leather", "Upper leather thickness, tensile strength and flexing requirements for footwear."],
    ["IS 5914:1970", "Leather — Specification for Sole Leather", "Sole leather substance, water absorption and abrasion requirements."],
    ["IS 5469:1969", "Leather — Specification for Lining Leather", "Lining leather softness, colour fastness and thickness requirements."],
    ["IS 10149:1982", "Leather — Specification for Garment Leather", "Garment leather flexing endurance, colour fastness and substance limits."],
    ["IS 10385:1982", "Leather — Specification for Bag and Case Leather", "Bag leather tensile strength and finish durability requirements."],
    ["IS 10489:1983", "Leather — Specification for Industrial Glove Leather", "Industrial glove leather chrome content, pH and strength requirements."],
    ["IS 6613:1972", "Writing and Printing Paper — Specification", "Paper grades by substance, tear strength, opacity and brightness."],
    ["IS 5716:1970", "Kraft Paper — Specification", "Kraft paper grades for packaging with burst and tear strength requirements."],
    ["IS 1398:1988", "Carton Board and Box Board — Specification", "Board substances, stiffness and moisture requirements for cartons."],
    ["IS 14612:1998", "Duplex Board — Specification", "Coated duplex board whiteness, stiffness and printability requirements."],
    ["IS 9036:1979", "Corrugated Fibre Board Boxes — Specification", "Box construction, burst strength and compression requirements for shipping.", "Q:Packaging (Quality Control) Order"],
    ["IS 2771-1:1990", "Methods of Test for Paper and Board — Part 1: Sampling", "Sampling procedures for paper and board consignments."],
    ["IS 1060-1:1987", "Methods of Test for Paper and Board — Part 1: Determination of Moisture and Ash", "Moisture and ash determination in paper and board."],
    ["IS 10831:1984", "Paper for Offset Printing — Specification", "Offset printing paper dimensional stability and surface requirements."],
    ["IS 9873-6:2011", "Safety of Toys — Part 6: Swings, Slides and Similar Activity Toys for Indoor and Outdoor Use (Test Methods)", "Test methods for activity toy stability and strength."],
    ["IS 11656:1986", "Toy Safety — Packaging Requirements", "Packaging safety, choking hazard and warning requirements for toys.", "Q:Toys (Quality Control) Order"],
  ],
};

export const STD_WAVE13 = buildBlocks(
  INDUSTRIAL_CHEMICALS,
  PLASTICS_AND_RUBBER,
  TEXTILES,
  LEATHER_AND_PAPER,
);
