/* Extra catalogue wave 12 — food, dairy, agriculture, drinking water and
 * management-system standards used in BIS certification. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const FOOD_QCO = "Food Products (Quality Control) Order";
const FERTILIZER_QCO = "Fertilizer (Quality Control) Order";

const FOOD_PRODUCTS: Block = {
  category: "food",
  qco: FOOD_QCO,
  rows: [
    ["IS 1479-1:1960", "Methods of Test for Dairy Industry — Part 1: Chemical Analysis of Milk", "Reference methods for fat, solids-not-fat, acidity and adulterant detection in milk.", "V", { keywords: ["milk testing", "dairy", "दूध", "fat test"] }],
    ["IS 1479-2:1961", "Methods of Test for Dairy Industry — Part 2: Chemical Analysis of Milk Products", "Analysis of butter, ghee, cheese, curd and dried milk products for conformity testing."],
    ["IS 2488-1:1966", "Methods of Sampling and Test for Milk and Milk Products — Part 1: Sampling", "Sampling plans for liquid milk and packaged dairy products."],
    ["IS 4941:1994", "Extracted Honey — Specification", "Honey quality limits on moisture, sucrose, fructose-glucose ratio, ash and HMF.", "V", { keywords: ["honey", "शहद", "sweetener"] }],
    ["IS 3633:2003", "Tea — Specification", "Black tea requirements covering total ash, water extract, crude fibre and organoleptic quality.", "V", { keywords: ["tea", "चाय", "black tea"] }],
    ["IS 13854:1994", "Milk Chocolate — Specification", "Compositional requirements for milk chocolate covering cocoa solids, milk solids and fat."],
    ["IS 2796:1981", "Instant Coffee — Specification", "Instant coffee quality requirements including moisture, caffeine content and solubility.", "V", { keywords: ["coffee", "कॉफी", "instant coffee"] }],
    ["IS 1151:1973", "Refined Wheat Flour (Maida) — Specification", "Maida grading, moisture, gluten and ash requirements for bakery and domestic use.", "Q:Food Products (Quality Control) Order"],
    ["IS 7224:1974", "Bakery Products — Specifications for Bread and Buns", "Bread and bun composition, moisture, acidity and hygiene requirements."],
    ["IS 3886:1984", "Fruit Squashes, Cordials, Crushes and Barley Waters — Specification", "Beverage base requirements covering fruit content, total soluble solids and preservatives.", "V"],
    ["IS 1983:1974", "Fruit Juices and Nectars — Specification", "Juice and nectar requirements including fruit content, Brix and permitted additives."],
    ["IS 546:1968", "Mustard Oil — Specification", "Mustard oil quality parameters including fatty acid composition, moisture and colour."],
    ["IS 548-1:1964", "Methods of Sampling and Test for Oils and Fats — Part 1: Sampling", "Sampling procedures for edible oil consignments."],
    ["IS 548-2:1964", "Methods of Sampling and Test for Oils and Fats — Part 2: Physical and Chemical Tests", "Determination of refractive index, saponification value, iodine value and free fatty acids."],
    ["IS 1944:1970", "Groundnut Oil — Specification", "Groundnut oil purity, FFA limits and test requirements.", "M"],
    ["IS 13147-1:1992", "Spices and Condiments — Methods of Test — Part 1: Sampling", "Sampling of whole and ground spices for conformity testing."],
    ["IS 1987:1973", "Turmeric (Haldi) — Specification", "Turmeric grades, curcumin content, moisture and ash limits.", "M", { keywords: ["turmeric", "haldi", "हल्दी"] }],
    ["IS 1988:1976", "Black Pepper — Specification", "Black pepper grading, piperine content, moisture and extraneous matter limits.", "M"],
    ["IS 4817:1975", "Coriander (Dhania) — Specification", "Coriander seed quality requirements including volatile oil and ash."],
    ["IS 13654:1993", "Iodized Salt — Specification", "Iodized common salt iodine content, purity and packaging requirements.", "M", { keywords: ["salt", "iodised salt", "नमक"] }],
    ["IS 1804:1973", "Common Salt — Specification", "Edible common salt purity, insoluble matter and moisture limits."],
    ["IS 1223:1973", "Pasteurized Butter — Specification", "Butter composition, moisture, salt and microbiological requirements.", "V"],
    ["IS 9856-1:1981", "Infant Milk Foods — Part 1: Specification", "Compositional and safety requirements for infant milk food including vitamins and minerals."],
    ["IS 13697:1993", "Weaning Foods — Specification", "Cereal-based weaning food composition, energy density and hygiene limits."],
    ["IS 7128:1973", "Biscuits — Specification", "Biscuit classification, moisture, fat and hygiene requirements.", "V"],
    ["IS 16071-1:2012", "Food Safety Management — Requirements for Food Business Operations — Part 1: General Requirements", "Requirements for food businesses covering hygiene, traceability and process control."],
    ["IS 14627:1999", "Meat and Meat Products — Hygienic Requirements", "Hygiene and quality requirements for slaughter, processing and packaging of meat.", "M"],
    ["IS 1224-1:1970", "Methods of Test for Edible Starches — Part 1: General Methods", "Test procedures for moisture, ash and acidity of edible starches."],
    ["IS 1224-2:1970", "Methods of Test for Edible Starches — Part 2: Physical and Chemical Tests", "Viscosity, granule size and chemical tests for starch conforming to specification."],
  ],
};

const AGRI_AND_FERTILIZER: Block = {
  category: "food",
  qco: FERTILIZER_QCO,
  rows: [
    ["IS 1473:1998", "Urea (Technical Grade) — Specification", "Urea composition, biuret and moisture limits for fertilizer use.", "M", { keywords: ["urea", "fertilizer", "यूरिया", "khad"] }],
    ["IS 251:1998", "Sulphur for Agricultural Purposes — Specification", "Sulphur purity, acidity and particle size requirements for agricultural use.", "M"],
    ["IS 239:1998", "Ammonium Sulphate — Specification", "Ammonium sulphate nitrogen content and impurity limits.", "M"],
    ["IS 4320:2015", "Single Super Phosphate — Specification", "SSP phosphorus content, free acid and moisture requirements for fertilizer use.", "M"],
    ["IS 2779:2010", "Muriate of Potash (Potassium Chloride) — Specification", "MOP potassium content, moisture and particle size requirements.", "M"],
    ["IS 15130-1:2002", "Di-Ammonium Phosphate — Specification", "DAP nitrogen and phosphorus content with moisture and granule strength limits.", "M"],
    ["IS 17046:2018", "Biofertilizers — Specification", "Rhizobium, azotobacter and phosphate solubilising biofertilizer quality requirements.", "M", { keywords: ["biofertilizer", "जैव उर्वरक", "organic"] }],
    ["IS 12134-1:1987", "Agricultural Tractors — Specification — Part 1: General Purpose Tractors", "Tractor power class, hitch and safety requirements for general purpose agricultural tractors."],
    ["IS 6285:1985", "Steel Tubular Hand Pumps — Specification", "Hand pump components, discharge rate and durability requirements."],
    ["IS 5998:1985", "Water Lifting Devices for Irrigation — Code of Practice", "Selection and installation practice for pumps used in irrigation."],
    ["IS 11420-1:1985", "Mould Board Plough — Specification", "Mould board plough dimensions and material requirements."],
    ["IS 13854:2000", "Drip Irrigation Systems — Specification", "Emitter, filter and lateral requirements for drip irrigation installations.", "Q:Micro Irrigation (Quality Control) Order"],
    ["IS 10875:1999", "Sprinkler Irrigation Systems — Specification", "Sprinkler nozzle, pressure and uniformity requirements for irrigation systems."],
    ["IS 15885:2010", "Agricultural Produce Grading and Marking — Guidelines", "Grading and AGMARK-style marking guidance for agricultural produce."],
    ["IS 14984:2001", "Cold Chain Logistics for Agricultural Produce — Guidelines", "Temperature control and handling guidance for cold chain transport of produce."],
    ["IS 13188:1992", "Rural Sanitary Latrine — Specification", "Twin pit pour flush latrine design and construction requirements for rural sanitation."],
    ["IS 16072:2012", "Solar Drying of Agricultural Produce — Guidelines", "Solar drier design, hygiene and performance guidance for small farm drying."],
    ["IS 12992:1990", "Poultry Feed — Specification", "Nutrient requirements for poultry feed including protein, fat and mineral content."],
    ["IS 1374:1981", "Compounded Feeds for Cattle — Specification", "Cattle feed composition, protein and mineral requirements.", "M"],
    ["IS 1664:2002", "Compounded Feeds for Poultry — Specification", "Poultry feed formulation requirements for starter, grower and layer rations."],
  ],
};

const DRINKING_WATER: Block = {
  category: "food",
  rows: [
    ["IS 3025-2:1983", "Methods of Sampling and Test for Water and Wastewater — Part 2: Determination of Colour", "Visual and spectrophotometric colour measurement of water."],
    ["IS 3025-3:1983", "Methods of Sampling and Test for Water and Wastewater — Part 3: Determination of Temperature", "Temperature measurement procedure for water samples and receiving waters."],
    ["IS 3025-4:1983", "Methods of Sampling and Test for Water and Wastewater — Part 4: Determination of Odour", "Threshold odour number determination for potable water."],
    ["IS 3025-5:1983", "Methods of Sampling and Test for Water and Wastewater — Part 5: Determination of Taste", "Taste rating procedure used in potability assessment."],
    ["IS 3025-6:1983", "Methods of Sampling and Test for Water and Wastewater — Part 6: Determination of Electrical Conductivity", "Conductivity measurement as an indicator of dissolved ionic content."],
    ["IS 3025-7:1984", "Methods of Sampling and Test for Water and Wastewater — Part 7: Determination of Alkalinity", "Alkalinity titration for carbonate, bicarbonate and hydroxide species."],
    ["IS 3025-8:1984", "Methods of Sampling and Test for Water and Wastewater — Part 8: Determination of Acidity", "Acidity determination for aggressive waters and effluents."],
    ["IS 3025-12:1983", "Methods of Sampling and Test for Water and Wastewater — Part 12: Determination of Hardness", "EDTA titrimetric determination of total and calcium hardness."],
    ["IS 3025-13:1983", "Methods of Sampling and Test for Water and Wastewater — Part 13: Determination of Dissolved Oxygen", "Winkler and membrane electrode methods for dissolved oxygen."],
    ["IS 3025-14:1984", "Methods of Sampling and Test for Water and Wastewater — Part 14: Determination of Biochemical Oxygen Demand", "BOD determination at 20 degrees C with and without seeding."],
    ["IS 3025-16:1984", "Methods of Sampling and Test for Water and Wastewater — Part 16: Determination of Chemical Oxygen Demand", "Dichromate reflux COD method for organic load assessment."],
    ["IS 3025-19:1984", "Methods of Sampling and Test for Water and Wastewater — Part 19: Determination of Ammoniacal Nitrogen", "Ammoniacal nitrogen by distillation and Nesslerisation."],
    ["IS 3025-20:1983", "Methods of Sampling and Test for Water and Wastewater — Part 20: Determination of Nitrate Nitrogen", "Nitrate nitrogen by phenol disulphonic acid and UV methods."],
    ["IS 3025-21:1983", "Methods of Sampling and Test for Water and Wastewater — Part 21: Determination of Nitrite Nitrogen", "Colorimetric nitrite nitrogen determination for potable water."],
    ["IS 3025-28:1986", "Methods of Sampling and Test for Water and Wastewater — Part 28: Determination of Fluoride", "SPADNS and ion-selective electrode fluoride methods."],
    ["IS 3025-29:1986", "Methods of Sampling and Test for Water and Wastewater — Part 29: Determination of Iron", "Colorimetric determination of total and dissolved iron."],
    ["IS 3025-30:1986", "Methods of Sampling and Test for Water and Wastewater — Part 30: Determination of Manganese", "Persulphate-colorimetric manganese determination."],
    ["IS 3025-31:1988", "Methods of Sampling and Test for Water and Wastewater — Part 31: Determination of Arsenic", "Silver diethyldithiocarbamate method for arsenic in water."],
    ["IS 3025-36:1987", "Methods of Sampling and Test for Water and Wastewater — Part 36: Determination of Mercury", "Cold vapour atomic absorption determination of mercury."],
    ["IS 3025-37:1987", "Methods of Sampling and Test for Water and Wastewater — Part 37: Determination of Cadmium", "Atomic absorption determination of cadmium in potable water."],
    ["IS 3025-38:1987", "Methods of Sampling and Test for Water and Wastewater — Part 38: Determination of Lead", "Lead determination by AAS and dithizone extraction."],
    ["IS 3025-42:1992", "Methods of Sampling and Test for Water and Wastewater — Part 42: Determination of Copper", "Copper determination by atomic absorption spectroscopy."],
    ["IS 3025-43:1992", "Methods of Sampling and Test for Water and Wastewater — Part 43: Determination of Zinc", "Zinc determination in drinking water and effluents."],
    ["IS 3025-46:1994", "Methods of Sampling and Test for Water and Wastewater — Part 46: Determination of Chromium", "Hexavalent and total chromium determination by colorimetry and AAS."],
    ["IS 3025-47:1994", "Methods of Sampling and Test for Water and Wastewater — Part 47: Determination of Nickel", "Nickel determination for industrial effluents and receiving waters."],
    ["IS 3025-49:1994", "Methods of Sampling and Test for Water and Wastewater — Part 49: Determination of Phenolic Compounds", "Phenolic compound determination by aminoantipyrine extraction."],
    ["IS 3025-50:1995", "Methods of Sampling and Test for Water and Wastewater — Part 50: Determination of Cyanide", "Cyanide determination for drinking water and trade effluents."],
    ["IS 3025-51:1996", "Methods of Sampling and Test for Water and Wastewater — Part 51: Determination of Oil and Grease", "Gravimetric oil and grease determination by solvent extraction."],
    ["IS 3025-52:1996", "Methods of Sampling and Test for Water and Wastewater — Part 52: Determination of Residual Chlorine (Alternate Methods)", "DPD and amperometric residual chlorine methods."],
    ["IS 3025-53:1996", "Methods of Sampling and Test for Water and Wastewater — Part 53: Determination of Sodium and Potassium", "Flame photometric determination of sodium and potassium."],
    ["IS 3025-54:1996", "Methods of Sampling and Test for Water and Wastewater — Part 54: Determination of Calcium and Magnesium", "EDTA complexometric determination of calcium and magnesium."],
    ["IS 3025-55:1996", "Methods of Sampling and Test for Water and Wastewater — Part 55: Determination of Phosphate", "Ascorbic acid and stannous chloride phosphate methods."],
    ["IS 3025-56:1996", "Methods of Sampling and Test for Water and Wastewater — Part 56: Determination of Sulphide", "Methylene blue method for sulphide in water and wastewater."],
    ["IS 3025-57:1996", "Methods of Sampling and Test for Water and Wastewater — Part 57: Determination of Pesticide Residues", "Gas chromatographic determination of organochlorine and organophosphorus residues."],
    ["IS 3025-60:2008", "Methods of Sampling and Test for Water and Wastewater — Part 60: Determination of Total Coliforms by Membrane Filtration", "Membrane filtration enumeration of total coliforms in potable water."],
  ],
};

const MANAGEMENT_SYSTEMS: Block = {
  category: "services",
  rows: [
    ["IS/ISO 9001:2015", "Quality Management Systems — Requirements", "The quality management system standard used for BIS management systems certification.", "V", { keywords: ["iso 9001", "quality management", "qms"], related: ["IS/ISO 14001:2015"] }],
    ["IS/ISO 14001:2015", "Environmental Management Systems — Requirements with Guidance for Use", "Environmental management system requirements covering aspects, impacts and legal compliance.", "V", { keywords: ["iso 14001", "environment", "ems"] }],
    ["IS/ISO 45001:2018", "Occupational Health and Safety Management Systems — Requirements with Guidance for Use", "Requirements for occupational health and safety management systems in workplaces.", "V", { keywords: ["iso 45001", "safety management", "ohs"] }],
    ["IS/ISO 50001:2018", "Energy Management Systems — Requirements with Guidance for Use", "Energy management system requirements including energy performance indicators.", "V", { keywords: ["iso 50001", "energy management", "efficiency"] }],
    ["IS/ISO 22000:2018", "Food Safety Management Systems — Requirements for Any Organization in the Food Chain", "Food safety management requirements covering HACCP principles and prerequisite programmes.", "V", { keywords: ["iso 22000", "food safety", "haccp"], related: ["IS/ISO 9001:2015"] }],
    ["IS/ISO 22005:2007", "Traceability in the Feed and Food Chain — General Principles and Basic Requirements", "Feed and food traceability system design principles.", "V"],
    ["IS/ISO 17025:2017", "General Requirements for the Competence of Testing and Calibration Laboratories", "Competence requirements for testing and calibration laboratories.", "V", { keywords: ["iso 17025", "laboratory", "accreditation"] }],
    ["IS/ISO 17020:2012", "Conformity Assessment — Requirements for the Operation of Various Types of Bodies Performing Inspection", "Requirements for inspection bodies performing conformity assessment."],
    ["IS/ISO 27001:2022", "Information Security, Cybersecurity and Privacy Protection — Information Security Management Systems — Requirements", "Information security management system requirements for organisations handling data.", "V", { keywords: ["iso 27001", "information security", "isms"] }],
    ["IS/ISO 17021-1:2015", "Conformity Assessment — Requirements for Bodies Providing Audit and Certification of Management Systems", "Competence and process requirements for certification bodies.", "V"],
    ["IS/ISO 31000:2018", "Risk Management — Guidelines", "Principles and framework for risk management in organisations."],
    ["IS/ISO 22301:2019", "Security and Resilience — Business Continuity Management Systems — Requirements", "Business continuity management system requirements and resilience planning."],
    ["IS/ISO 14064-1:2018", "Greenhouse Gases — Part 1: Specification with Guidance at the Organization Level for Quantification and Reporting of Greenhouse Gas Emissions", "Organisational GHG inventory quantification and reporting requirements."],
    ["IS/ISO 20400:2017", "Sustainable Procurement — Guidance", "Guidance on integrating sustainability into procurement decisions and supply chains."],
    ["IS/ISO 2446:2008", "Milk — Determination of Fat Content (Routine Method)", "Gerber-type routine determination of fat in milk."],
    ["IS/ISO 8968-1:2014", "Milk and Milk Products — Determination of Nitrogen Content — Part 1: Kjeldahl Principle", "Kjeldahl nitrogen and protein determination in milk and dairy products."],
  ],
};

const FOOD_MICROBIOLOGY: Block = {
  category: "food",
  rows: [
    ["IS/ISO 4833-1:2013", "Microbiology of the Food Chain — Horizontal Method for the Enumeration of Microorganisms — Part 1: Colony Count at 30 Degrees C by the Pour Plate Technique", "Aerobic mesophilic colony count by pour plate technique."],
    ["IS/ISO 4833-2:2013", "Microbiology of the Food Chain — Horizontal Method for the Enumeration of Microorganisms — Part 2: Colony Count at 30 Degrees C by the Surface Plating Technique", "Surface plating colony count procedure for food samples."],
    ["IS/ISO 6579-1:2017", "Microbiology of the Food Chain — Horizontal Method for the Detection, Enumeration and Serotyping of Salmonella — Part 1: Detection of Salmonella spp.", "Salmonella detection protocol for food and feed samples."],
    ["IS/ISO 7251:2005", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Detection and Enumeration of Presumptive Escherichia coli (Most Probable Number Technique)", "MPN based presumptive E. coli detection and enumeration."],
    ["IS/ISO 6888-1:1999", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Coagulase-Positive Staphylococci — Part 1: Baird-Parker Agar Medium", "Staphylococcus aureus enumeration using Baird-Parker medium."],
    ["IS/ISO 6888-2:1999", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Coagulase-Positive Staphylococci — Part 2: Rabbit Plasma Fibrinogen Agar Medium", "RPF agar based enumeration of coagulase-positive staphylococci."],
    ["IS/ISO 7937:2004", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Clostridium perfringens", "Colony count technique for Clostridium perfringens in food."],
    ["IS/ISO 10272-1:2017", "Microbiology of the Food Chain — Horizontal Method for Detection and Enumeration of Campylobacter spp. — Part 1: Detection Method", "Campylobacter detection in food chain samples."],
    ["IS/ISO 11290-1:2017", "Microbiology of the Food Chain — Horizontal Method for the Detection and Enumeration of Listeria monocytogenes and of Listeria spp. — Part 1: Detection Method", "Listeria detection method for ready-to-eat foods."],
    ["IS/ISO 11290-2:2017", "Microbiology of the Food Chain — Horizontal Method for the Detection and Enumeration of Listeria monocytogenes — Part 2: Enumeration Method", "Listeria enumeration for product conformity limits."],
    ["IS/ISO 21527-1:2008", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Yeasts and Moulds — Part 1: Colony Count Technique in Products with Water Activity Greater than 0.95", "Yeast and mould enumeration in high moisture foods."],
    ["IS/ISO 21527-2:2008", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Yeasts and Moulds — Part 2: Colony Count Technique in Products with Water Activity Less than or Equal to 0.95", "Yeast and mould enumeration in dry and low moisture foods."],
    ["IS/ISO 16649-2:2001", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Beta-Glucuronidase-Positive Escherichia coli — Part 2: Colony-Count Technique at 44 Degrees C Using 5-Bromo-4-Chloro-3-Indolyl Beta-D-Glucuronide", "Rapid E. coli enumeration by chromogenic colony count."],
    ["IS/ISO 21872-1:2017", "Microbiology of the Food Chain — Horizontal Method for the Determination of Vibrio spp. — Part 1: Detection of Potentially Enteropathogenic Vibrio parahaemolyticus, Vibrio cholerae and Vibrio vulnificus", "Vibrio detection method for seafood and water samples."],
    ["IS/ISO 22964:2017", "Microbiology of the Food Chain — Horizontal Method for the Detection of Cronobacter spp.", "Cronobacter detection in powdered infant formula and dairy powders."],
    ["IS/ISO 11133:2014", "Microbiology of Food, Animal Feed and Water — Preparation, Production, Storage and Performance Testing of Culture Media", "Culture media preparation and performance testing requirements for laboratories."],
  ],
};

const FOOD_NUTRITION: Block = {
  category: "food",
  rows: [
    ["IS/ISO 2171:2007", "Cereals, Pulses and By-Products — Determination of Ash Yield by Incineration", "Total ash determination for cereals, pulses and milling products."],
    ["IS/ISO 712:2009", "Cereals and Cereal Products — Determination of Moisture Content (Routine Reference Method)", "Routine moisture determination for grain and flour."],
    ["IS/ISO 6647-1:2020", "Rice — Determination of Amylose Content — Part 1: Reference Method", "Amylose content determination for rice quality grading."],
    ["IS/ISO 5983-1:2005", "Animal Feeding Stuffs — Determination of Nitrogen Content and Calculation of Crude Protein Content — Part 1: Kjeldahl Method", "Crude protein determination in animal feed by Kjeldahl digestion."],
    ["IS/ISO 6865:2000", "Animal Feeding Stuffs — Determination of Crude Fibre Content — Method with Intermediate Filtration", "Crude fibre determination for feed quality control."],
    ["IS/ISO 6496:1999", "Animal Feeding Stuffs — Determination of Moisture and Other Volatile Matter Content", "Moisture and volatile matter determination in feed."],
    ["IS/ISO 5984:2002", "Animal Feeding Stuffs — Determination of Crude Ash", "Crude ash determination for feed mineral content."],
    ["IS/ISO 5498:1981", "Agricultural Food Products — Determination of Crude Fibre Content — General Method", "General crude fibre determination for agricultural food products."],
  ],
};

export const STD_WAVE12 = buildBlocks(
  FOOD_PRODUCTS,
  AGRI_AND_FERTILIZER,
  DRINKING_WATER,
  MANAGEMENT_SYSTEMS,
  FOOD_MICROBIOLOGY,
  FOOD_NUTRITION,
);
