import { db } from "@/db";
import { knowledgeDocs, labs, licences, standards } from "@/db/schema";

/* ------------------------------ STANDARDS ------------------------------ */

const STD = [
  {
    code: "IS 456:2000",
    title: "Plain and Reinforced Concrete — Code of Practice",
    category: "construction",
    status: "current",
    mandatory: false,
    scheme: "Code of Practice (voluntary)",
    qco: null,
    summary:
      "The most-used civil engineering code in India. Specifies materials, workmanship, durability requirements and design basis for plain and reinforced concrete structures. Fourth revision introduced durability clauses based on exposure conditions.",
    keywords: ["concrete", "rcc", "cement", "civil", "building", "beam", "column", "m20", "m25", "grade", "सीमेंट", "कंक्रीट"],
    sections: [
      { clause: "5", title: "Materials", summary: "Requirements for cement, aggregates, water, admixtures and reinforcement." },
      { clause: "6", title: "Concrete mix proportioning", summary: "Nominal and design mixes; grade designation up to M80." },
      { clause: "8", title: "Durability of concrete", summary: "Exposure classes, max w/c ratio and minimum cement content." },
      { clause: "26.2", title: "Design requirements", summary: "Limit state design basis for flexure, shear and deflection." },
      { clause: "26.5", title: "Detailing of reinforcement", summary: "Development length, lap splices, curtailment and spacing rules." },
    ],
    related: ["IS 383:2016", "IS 2386-3:1963", "IS 516:1959", "IS 1786:2008"],
    editions: 4,
  },
  {
    code: "IS 269:2015",
    title: "Ordinary Portland Cement — Specification",
    category: "construction",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Cement (Quality Control) Order",
    summary:
      "Specifies chemical and physical requirements for 33, 43 and 53 grade ordinary Portland cement, including fineness, soundness, setting time and compressive strength. Cement cannot be manufactured or sold in India without BIS certification.",
    keywords: ["cement", "opc", "33 grade", "43 grade", "53 grade", "clinker", "gypsum", "सीमेंट"],
    sections: [
      { clause: "6", title: "Chemical requirements", summary: "Lime saturation, insoluble residue, magnesia, sulphur limits." },
      { clause: "7", title: "Physical requirements", summary: "Fineness, soundness by Le-Chatelier, initial/final setting time." },
      { clause: "7.2", title: "Compressive strength", summary: "72 h, 168 h and 672 h mortar cube strength per grade." },
      { clause: "10", title: "Marking", summary: "Bag marking: ISI mark, grade, week/year of manufacture, net mass." },
    ],
    related: ["IS 1489-1:2015", "IS 8112:2013", "IS 12269:2013", "IS 4031-1:1996"],
    editions: 6,
  },
  {
    code: "IS 1489-1:2015",
    title: "Portland Pozzolana Cement — Part 1: Flyash Based — Specification",
    category: "construction",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Cement (Quality Control) Order",
    summary:
      "Covers PPC manufactured with fly ash as pozzolana (15–35%). Lower heat of hydration and improved long-term durability make it the dominant cement in Indian housing.",
    keywords: ["cement", "ppc", "fly ash", "pozzolana", "सीमेंट"],
    sections: [
      { clause: "4", title: "Composition", summary: "Permitted fly ash content and clinker proportion." },
      { clause: "7", title: "Physical requirements", summary: "Fineness, soundness, setting time and strength classes." },
    ],
    related: ["IS 269:2015", "IS 3812-1:2013"],
    editions: 4,
  },
  {
    code: "IS 1786:2008",
    title: "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement — Specification",
    category: "construction",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Steel & Steel Products (Quality Control) Order",
    summary:
      "The TMT/rebar standard. Covers grades Fe 415 to Fe 600 including corrosion-resistant Fe 415S/500S with limits on carbon, sulphur, phosphorus, yield strength and percentage elongation.",
    keywords: ["tmt", "rebar", "steel", "fe500", "fe550", "saria", "deformed bars", "सरिया", "इस्पात"],
    sections: [
      { clause: "4", title: "Grades", summary: "Fe 415, Fe 500, Fe 550, Fe 600 and ductile 'D' variants." },
      { clause: "5", title: "Chemical composition", summary: "Carbon equivalent, S&P limits for weldability." },
      { clause: "7", title: "Mechanical tests", summary: "Yield stress, tensile ratio, elongation and bend/rebend tests." },
      { clause: "9", title: "Marking", summary: "Embossed grade marks rolled onto every bar with ISI + CM/L number." },
    ],
    related: ["IS 2062:2011", "IS 456:2000", "IS 1608:2005"],
    editions: 4,
  },
  {
    code: "IS 2062:2011",
    title: "Hot Rolled Medium and High Tensile Structural Steel — Specification",
    category: "construction",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Steel & Steel Products (Quality Control) Order",
    summary:
      "Governs structural steel plates, sections, flats and bars (grades E250–E650 in qualities A/B/C/BR) used in buildings, bridges and industrial structures.",
    keywords: ["structural steel", "e250", "plates", "angles", "channels", "beam", "इस्पात"],
    sections: [
      { clause: "6", title: "Grades & qualities", summary: "E250 to E650 with impact-quality suffixes." },
      { clause: "9", title: "Tensile & bend tests", summary: "Yield, UTS, elongation and internal bend diameter." },
      { clause: "12", title: "Marking", summary: "Marking of grade, quality and ISI licence on material and test certificates." },
    ],
    related: ["IS 1786:2008", "IS 1239-1:2004"],
    editions: 7,
  },
  {
    code: "IS 1239-1:2004",
    title: "Steel Tubes, Tubulars and Other Wrought Steel Fittings — Part 1: Steel Tubes",
    category: "construction",
    status: "current",
    mandatory: false,
    scheme: "ISI Mark (Scheme-I)",
    qco: null,
    summary:
      "Seamless and welded steel tubes in light/medium/heavy classes for water, gas and structural conveyance. Widely referenced as 'GI pipe' standard.",
    keywords: ["gi pipe", "steel tube", "water pipe", "galvanized", "पाइप"],
    sections: [
      { clause: "6", title: "Classification", summary: "Light, medium, heavy classes by wall thickness." },
      { clause: "9", title: "Tests", summary: "Flattening, bend, leak-tightness and galvanizing tests." },
    ],
    related: ["IS 1239-2:2011", "IS 3589:2001"],
    editions: 5,
  },
  {
    code: "IS 694:2010",
    title: "PVC Insulated Cables for Working Voltages up to and including 1100 V — Specification",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Electrical Wires, Cables (Quality Control) Order",
    summary:
      "The house-wiring standard. Covers single- and multi-core PVC insulated non-sheathed and sheathed cords/cables with requirements on conductor class, insulation thickness, flame test and insulation resistance.",
    keywords: ["wire", "cable", "house wiring", "pvc", "frlv", "conductor", "तार", "केबल"],
    sections: [
      { clause: "10", title: "Conductor", summary: "Annealed copper/aluminium, Class 1–5 per IS 8130." },
      { clause: "11", title: "Insulation", summary: "PVC Type A/C, thickness and resistance requirements." },
      { clause: "15", title: "Flame test", summary: "Single-cable flame propagation for FR categories." },
      { clause: "17", title: "Marking", summary: "Continuous marking of ISI, size, CM/L number and voltage grade." },
    ],
    related: ["IS 1554-1:1988", "IS 7098-1:1988", "IS 8130:2013"],
    editions: 4,
  },
  {
    code: "IS 1554-1:1988",
    title: "PVC Insulated (Heavy Duty) Electric Cables — Part 1: For Working Voltages up to and including 1100 V",
    category: "electrical",
    status: "current",
    mandatory: false,
    scheme: "Voluntary (widely certified)",
    qco: null,
    summary: "Heavily used for power distribution feeders in buildings and industry — armoured and unarmoured heavy-duty PVC power cables.",
    keywords: ["power cable", "heavy duty", "armoured", "ht cable", "केबल"],
    sections: [
      { clause: "12", title: "Armouring", summary: "Steel wire/strip armour dimensions and coverage." },
      { clause: "18", title: "Routine tests", summary: "Conductor resistance, HV test and insulation resistance measurement." },
    ],
    related: ["IS 694:2010", "IS 7098-1:1988"],
    editions: 2,
  },
  {
    code: "IS 7098-1:1988",
    title: "Crosslinked Polyethylene Insulated PVC Sheathed Cables — Part 1: For Working Voltages up to and including 1100 V",
    category: "electrical",
    status: "current",
    mandatory: false,
    scheme: "Voluntary (widely certified)",
    qco: null,
    summary: "XLPE-insulated power cables with higher conductor temperature rating (90 °C) replacing PVC in modern installations.",
    keywords: ["xlpe", "power cable", "cable", "केबल"],
    sections: [
      { clause: "11", title: "XLPE insulation", summary: "Crosslinking process, thickness and hot-set test." },
      { clause: "16", title: "Tests", summary: "Partial discharge, tan-delta and ageing requirements." },
    ],
    related: ["IS 1554-1:1988", "IS 7098-2:2011"],
    editions: 2,
  },
  {
    code: "IS 1293:2019",
    title: "Plugs and Socket-Outlets for Household and Similar Purposes — Specification",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Electrical Accessories (Quality Control) Order",
    summary: "Covers rewirable/non-rewirable plugs and socket-outlets up to 16 A 250 V — contact pressure, temperature rise, breaking capacity and shutter safety for the 6A/16A Indian system.",
    keywords: ["plug", "socket", "switch", "16a", "6a", "प्लग", "सॉकेट"],
    sections: [
      { clause: "13", title: "Construction", summary: "Pin dimensions, shutter operation and earthing contact sequence." },
      { clause: "16", title: "Temperature rise", summary: "Terminal and contact temperature limits under rated load." },
      { clause: "21", title: "Breaking capacity", summary: "Endurance and making/breaking performance of socket-outlets." },
    ],
    related: ["IS 3854:1997", "IS 9537-3:1983"],
    editions: 4,
  },
  {
    code: "IS 3854:1997",
    title: "Switches for Domestic and Similar Purposes — Specification",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Electrical Accessories (Quality Control) Order",
    summary: "General-purpose 6 A/16 A flush and surface switches — endurance of 40 000+ operations, glow-wire resistance and clear marking of rating.",
    keywords: ["switch", "modular switch", "स्विच"],
    sections: [
      { clause: "11", title: "Rating & classification", summary: "6 A, 16 A, 240 V switched functions." },
      { clause: "19", title: "Endurance", summary: "Mechanical and electrical operation cycles." },
    ],
    related: ["IS 1293:2019"],
    editions: 2,
  },
  {
    code: "IS 374:2019",
    title: "Electric Ceiling Type Fans and Regulators — Specification",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Electric Ceiling Fans (Quality Control) Order",
    summary:
      "Defines air delivery, service value (air/watt) and safety for 600–1500 mm sweep ceiling fans. The 2019 revision links performance classes to energy-efficiency star labelling.",
    keywords: ["fan", "ceiling fan", "bldc fan", "पंखा"],
    sections: [
      { clause: "10", title: "Performance", summary: "Minimum air delivery and service value per sweep size." },
      { clause: "14", title: "Temperature rise", summary: "Winding temperature limits for class of insulation." },
      { clause: "18", title: "Marking", summary: "ISI, sweep, rated input and energy label information." },
    ],
    related: ["IS 302-2-80:2017"],
    editions: 6,
  },
  {
    code: "IS 13252-1:2010",
    title: "Information Technology Equipment — Safety — Part 1: General Requirements",
    category: "electronics",
    status: "current",
    mandatory: true,
    scheme: "Compulsory Registration Scheme (CRS)",
    qco: "Electronics & IT Goods (CRS) Order, 2012",
    summary:
      "Identical to IEC 60950-1. The backbone of CRS for laptops, adapters, printers, set-top boxes — electric shock, energy hazards, fire enclosure and insulation requirements.",
    keywords: ["laptop", "adapter", "charger", "it equipment", "printer", "crs", "लैपटॉप", "mobile charger"],
    sections: [
      { clause: "1.6", title: "Power interface", summary: "Input ratings and PS classification." },
      { clause: "2", title: "Protection from hazards", summary: "Electric shock, energy, mechanical and thermal hazards." },
      { clause: "4.7", title: "Resistance to fire", summary: "Enclosure flammability classes V-1/V-0 or HB alternatives." },
    ],
    related: ["IS 616:2017", "IS 16270:2023"],
    editions: 2,
  },
  {
    code: "IS 616:2017",
    title: "Audio, Video and Similar Electronic Apparatus — Safety Requirements",
    category: "electronics",
    status: "current",
    mandatory: true,
    scheme: "Compulsory Registration Scheme (CRS)",
    qco: "Electronics & IT Goods (CRS) Order, 2012",
    summary: "IEC 60065-based safety standard covering LED/LCD TVs and audio apparatus — insulation distances, fault conditions and mechanical strength.",
    keywords: ["television", "tv", "led tv", "audio", "speaker", "crs", "टीवी"],
    sections: [
      { clause: "7", title: "Fault conditions", summary: "Single-fault testing and fire safety verification." },
      { clause: "9", title: "Marking & instructions", summary: "Rating plate, CRS R-number and multilingual safety instructions." },
    ],
    related: ["IS 13252-1:2010"],
    editions: 3,
  },
  {
    code: "IS 16046:2018",
    title: "Secondary Cells and Batteries Containing Alkaline or other Non-Acid Electrolytes — Safety Requirements for Portable Sealed Secondary Cells",
    category: "electronics",
    status: "current",
    mandatory: true,
    scheme: "Compulsory Registration Scheme (CRS)",
    qco: "Electronics & IT Goods (CRS) Order, 2012",
    summary: "IEC 62133-aligned. Lithium-ion cells and battery packs — overcharge, short-circuit, crush, thermal abuse and vibration testing. Mandatory for mobile/consumer batteries sold under CRS.",
    keywords: ["battery", "lithium", "li-ion", "cell", "power bank", "crs", "बैटरी"],
    sections: [
      { clause: "7", title: "Safety requirements", summary: "Continuous charge, external short and thermal cycling." },
      { clause: "8", title: "Mechanical tests", summary: "Crush, impact, vibration and drop tests." },
    ],
    related: ["IS 16270:2023", "IS 13252-1:2010"],
    editions: 2,
  },
  {
    code: "IS 16102-1:2012",
    title: "Self-Ballasted LED Lamps for General Lighting Services — Part 1: Safety Requirements",
    category: "electronics",
    status: "current",
    mandatory: true,
    scheme: "Compulsory Registration Scheme (CRS)",
    qco: "Electronics & IT Goods (CRS) Order, 2012",
    summary: "Safety of retrofit LED lamps — interchangeability with lamp holders, protection against shock at the cap, insulation resistance and dielectric strength.",
    keywords: ["led bulb", "led lamp", "lighting", "crs", "बल्ब", "एलईडी"],
    sections: [
      { clause: "6", title: "Interchangeability", summary: "Gauging of B22d/E27 caps per IS 1554 dimensions." },
      { clause: "10", title: "Insulation & strength", summary: "Insulation resistance and HV withstand after humidity treatment." },
    ],
    related: ["IS 16102-2:2012", "IS 15885-2-13:2012"],
    editions: 1,
  },
  {
    code: "IS 1417:2016",
    title: "Gold and Gold Alloys, Jewellery/Artefacts — Fineness and Marking",
    category: "hallmark",
    status: "current",
    mandatory: true,
    scheme: "BIS Hallmarking Scheme",
    qco: "Hallmarking of Gold Jewellery (mandatory in notified districts)",
    summary:
      "The gold hallmarking standard. Recognizes six fineness grades (14K585, 18K750, 20K833, 22K916, 23K958, 24K999); every hallmarked article carries the BIS Standard Mark, fineness mark and a 6-digit HUID.",
    keywords: ["gold", "hallmark", "huid", "22k916", "18k750", "jewellery", "purity", "sona", "सोना", "आभूषण", "हॉलमार्क"],
    sections: [
      { clause: "3", title: "Fineness grades", summary: "585/750/833/916/958/999 parts per thousand gold content." },
      { clause: "4", title: "Assaying", summary: "Fire assay reference method for fineness determination." },
      { clause: "5", title: "Marking (HUID)", summary: "Standard Mark + fineness + six-digit alphanumeric hallmark unique ID." },
    ],
    related: ["IS 2112:2014", "IS 1418:2016"],
    editions: 3,
  },
  {
    code: "IS 2112:2014",
    title: "Silver and Silver Alloys, Jewellery/Artefacts — Fineness and Marking",
    category: "hallmark",
    status: "current",
    mandatory: false,
    scheme: "BIS Hallmarking Scheme (voluntary for silver)",
    qco: null,
    summary: "Fineness grades 999, 990, 925 (sterling), 900, 835 and 800 for silver articles with analogous hallmarking to gold.",
    keywords: ["silver", "chandi", "hallmark", "sterling", "925", "चांदी"],
    sections: [
      { clause: "3", title: "Grades", summary: "800–999 fineness series." },
      { clause: "5", title: "Marking", summary: "Standard Mark, fineness and HUID for hallmarked articles." },
    ],
    related: ["IS 1417:2016"],
    editions: 2,
  },
  {
    code: "IS 14543:2016",
    title: "Packaged Drinking Water (Other than Packaged Natural Mineral Water) — Specification",
    category: "food",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "FSSAI-linked mandatory BIS certification",
    summary:
      "Every bottle of packaged drinking water must be produced in a BIS-licensed plant. Specifies treatment, microbiological limits, packaging materials and the required labelling declarations.",
    keywords: ["packaged water", "water bottle", "drinking water", "पानी", "पेयजल"],
    sections: [
      { clause: "4", title: "Treatment", summary: "Decantation, filtration, disinfection and optional remineralization." },
      { clause: "6", title: "Microbiological requirements", summary: "E. coli, coliform and pathogen absence criteria." },
      { clause: "8", title: "Marking", summary: "ISI mark, 'packaged drinking water' legend and batch details." },
    ],
    related: ["IS 13428:2005", "IS 10500:2012"],
    editions: 2,
  },
  {
    code: "IS 10500:2012",
    title: "Drinking Water — Specification",
    category: "food",
    status: "current",
    mandatory: false,
    scheme: "Specification (reference for water quality)",
    qco: null,
    summary: "Acceptable and permissible limits for ~60 drinking-water parameters (arsenic 0.01 mg/L, nitrate 45 mg/L etc.) used by utilities, labs and courts as the national benchmark.",
    keywords: ["drinking water", "water quality", "jal", "पानी", "पेयजल"],
    sections: [
      { clause: "4", title: "Requirements", summary: "Organoleptic, physical, chemical and bacteriological limits." },
      { clause: "Table 2", title: "Toxic substances", summary: "Arsenic, lead, mercury, chromium limits." },
    ],
    related: ["IS 14543:2016", "IS 1622:1981"],
    editions: 2,
  },
  {
    code: "IS 4984:2016",
    title: "High Density Polyethylene Pipes for Water Supply — Specification",
    category: "plastics",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Polyethylene Pipes (Quality Control) Order",
    summary: "PE 63/80/100 grades, PN 2.5–16 pressure classes for potable water — carbon black content, oxidation induction time and hydraulic pressure tests.",
    keywords: ["hdpe", "pipe", "pe100", "water supply", "पाइप"],
    sections: [
      { clause: "7", title: "Material", summary: "PE grade designation and carbon black dispersion." },
      { clause: "12", title: "Hydrostatic tests", summary: "Proof-creep and pressure test acceptance." },
    ],
    related: ["IS 4985:2021", "IS 12235-8:2004"],
    editions: 5,
  },
  {
    code: "IS 4985:2021",
    title: "Unplasticized PVC Pipes for Potable Water Supplies — Specification",
    category: "plastics",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "PVC Pipes (Quality Control) Order",
    summary: "uPVC pressure pipes for drinking water — opacity, vinyl chloride monomer content limits, and full dimensional/pressure performance tables.",
    keywords: ["upvc", "pvc pipe", "pipe", "पाइप"],
    sections: [
      { clause: "6", title: "Material safety", summary: "VCM residual limit and opacity for potable use." },
      { clause: "10", title: "Dimensions & tests", summary: "Pressure classes and acceptance testing." },
    ],
    related: ["IS 4984:2016"],
    editions: 5,
  },
  {
    code: "IS 4151:2015",
    title: "Protective Helmets for Motorcycle Riders — Specification",
    category: "mechanical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Protective Helmets for Two Wheeler Riders (Quality Control) Order",
    summary: "Mandatory for every helmet sold in India — shell construction, retention system, impact absorption, penetration and peripheral vision requirements.",
    keywords: ["helmet", "rider", "two wheeler", "हेलमेट"],
    sections: [
      { clause: "6", title: "Construction", summary: "Shell, comfort padding, visor and chin-strap requirements." },
      { clause: "8", title: "Impact test", summary: "Drop tests on flat/kerbstone anvils with acceleration limits." },
      { clause: "11", title: "Marking", summary: "Permanent ISI marking inside the shell." },
    ],
    related: ["IS 2925:1984"],
    editions: 4,
  },
  {
    code: "IS 2347:2017",
    title: "Domestic Pressure Cookers — Specification",
    category: "consumer",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Pressure Cooker (Quality Control) Order",
    summary: "Aluminium/stainless steel pressure cookers — minimum thickness, safety valve, fusible plug, bursting pressure and handle-strength tests to prevent kitchen accidents.",
    keywords: ["pressure cooker", "cooker", "कुकर"],
    sections: [
      { clause: "5", title: "Materials", summary: "Body metal thickness per capacity." },
      { clause: "9", title: "Safety devices", summary: "Steam vent, safety valve and fusible plug performance." },
      { clause: "12", title: "Bursting test", summary: "Minimum bursting pressure multiples of working pressure." },
    ],
    related: ["IS 302-2-15:2009"],
    editions: 7,
  },
  {
    code: "IS 9873-1:2019",
    title: "Safety of Toys — Part 1: Safety Aspects Related to Mechanical and Physical Properties",
    category: "consumer",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Toys (Quality Control) Order, 2020",
    summary: "ISO 8124-1 aligned. Small-part hazards, sharp edges/points, projectile energy and age-labelling — mandatory for all toys sold in India.",
    keywords: ["toys", "toy safety", "खिलौना", "children"],
    sections: [
      { clause: "4", title: "Normal use", summary: "Structure, small parts and cords for different age groups." },
      { clause: "5", title: "Test methods", summary: "Tension, torque, drop and impact misuse tests." },
    ],
    related: ["IS 9873-2:2017", "IS 9873-3:2017", "IS 15644:2006"],
    editions: 4,
  },
  {
    code: "IS 9873-3:2017",
    title: "Safety of Toys — Part 3: Migration of Certain Elements",
    category: "consumer",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Toys (Quality Control) Order, 2020",
    summary: "Limits migration of eight heavy metals (Sb, As, Ba, Cd, Cr, Pb, Hg, Se) from toy materials — the key chemical safety clause for painted/plastic toys.",
    keywords: ["toys", "lead paint", "migration", "खिलौना"],
    sections: [
      { clause: "4", title: "Migration limits", summary: "Element-wise limits by toy material category." },
    ],
    related: ["IS 9873-1:2019", "IS 9873-2:2017"],
    editions: 2,
  },
  {
    code: "IS 3196:2013",
    title: "Welded Low Carbon Steel Cylinders Exceeding 5 Litre Water Capacity for Low Pressure Liquefiable Gases",
    category: "mechanical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Gas Cylinders (Quality Control) Order",
    summary: "The domestic LPG cylinder standard — body steel, weld quality, tare weight, and periodic re-testing regime enforced with PESO rules.",
    keywords: ["lpg", "cylinder", "gas cylinder", "सिलिंडर"],
    sections: [
      { clause: "7", title: "Design & manufacture", summary: "Shell thickness, circumferential weld and valve boss." },
      { clause: "11", title: "Tests", summary: "Hydrostatic, burst, and radiographic examination of welds." },
    ],
    related: ["IS 4246:2002", "IS 8737:2017"],
    editions: 4,
  },
  {
    code: "IS 4246:2002",
    title: "Domestic Gas Stoves for Use with Liquefied Petroleum Gases — Specification",
    category: "mechanical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Domestic Gas Stoves (Quality Control) Order",
    summary: "LPG stoves — burner construction, gas consumption, flame stability, ignition safety and thermal efficiency (≥68%) requirements.",
    keywords: ["gas stove", "lpg stove", "burner", "स्टोव"],
    sections: [
      { clause: "8", title: "Thermal efficiency", summary: "Minimum efficiency at rated heat input." },
      { clause: "10", title: "Safety", summary: "Flame failure, back-fire and formation of soot limits." },
    ],
    related: ["IS 3196:2013", "IS 5116:1996"],
    editions: 5,
  },
  {
    code: "IS/IEC 60898-1:2002",
    title: "Circuit-Breakers for Overcurrent Protection for Household and Similar Installations — Part 1: Circuit-breakers for AC Operation",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Low Voltage Switchgear and Controlgear (Quality Control) Order",
    summary: "The MCB standard — B/C/D trip curves, 10 kA breaking capacity classes, endurance and short-circuit tests for panels in every building.",
    keywords: ["mcb", "circuit breaker", "switchgear", "ब्रेकर"],
    sections: [
      { clause: "8", title: "Characteristics", summary: "Instantaneous trip ranges B/C/D curves." },
      { clause: "9", title: "Tests", summary: "Short-circuit, endurance and dielectric verification." },
    ],
    related: ["IS 12640-1:2016"],
    editions: 2,
  },
  {
    code: "IS 12640-1:2016",
    title: "Residual Current Operated Circuit-Breakers for Household and Similar Uses — Part 1: Circuit-Breakers Without Integral Overcurrent Protection (RCCBs)",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Low Voltage Switchgear and Controlgear (Quality Control) Order",
    summary: "RCCB/ELCB protection against earth leakage — 30/100/300 mA sensitivity classes for shock and fire protection.",
    keywords: ["rccb", "elcb", "earth leakage", "rcd", "ब्रेकर"],
    sections: [
      { clause: "5", title: "Classification", summary: "AC/A type residual current devices." },
      { clause: "9", title: "Operating characteristics", summary: "Trip time-current requirements per sensitivity." },
    ],
    related: ["IS/IEC 60898-1:2002"],
    editions: 2,
  },
  {
    code: "IS 13779:1999",
    title: "AC Static Watt-Hour Meters, Class 1 and 2 — Specification",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Energy Meters (Quality Control) Order",
    summary: "Static energy meters for utilities — accuracy classes, tamper detection features and electromagnetic compatibility.",
    keywords: ["energy meter", "electricity meter", "मीटर"],
    sections: [
      { clause: "9", title: "Accuracy", summary: "Limits of error for class 1 and class 2 meters." },
      { clause: "12", title: "Tamper features", summary: "Events logging and anti-tamper design requirements." },
    ],
    related: ["IS 16444:2015"],
    editions: 2,
  },
  {
    code: "IS 16444:2015",
    title: "AC Static Direct Connected Watt Hour Smart Meter Class 1 and 2 — Specification",
    category: "electrical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Smart Energy Meters (Quality Control) Order",
    summary: "India's smart meter standard behind the national AMI rollout — connect/disconnect, tamper events, load survey and interoperability profiles with DLMS/COSEM.",
    keywords: ["smart meter", "ami", "energy meter", "मीटर"],
    sections: [
      { clause: "6", title: "Functional requirements", summary: "Metrology, communication and remote connect/disconnect." },
      { clause: "9", title: "Interoperability", summary: "Companion specification with communication profiles." },
    ],
    related: ["IS 13779:1999", "IS 15959-2:2016"],
    editions: 2,
  },
  {
    code: "IS 15683:2018",
    title: "Portable Fire Extinguishers — Performance and Construction — Specification",
    category: "mechanical",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Fire Extinguishers (Quality Control) Order",
    summary: "Water/foam/powder/CO2 extinguishers — discharge time, throw, fire-rating (21A/183B etc.) demonstration and ISI colour-coding of extinguisher types.",
    keywords: ["fire extinguisher", "fire safety", "अग्निशामक"],
    sections: [
      { clause: "8", title: "Fire rating", summary: "Class A/B construction rating demonstration on test fires." },
      { clause: "10", title: "Marking", summary: "Type colour band, capacity, ISI and CM/L number." },
    ],
    related: ["IS 2190:2010"],
    editions: 2,
  },
  {
    code: "IS 303:2012",
    title: "Plywood for General Purposes — Specification",
    category: "construction",
    status: "current",
    mandatory: true,
    scheme: "ISI Mark (Scheme-I)",
    qco: "Wood Based Boards (Quality Control) Order",
    summary: "MR/BWR/BWP grade plywood — veneer quality, bonding strength, glue shear and mycological treatment requirements for furniture-grade boards.",
    keywords: ["plywood", "bwr", "marine ply", "board", "प्लाईवुड"],
    sections: [
      { clause: "6", title: "Grades & veneer classes", summary: "MR, BWR (Type 503) and BWP constructions." },
      { clause: "10", title: "Glue shear strength", summary: "Dry/wet/mycological shear tests per grade." },
    ],
    related: ["IS 710:2010", "IS 1659:2004"],
    editions: 7,
  },
  {
    code: "IS 9473:2002",
    title: "Filtering Half Masks to Protect Against Particles — Specification",
    category: "consumer",
    status: "current",
    mandatory: false,
    scheme: "Voluntary (ISI)",
    qco: null,
    summary: "FFP1/FFP2/FFP3 respirators — penetration, breathing resistance and clogging tests; the Indian basis for 'N95-type' claims.",
    keywords: ["mask", "n95", "respirator", "ffp2", "मास्क"],
    sections: [
      { clause: "7", title: "Classification", summary: "FFP1/FFP2/FFP3 filtration efficiency classes." },
      { clause: "8", title: "Tests", summary: "Paraffin-oil/NaCl penetration and breathing resistance." },
    ],
    related: ["IS 9623:1980"],
    editions: 2,
  },
  {
    code: "IS 1165:2022",
    title: "Milk Powder — Specification",
    category: "food",
    status: "current",
    mandatory: false,
    scheme: "Voluntary (ISI)",
    qco: null,
    summary: "Whole/skimmed/partly skimmed milk powders — moisture, fat, acidity, scorched particles and microbiological limits; often adopted in FSSAI enforcement sampling.",
    keywords: ["milk powder", "dairy", "दूध"],
    sections: [
      { clause: "4", title: "Types & grades", summary: "Whole, partly skimmed, skimmed; standard/extra grade." },
      { clause: "6", title: "Microbiology", summary: "Coliform, Salmonella absence criteria." },
    ],
    related: ["IS 13334-1:2014"],
    editions: 5,
  },
];

/* ------------------------------ KNOWLEDGE ------------------------------ */

const DOCS = [
  {
    slug: "concept-what-is-bis",
    kind: "concept",
    title: "BIS — India's National Standards Body (BIS Act, 2016)",
    body: "The Bureau of Indian Standards is the National Standards Body of India, functioning under the Ministry of Consumer Affairs, Food & Public Distribution. It formulates Indian Standards through technical committees, operates product certification and hallmarking schemes, recognizes laboratories and enforces against misuse of the Standard Mark under the BIS Act, 2016.",
    bodyHi: "भारतीय मानक ब्यूरो भारत का राष्ट्रीय मानक निकाय है, जो उपभोक्ता मामले, खाद्य एवं सार्वजनिक वितरण मंत्रालय के अधीन कार्य करता है। यह तकनीकी समितियों द्वारा भारतीय मानक तैयार करता है, उत्पाद प्रमाणन व हॉलमार्किंग योजनाएँ चलाता है, प्रयोगशालाओं को मान्यता देता है तथा BIS अधिनियम, 2016 के अंतर्गत मानक चिह्न के दुरुपयोग के विरुद्ध कार्रवाई करता है।",
    keywords: ["bis", "bureau", "what is bis", "about", "ब्यूरो"],
    refs: [],
  },
  {
    slug: "scheme-isi",
    kind: "scheme",
    title: "Scheme-I — ISI Mark Product Certification",
    body: "BIS grants a licence to manufacturers whose product conforms to the applicable Indian Standard. Assessment includes factory inspection of raw materials, manufacturing process and in-house quality control, plus independent testing of drawn samples. The licensee may apply the ISI Standard Mark with the unique CM/L licence number. Certification is mandatory where a Quality Control Order applies; otherwise voluntary.",
    bodyHi: "योजना-I में BIS उन निर्माताओं को लाइसेंस देता है जिनका उत्पाद लागू भारतीय मानक के अनुरूप हो। मूल्यांकन में कारखाना निरीक्षण, गुणवत्ता-नियंत्रण व्यवस्था व स्वतंत्र नमूना परीक्षण शामिल है। लाइसेंस धारक अद्वितीय CM/L संख्या सहित ISI मानक चिह्न लगा सकता है। QCO लागू होने पर प्रमाणन अनिवार्य, अन्यथा स्वैच्छिक।",
    keywords: ["isi", "scheme", "certification", "licence", "mark", "आईएसआई"],
    refs: [],
  },
  {
    slug: "scheme-crs",
    kind: "scheme",
    title: "Scheme-II — Compulsory Registration Scheme (Electronics & IT)",
    body: "Under the Electronics and Information Technology Goods (Requirements of Compulsory Registration) Order, 2012, notified electronics must be tested at BIS-recognized labs and registered online. Registered products display the Standard Mark and a registration number of the form R-XXXXXXXX. No factory audit; registration is based on test reports and brand/model declarations, with post-registration surveillance.",
    bodyHi: "इलेक्ट्रॉनिक्स एवं सूचना प्रौद्योगिकी वस्तु (अनिवार्य पंजीकरण) आदेश, 2012 के अंतर्गत अधिसूचित इलेक्ट्रॉनिक्स को BIS-मान्यता प्राप्त प्रयोगशालाओं में परीक्षित कराकर ऑनलाइन पंजीकृत करना होता है। पंजीकृत उत्पादों पर मानक चिह्न और R-XXXXXXXX प्रारूप की पंजीकरण संख्या अंकित होती है। फैक्ट्री ऑडिट नहीं; पंजीकरण टेस्ट रिपोर्ट व ब्रांड/मॉडल घोषणा पर आधारित है।",
    keywords: ["crs", "registration", "electronics", "it goods", "r-number", "सीआरएस"],
    refs: [],
  },
  {
    slug: "scheme-coc-x",
    kind: "scheme",
    title: "Scheme-IV — Certificate of Conformity",
    body: "Grant of Certificate of Conformity for lots/batches or continuous production assessed against an Indian Standard through testing and inspection. Often used where product design needs type-approval style conformity; newer machinery and low-voltage safety regulations adopt this certification approach.",
    bodyHi: "योजना-IV में किसी भारतीय मानक के विरुद्ध परीक्षण व निरीक्षण के आधार पर लॉट/बैच या सतत उत्पादन हेतु अनुरूपता प्रमाणपत्र प्रदान किया जाता है। नई मशीनरी व लो-वोल्टेज सुरक्षा विनियम इसी दृष्टिकोण को अपनाते हैं।",
    keywords: ["certificate of conformity", "scheme iv", "coc", "scheme x"],
    refs: [],
  },
  {
    slug: "scheme-fmcs",
    kind: "scheme",
    title: "FMCS — Foreign Manufacturers Certification Scheme",
    body: "Overseas manufacturers obtain a BIS licence to use the ISI mark on products imported into India. The applicant nominates an Authorized Indian Representative; BIS conducts a foreign factory audit and independent sample testing. Licence obligations mirror Scheme-I including surveillance visits.",
    bodyHi: "विदेशी निर्माता भारत में आयातित उत्पादों पर ISI चिह्न हेतु BIS लाइसेंस प्राप्त करते हैं। आवेदक अधिकृत भारतीय प्रतिनिधि नामित करता है; BIS विदेशी फैक्ट्री ऑडिट व स्वतंत्र नमूना परीक्षण करता है। लाइसेंस दायित्व योजना-I के समान, निगरानी सहित।",
    keywords: ["fmcs", "foreign", "import", "overseas"],
    refs: [],
  },
  {
    slug: "hallmark-guide",
    kind: "hallmark",
    title: "Hallmarking of Gold & Silver Jewellery — Complete Guide",
    body: "Sale of gold jewellery/artefacts with BIS hallmark is mandatory in notified districts. A hallmark has three parts: (1) BIS Standard Mark, (2) fineness/purity as per IS 1417 — 14K585, 18K750, 20K833, 22K916, 23K958, 24K999, and (3) a six-digit alphanumeric HUID. Jewellers register with BIS; assaying & hallmarking is performed only at BIS-recognized Assaying and Hallmarking Centres. Silver hallmarking under IS 2112 is voluntary. Consumers can verify HUID in the BIS Care App.",
    bodyHi: "अधिसूचित जिलों में BIS हॉलमार्क सहित स्वर्ण आभूषण/वस्तुओं की बिक्री अनिवार्य है। हॉलमार्क के तीन भाग: (1) BIS मानक चिह्न, (2) IS 1417 अनुसार शुद्धता — 14K585, 18K750, 20K833, 22K916, 23K958, 24K999, तथा (3) छह-अंकों का अल्फ़ान्यूमेरिक HUID। जॉइलर्स BIS में पंजीकृत होते हैं; एस्सेइंग व हॉलमार्किंग केवल BIS-मान्यता प्राप्त AHC पर होती है। IS 2112 के अंतर्गत चांदी की हॉलमार्किंग स्वैच्छिक है। उपभोक्ता BIS Care ऐप में HUID सत्यापित कर सकते हैं।",
    keywords: ["hallmark", "gold", "huid", "purity", "ahc", "jeweller", "हॉलमार्क", "सोना"],
    refs: [],
  },
  {
    slug: "process-isi-steps",
    kind: "process",
    title: "ISI Licensing Process — Step by Step (Domestic Manufacturers)",
    body: "1. Identify applicable Indian Standard and QCO status. 2. Establish manufacturing and testing infrastructure (in-house or tied-up recognized lab). 3. Apply on the BIS portal with documents and fee. 4. Factory audit by BIS officers. 5. Independent testing of sealed samples at BIS/recognized laboratories. 6. Grant of licence with CM/L number. 7. Surveillance through periodic inspections and market/factory sampling; renewals typically 1–5 years. Typical end-to-end timeline: 30–90 days.",
    bodyHi: "1. लागू भारतीय मानक व QCO स्थिति पहचानें। 2. निर्माण व परीक्षण ढाँचा तैयार करें (इन-हाउस या मान्यता प्राप्त प्रयोगशाला)। 3. BIS पोर्टल पर दस्तावेज़ व शुल्क सहित आवेदन करें। 4. BIS अधिकारियों द्वारा फैक्ट्री ऑडिट। 5. सील नमूनों का स्वतंत्र परीक्षण। 6. CM/L संख्या सहित लाइसेंस प्रदान। 7. आवधिक निरीक्षण व नमूनाकरण द्वारा निगरानी; नवीनीकरण सामान्यतः 1–5 वर्ष। सामान्य समय: 30–90 दिन।",
    keywords: ["process", "apply", "licence", "steps", "factory", "प्रक्रिया", "लाइसेंस"],
    refs: [],
  },
  {
    slug: "fees-concessions",
    kind: "fees",
    title: "Certification Fees & Concessions Overview",
    body: "Costs comprise application fee, factory audit charges (per man-day), sample testing charges (actuals, product-specific), annual licence fee and unit marking fee. BIS provides concessions up to 80% on certification/marking fees for micro units and recognized startups, ~50% for small-scale units, with additional relief for women entrepreneurs and North-Eastern units. Hallmarking involves jeweller registration fee plus per-article AHC charges; CRS involves registration fee plus lab testing cost per model.",
    bodyHi: "लागत में आवेदन शुल्क, फैक्ट्री ऑडिट शुल्क (प्रति मैन-डे), नमूना परीक्षण शुल्क (वास्तविक), वार्षिक लाइसेंस शुल्क व यूनिट मार्किंग शुल्क शामिल हैं। सूक्ष्म इकाइयों व मान्यता प्राप्त स्टार्टअप को प्रमाणन/मार्किंग शुल्क पर 80% तक, लघु इकाइयों को ~50% छूट, महिला उद्यमियों व पूर्वोत्तर इकाइयों को अतिरिक्त राहत। हॉलमार्किंग में जॉइलर पंजीकरण शुल्क + प्रति-वस्तु AHC शुल्क; CRS में पंजीकरण शुल्क + प्रति मॉडल परीक्षण लागत।",
    keywords: ["fee", "cost", "concession", "msme", "startup", "शुल्क"],
    refs: [],
  },
  {
    slug: "consumer-verify",
    kind: "consumer",
    title: "Verify Marks & Licences — Consumer Guide",
    body: "Use the BIS Care App to verify: ISI licence numbers (CM/L-...), CRS registration numbers (R-...), jeweller registrations, and gold HUID codes. This app's Consumer Corner offers the same lookup against the demonstration registry plus a complaint flow. Officials also accept complaints via the National Consumer Helpline 1915.",
    bodyHi: "BIS Care ऐप से सत्यापित करें: ISI लाइसेंस (CM/L-...), CRS पंजीकरण (R-...), जॉइलर पंजीकरण व गोल्ड HUID कोड। इस ऐप का उपभोक्ता कॉर्नर भी प्रदर्शन-रजिस्ट्री से समान जाँच व शिकायत प्रवाह प्रदान करता है। राष्ट्रीय उपभोक्ता हेल्पलाइन 1915 पर भी शिकायत संभव।",
    keywords: ["verify", "check", "care app", "licence number", "जाँच"],
    refs: [],
  },
  {
    slug: "consumer-complaints",
    kind: "consumer",
    title: "Complaints & Enforcement — BIS Act, 2016",
    body: "Selling QCO products without certification, counterfeiting the Standard Mark, or misusing a licence is punishable under the BIS Act, 2016 with fines up to ₹5 lakh and/or imprisonment. Consumers can file grievances via the BIS Care App, the National Consumer Helpline (1915), or on the BIS portal. BIS also conducts market surveillance and recalls.",
    bodyHi: "QCO उत्पादों को बिना प्रमाणन बेचना, मानक चिह्न की नकल या लाइसेंस का दुरुपयोग BIS अधिनियम, 2016 में ₹5 लाख तक जुर्माने और/या कारावास से दंडनीय है। उपभोक्ता BIS Care ऐप, राष्ट्रीय उपभोक्ता हेल्पलाइन (1915) या BIS पोर्टल पर शिकायत कर सकते हैं। BIS बाज़ार निगरानी व रिकॉल भी करता है।",
    keywords: ["complaint", "fake", "misuse", "penalty", "1915", "शिकायत"],
    refs: [],
  },
  {
    slug: "labs-recognition",
    kind: "labs",
    title: "Laboratory Recognition & Network",
    body: "BIS maintains its own laboratories (Central, Northern, Eastern, Western, Southern regions) and recognizes outside laboratories whose facilities it assesses as competent to test specific standards. For hallmarking, Assaying & Hallmarking Centres (AHCs) are recognized to test fineness and apply hallmarks. Manufacturers may use recognized labs for routine testing; scheme-designated samples are tested at BIS labs.",
    bodyHi: "BIS की स्वयं की प्रयोगशालाएँ (केंद्रीय, उत्तर, पूर्व, पश्चिम, दक्खिण क्षेत्र) हैं और यह बाहरी प्रयोगशालाओं को भी विशिष्ट मानकों के परीक्षण हेतु मान्यता देता है। हॉलमार्किंग हेतु AHC मान्यता प्राप्त होते हैं। निर्माता दिनचर्या परीक्षण हेतु मान्यता प्राप्त लैब उपयोग कर सकते हैं; योजना-नामित नमूने BIS लैब में परीक्षित होते हैं।",
    keywords: ["lab", "laboratory", "recognition", "testing", "ahc", "प्रयोगशाला"],
    refs: [],
  },
  {
    slug: "concept-qco",
    kind: "concept",
    title: "Quality Control Orders (QCOs) Explained",
    body: "QCOs are notifications under the BIS Act, 2016 by line ministries that make conformity to a specified Indian Standard mandatory for manufacture, import, sale or distribution of a product. Examples: helmets, domestic pressure cookers, toys, PVC cables, steel products, gold hallmarking. Selling non-conforming products attracts enforcement action.",
    bodyHi: "QCO, BIS अधिनियम, 2016 के अंतर्गत संबंधित मंत्रालयों की अधिसूचनाएँ हैं जो किसी उत्पाद के निर्माण, आयात, विक्रय या वितरण हेतु निर्दिष्ट भारतीय मानक के अनुरूप होना अनिवार्य करती हैं। उदाहरण: हेलमेट, प्रेशर कुकर, खिलौने, PVC केबल, इस्पात उत्पाद, गोल्ड हॉलमार्किंग। गैर-अनुरूप उत्पादों की बिक्री पर प्रवर्तन कार्रवाई होती है।",
    keywords: ["qco", "quality control order", "mandatory", "अनिवार्य"],
    refs: [],
  },
  {
    slug: "faq-licence-validity",
    kind: "faq",
    title: "FAQ — Licence Validity, Marking & Surveillance",
    body: "Initial ISI licences are generally granted for 1–2 years and renewed for longer spans based on performance. The Standard Mark must show the applicable standard number and CM/L licence number. BIS surveillance includes factory inspections and market/factory sample testing; failure can suspend or cancel the licence.",
    bodyHi: "प्रारंभिक ISI लाइसेंस सामान्यतः 1–2 वर्ष हेतु होते हैं और प्रदर्शन के आधार पर अधिक अवधि में नवीनीकृत होते हैं। मानक चिह्न पर लागू मानक संख्या व CM/L लाइसेंस संख्या अंकित होनी चाहिए। BIS निगरानी में फैक्ट्री निरीक्षण व बाज़ार/फैक्ट्री नमूना परीक्षण शामिल; विफलता पर लाइसेंस निलंबित/रद्द हो सकता है।",
    keywords: ["validity", "renewal", "surveillance", "faq"],
    refs: [],
  },
];

/* --------------------------------- LABS --------------------------------- */

const LABS = [
  { name: "BIS Central Laboratory", city: "Ghaziabad (Sahibabad)", state: "Uttar Pradesh", kind: "BIS Laboratory", capabilities: ["electrical", "construction", "mechanical", "food", "consumer", "plastics"], standards: ["IS 456:2000", "IS 694:2010", "IS 2347:2017", "IS 374:2019"], phone: "0120-4642000", email: "clab@bis.gov.in" },
  { name: "BIS Northern Regional Laboratory", city: "New Delhi", state: "Delhi", kind: "BIS Laboratory", capabilities: ["electrical", "mechanical", "consumer"], standards: ["IS 1293:2019", "IS/IEC 60898-1:2002", "IS 4151:2015"], phone: "011-2323-0000", email: "nrol@bis.gov.in" },
  { name: "BIS Western Regional Laboratory", city: "Mumbai", state: "Maharashtra", kind: "BIS Laboratory", capabilities: ["construction", "plastics", "mechanical", "electrical"], standards: ["IS 4984:2016", "IS 1786:2008", "IS 15683:2018"], phone: "022-2832-0000", email: "wro@bis.gov.in" },
  { name: "BIS Southern Regional Laboratory", city: "Chennai", state: "Tamil Nadu", kind: "BIS Laboratory", capabilities: ["food", "electrical", "consumer", "construction"], standards: ["IS 14543:2016", "IS 1165:2022", "IS 694:2010"], phone: "044-2254-0000", email: "sro@bis.gov.in" },
  { name: "BIS Eastern Regional Laboratory", city: "Kolkata", state: "West Bengal", kind: "BIS Laboratory", capabilities: ["construction", "mechanical", "food"], standards: ["IS 269:2015", "IS 1786:2008", "IS 303:2012"], phone: "033-2486-0000", email: "ero@bis.gov.in" },
  { name: "National Test House (NR)", city: "Ghaziabad", state: "Uttar Pradesh", kind: "Recognized Laboratory", capabilities: ["construction", "electrical", "mechanical", "plastics", "hallmark"], standards: ["IS 456:2000", "IS 1786:2008", "IS 2062:2011"], phone: "0120-278-9000", email: "nth-nr@gov.in" },
  { name: "National Test House (WR)", city: "Mumbai", state: "Maharashtra", kind: "Recognized Laboratory", capabilities: ["consumer", "mechanical", "electrical"], standards: ["IS 2347:2017", "IS 4246:2002", "IS 3196:2013"], phone: "022-2579-0000", email: "nth-wr@gov.in" },
  { name: "Shriram Institute for Industrial Research", city: "New Delhi", state: "Delhi", kind: "Recognized Laboratory", capabilities: ["food", "plastics", "consumer", "electrical"], standards: ["IS 10500:2012", "IS 14543:2016", "IS 9873-3:2017"], phone: "011-2760-0000", email: "labs@shriraminstitute.org" },
  { name: "Electronic Regional Test Laboratory (ERTL North)", city: "New Delhi", state: "Delhi", kind: "Recognized Laboratory", capabilities: ["electronics", "electrical"], standards: ["IS 13252-1:2010", "IS 616:2017", "IS 16046:2018"], phone: "011-2696-0000", email: "ertln@stpi.in" },
  { name: "ERTL (West)", city: "Mumbai", state: "Maharashtra", kind: "Recognized Laboratory", capabilities: ["electronics"], standards: ["IS 13252-1:2010", "IS 16102-1:2012", "IS 16046:2018"], phone: "022-2757-0000", email: "ertlw@stpi.in" },
  { name: "ETDC (STQC) Bengaluru", city: "Bengaluru", state: "Karnataka", kind: "Recognized Laboratory", capabilities: ["electronics", "electrical"], standards: ["IS 13252-1:2010", "IS 16444:2015", "IS 13779:1999"], phone: "080-2509-0000", email: "etdc.blr@stqc.gov.in" },
  { name: "Vinta Labs", city: "Noida", state: "Uttar Pradesh", kind: "Recognized Laboratory", capabilities: ["electronics", "consumer"], standards: ["IS 16046:2018", "IS 16333-3:2022", "IS 616:2017"], phone: "0120-433-0000", email: "support@vinta.in" },
  { name: "URS Products & Testing", city: "Faridabad", state: "Haryana", kind: "Recognized Laboratory", capabilities: ["electrical", "consumer", "mechanical"], standards: ["IS 694:2010", "IS 3854:1997", "IS 4151:2015"], phone: "0129-400-0000", email: "info@urstestinglab.com" },
  { name: "Spectro Analytical Labs", city: "New Delhi", state: "Delhi", kind: "Recognized Laboratory", capabilities: ["construction", "food", "plastics"], standards: ["IS 269:2015", "IS 1165:2022", "IS 4985:2021"], phone: "011-4552-0000", email: "care@spectro.in" },
  { name: "Sigma Test & Research Centre", city: "New Delhi", state: "Delhi", kind: "Recognized Laboratory", capabilities: ["electrical", "consumer", "electronics"], standards: ["IS 1293:2019", "IS 9473:2002", "IS 13252-1:2010"], phone: "011-4940-0000", email: "info@sigmatest.org" },
  { name: "Labs India (TUV)", city: "Gurugram", state: "Haryana", kind: "Recognized Laboratory", capabilities: ["construction", "mechanical", "electrical"], standards: ["IS 1786:2008", "IS 2062:2011", "IS 15683:2018"], phone: "0124-436-0000", email: "labs.india@tuv.com" },
  { name: "Advance Testing & Calibration", city: "Pune", state: "Maharashtra", kind: "Recognized Laboratory", capabilities: ["electrical", "mechanical"], standards: ["IS 374:2019", "IS/IEC 60898-1:2002", "IS 12640-1:2016"], phone: "020-6740-0000", email: "atc.pune@labmail.in" },
  { name: "Kundun Hallmark AHC", city: "Jaipur", state: "Rajasthan", kind: "AHC", capabilities: ["hallmark"], standards: ["IS 1417:2016", "IS 2112:2014"], phone: "0141-402-0000", email: "kundun.ahc@hallmark.in" },
  { name: "TrueTest Assaying & Hallmarking Centre", city: "Ahmedabad", state: "Gujarat", kind: "AHC", capabilities: ["hallmark"], standards: ["IS 1417:2016", "IS 2112:2014"], phone: "079-2640-0000", email: "truetest@ahc.in" },
  { name: "Siddharth Refinery & AHC", city: "Mumbai (Zaveri Bazaar)", state: "Maharashtra", kind: "AHC", capabilities: ["hallmark"], standards: ["IS 1417:2016"], phone: "022-6180-0000", email: "support@siddharthahc.in" },
  { name: "Gem & Jewellery Testing AHC", city: "Surat", state: "Gujarat", kind: "AHC", capabilities: ["hallmark"], standards: ["IS 1417:2016", "IS 2112:2014"], phone: "0261-246-0000", email: "gj.ahc@surat.in" },
  { name: "Southern Assay House AHC", city: "Chennai", state: "Tamil Nadu", kind: "AHC", capabilities: ["hallmark"], standards: ["IS 1417:2016"], phone: "044-2815-0000", email: "sa.ahc@chennai.in" },
  { name: "Rajkot Metal & Metallurgical Lab", city: "Rajkot", state: "Gujarat", kind: "Recognized Laboratory", capabilities: ["construction", "mechanical"], standards: ["IS 1786:2008", "IS 1239-1:2004", "IS 2062:2011"], phone: "0281-236-0000", email: "rml@rajkot.in" },
  { name: "Sara Electricals Test Lab", city: "Ludhiana", state: "Punjab", kind: "Recognized Laboratory", capabilities: ["electrical", "consumer"], standards: ["IS 694:2010", "IS 1293:2019", "IS 3854:1997"], phone: "0161-267-0000", email: "sara@ludhiana.in" },
];

/* ------------------------------- LICENCES ------------------------------- */

const LICENCES = [
  { markNo: "CM/L-7200045182", type: "isi", holder: "Shree Cement Ltd", product: "Ordinary Portland Cement 43 Grade", standardCode: "IS 269:2015", status: "valid", issuedOn: "2024-02-11", validTill: "2026-02-10", city: "Beawar, Rajasthan" },
  { markNo: "CM/L-7600112290", type: "isi", holder: "JSW Steel Ltd", product: "HSD Bars Fe 500D for concrete reinforcement", standardCode: "IS 1786:2008", status: "valid", issuedOn: "2023-06-19", validTill: "2026-06-18", city: "Vijayanagar, Karnataka" },
  { markNo: "CM/L-8400033177", type: "isi", holder: "Polycab India Ltd", product: "PVC insulated FR cables 1100 V", standardCode: "IS 694:2010", status: "valid", issuedOn: "2024-09-02", validTill: "2027-09-01", city: "Halol, Gujarat" },
  { markNo: "CM/L-4100022339", type: "isi", holder: "TTK Prestige Ltd", product: "Domestic pressure cookers (3 L–10 L)", standardCode: "IS 2347:2017", status: "valid", issuedOn: "2023-11-24", validTill: "2026-11-23", city: "Hosur, Tamil Nadu" },
  { markNo: "CM/L-8600055641", type: "isi", holder: "Super Steel & Alloys", product: "Hot rolled structural steel E250A", standardCode: "IS 2062:2011", status: "suspended", issuedOn: "2022-04-15", validTill: "2025-04-14", city: "Raipur, Chhattisgarh" },
  { markNo: "CM/L-9300188224", type: "isi", holder: "Vega Auto Accessories", product: "Protective helmets for motorcycle riders", standardCode: "IS 4151:2015", status: "valid", issuedOn: "2024-01-30", validTill: "2026-01-29", city: "Belagavi, Karnataka" },
  { markNo: "CM/L-6500991234", type: "isi", holder: "Himalaya Pipes Pvt Ltd", product: "HDPE pipes PE100 PN8 for water supply", standardCode: "IS 4984:2016", status: "valid", issuedOn: "2024-05-12", validTill: "2026-05-11", city: "Dehradun, Uttarakhand" },
  { markNo: "R-41003456812", type: "crs", holder: "Dell International Services India", product: "Notebook computers (series)", standardCode: "IS 13252-1:2010", status: "valid", issuedOn: "2024-03-08", validTill: "2026-03-07", city: "Bengaluru, Karnataka" },
  { markNo: "R-41008720411", type: "crs", holder: "Samsung India Electronics", product: "LED televisions (32–65 inch series)", standardCode: "IS 616:2017", status: "valid", issuedOn: "2023-12-01", validTill: "2025-11-30", city: "Noida, Uttar Pradesh" },
  { markNo: "R-41011900782", type: "crs", holder: "Ambrane India Pvt Ltd", product: "Power banks (10000–20000 mAh)", standardCode: "IS 16046:2018", status: "valid", issuedOn: "2024-07-17", validTill: "2026-07-16", city: "Sonipat, Haryana" },
  { markNo: "R-41002551094", type: "crs", holder: "Sunlit Lighting Co", product: "Self-ballasted LED lamps 7W–15W", standardCode: "IS 16102-1:2012", status: "expired", issuedOn: "2021-05-03", validTill: "2023-05-02", city: "Surat, Gujarat" },
  { markNo: "HM/C-729001188", type: "jeweller", holder: "Tanishq (Titan Company Ltd)", product: "Gold & silver jewellery retail outlets — Region South", standardCode: "IS 1417:2016", status: "valid", issuedOn: "2024-04-21", validTill: "2029-04-20", city: "Bengaluru, Karnataka" },
  { markNo: "HM/C-729004520", type: "jeweller", holder: "Kalyan Jewellers India Ltd", product: "Gold & silver jewellery retail outlets — Region West", standardCode: "IS 1417:2016", status: "valid", issuedOn: "2023-08-14", validTill: "2028-08-13", city: "Thrissur, Kerala" },
  { markNo: "A3K9P2", type: "huid", holder: "Tanishq (via Kundun Hallmark AHC)", product: "Gold bangle — 22K916 fineness, 18.4 g", standardCode: "IS 1417:2016", status: "valid", issuedOn: "2025-03-15", validTill: "9999-12-31", city: "Jaipur, Rajasthan" },
  { markNo: "M7TQ4X", type: "huid", holder: "Kalyan Jewellers (via TrueTest AHC)", product: "Gold necklace — 18K750 fineness, 24.1 g", standardCode: "IS 1417:2016", status: "valid", issuedOn: "2025-06-02", validTill: "9999-12-31", city: "Ahmedabad, Gujarat" },
  { markNo: "Z2R8LW", type: "huid", holder: "Malabar Gold (via Southern Assay House)", product: "Silver anklet pair — 925 fineness, 42.0 g", standardCode: "IS 2112:2014", status: "valid", issuedOn: "2025-01-20", validTill: "9999-12-31", city: "Chennai, Tamil Nadu" },
];

export async function seed() {
  console.log("Seeding PRAMAAN knowledge base…");
  await db.delete(standards);
  await db.delete(knowledgeDocs);
  await db.delete(labs);
  await db.delete(licences);

  await db.insert(standards).values(STD as never);
  await db.insert(knowledgeDocs).values(DOCS as never);
  await db.insert(labs).values(LABS as never);
  await db.insert(licences).values(LICENCES as never);

  console.log(
    `Seeded ${STD.length} standards, ${DOCS.length} docs, ${LABS.length} labs, ${LICENCES.length} licences.`,
  );
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
