/* Extra catalogue wave 14 — mechanical engineering: steel products, tubes,
 * valves and pumps, castings and welding, pressure equipment, LPG appliances,
 * fire protection equipment and personal protective equipment. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const STEEL_QCO = "Steel & Steel Products (Quality Control) Order";
const GAS_QCO = "Gas Cylinders (Quality Control) Order";
const FIRE_QCO = "Fire Extinguishers (Quality Control) Order";
const PPE_QCO = "Personal Protective Equipment (Quality Control) Order";

const STEEL_PRODUCTS: Block = {
  category: "mechanical",
  qco: STEEL_QCO,
  rows: [
    ["IS 10748:2008", "Hot Rolled Steel Strip for Welded Pipes and Tubes — Specification", "Strip grades for spiral and ERW pipe manufacture with chemistry and mechanical limits.", "M"],
    ["IS 1730:1989", "Dimensions for Steel Plates, Sheets, Strips and Flats for General Engineering Purposes", "Standard thickness, width and length schedules for plates and sheets."],
    ["IS 1731:1983", "Dimensions for Steel Bars (Round, Square and Hexagonal) for General Engineering Purposes", "Standard bar diameters and tolerances for machined components."],
    ["IS 1732:1983", "Dimensions for Tool Steel and Carbide Tips", "Standard blank and tip dimensions for cutting tools."],
    ["IS 1852:1985", "Rolling and Cutting Tolerances for Hot Rolled Steel Products", "Permissible thickness, width and length tolerances for hot rolled products."],
    ["IS 1876:1992", "Steel Bars for Re-Rolling into Structural Steel — Specification", "Re-rolling bar grades with chemistry and segregation limits."],
    ["IS 2284:1990", "Rivets and Rivet Bars — Specification", "Rivet head dimensions and bar quality requirements."],
    ["IS 2507:1976", "Refractory Materials — Specifications for Steel Plant Refractories", "Refractory brick grades for blast furnace, ladle and tundish lining."],
    ["IS 2790:1979", "Specification for Welded Steel Wire Fabrics for Concrete Reinforcement", "Weld mesh aperture, wire diameter and strength requirements."],
    ["IS 2800:1979", "Specification for Steel Bars for Concrete Reinforcement (Hard Drawn Wire)", "Hard drawn wire reinforcement requirements for prestressed and precast elements."],
    ["IS 1239-2:2004", "Steel Tubes, Tubulars and Other Wrought Steel Fittings — Part 2: Pipe Fittings", "Threaded and buttweld fitting dimensions and pressure ratings for steel piping."],
    ["IS 4923:2017", "Hollow Steel Sections for Structural Use — Specification", "Square, rectangular and circular hollow section dimensions and strength classes.", "M"],
    ["IS 1536:1989", "Centrifugally Cast Iron Pressure Pipes — Specification", "Spun iron pipe classes, hydrostatic test pressures and cement lining requirements."],
    ["IS 1978:1982", "Cast Iron Fittings for Pressure Pipes — Specification", "Socket, spigot and flange fitting dimensions for cast iron pressure mains."],
    ["IS 1979:1982", "Cast Iron Fittings for Pressure Pipes — Flanged Fittings", "Flanged branch, bend and tee dimensions for water mains."],
    ["IS 3588:1988", "Cast Iron Pipes for Water, Gas and Sewage (Spun and Sand Cast)", "Vertical cast iron pipe classes with crushing and hydrostatic test requirements."],
    ["IS 5504:1985", "Cast Iron Fittings for Pressure Pipes (Socket and Spigot)", "Fitting dimensions and quality requirements for socket-spigot joints."],
    ["IS 5822:1994", "Cast Iron Specials for Pressure Pipes — Specification", "Special castings for pipeline diversions, bends and tapers."],
    ["IS 11606:1986", "Cast Iron Rising Main Pipes for Tube Wells — Specification", "Riser pipe dimensions and strength for deep tube well installations."],
    ["IS 1538:1995", "Cast Iron Fittings for Pressure Pipes — General Requirements", "Common requirements, marking and testing of cast iron pipe fittings."],
    ["IS 2004:1991", "Carbon Steel Forgings for General Engineering Purposes — Specification", "Forging grades with heat treatment and mechanical property requirements."],
    ["IS 3469:1974", "Forged Steel Rolls for Rolling Mills — Specification", "Roll material, hardness and defect requirements for rolling mills."],
    ["IS 1379:1986", "Steel Wire Ropes — Specification", "Rope construction, lay, breaking load and lubrication requirements."],
    ["IS 6867:1973", "Steel Wire Slings — Specification", "Slings, thimbles and ferrule requirements with safe working load marking."],
    ["IS 1182:1971", "Specification for Steel Wire for Mechanical Springs", "Spring wire grades, diameter tolerance and surface finish."],
    ["IS 3613:1974", "Specification for Steel Wire for Prestressed Concrete", "High tensile wire requirements for prestressing.", "M"],
    ["IS 4021:1977", "Specification for Steel Wire for Ropes", "Wire grades and tensile classes for rope manufacture."],
    ["IS 5994:1985", "Specification for Steel Wire for Staples and Pins", "Wire requirements for stationery staples and industrial pins."],
    ["IS 7291:1974", "Specification for Steel Wire for Umbrella Ribs", "Wire strength and finish for umbrella frame components."],
    ["IS 6547:1972", "Specification for Steel Wire for Wire Nails", "Nail wire grades and coating requirements."],
  ],
};

const MACHINES_AND_EQUIPMENT: Block = {
  category: "mechanical",
  qco: STEEL_QCO,
  rows: [
    ["IS 780:1983", "Gate Valves for Water Works Purposes — Specification", "Gate valve body, seating and pressure test requirements for water supply."],
    ["IS 14845:2000", "Ball Valves for Water Supply — Specification", "Ball valve sizes, torque and pressure rating requirements."],
    ["IS 10983-1:1984", "Sluice Valves for Water Works — Specification", "Sluice valve construction, sealing and operating requirements."],
    ["IS 8472:1998", "Centrifugal Pumps for Water Supply — Specification", "Pump performance, efficiency and hydraulic test requirements."],
    ["IS 10804-1:1986", "Horizontal Centrifugal Pumps for Clear, Cold Water — Specification", "Pump duty point, head-capacity curve and efficiency tolerances."],
    ["IS 11549:1986", "Submersible Pump Sets for Agricultural Use — Specification", "Borewell submersible pump set performance and safety requirements."],
    ["IS 14226:1995", "Vertical Turbine Pumps — Specification", "Vertical turbine pump construction, bowl assembly and testing."],
    ["IS 5456:1985", "Air Compressors — Specification (Reciprocating Type)", "Reciprocating compressor capacities, safety valves and performance testing."],
    ["IS 9248:1979", "Safety Requirements for Air Compressors", "Guarding, pressure relief and controls for compressor safety."],
    ["IS 3823:1982", "Rolling Bearings — Specification for Deep Groove Ball Bearings", "Ball bearing dimensions, clearance and load rating requirements."],
    ["IS 3824:1982", "Rolling Bearings — Cylindrical Roller Bearings — Specification", "Roller bearing dimensional and load rating requirements."],
    ["IS 3825:1982", "Rolling Bearings — Taper Roller Bearings — Specification", "Taper roller bearing dimensions, tolerance classes and rating."],
    ["IS 6455:1972", "Rolling Bearings — Thrust Bearings — Specification", "Thrust bearing dimensions and load ratings for axial loads."],
    ["IS 4460:1995", "Code of Practice for Selection and Erection of Rolling Bearings", "Fitting, lubrication and mounting practice for bearings."],
    ["IS 4660:1978", "Gears — Specification for Spur and Helical Gears", "Tooth profile, accuracy grade and strength requirements for gears."],
    ["IS 4238:1982", "Specification for Machine Tool Elements — Guideways", "Guideway accuracy and surface requirements for machine tools."],
    ["IS 2985:1982", "Specification for Machine Vices", "Vice jaw dimensions, clamping force and accuracy requirements."],
    ["IS 1030:1998", "Carbon Steel Castings for General Engineering Purposes — Specification", "Casting grades with chemistry, heat treatment and defect acceptance limits.", "M"],
    ["IS 2708:1993", "Grey Iron Castings — Specification", "Grey iron grades by tensile strength and hardness for general castings."],
    ["IS 276:2000", "Spheroidal Graphite Iron Castings — Specification", "SG iron grades, nodularity and mechanical property requirements.", "M"],
    ["IS 1395:1982", "Covered Electrodes for Manual Metal Arc Welding of Mild Steel — Specification", "Electrode classification, coating type and weld metal properties.", "M"],
    ["IS 3580:1986", "Filler Rods for Welding of Structural Steels — Specification", "Filler rod chemistry and strength matching for structural welds."],
    ["IS 4351:1982", "Filler Rods and Wires for Welding of Cast Irons — Specification", "Filler metal requirements for cast iron repair welding."],
    ["IS 6419:1986", "Welding Consumables for Submerged Arc Welding — Specification", "Wire and flux combinations with weld metal property requirements."],
    ["IS 6560:1996", "Welding Consumables — CO2 Gas Shielded Arc Welding — Specification", "Solid wire and shielding gas requirements for CO2 welding."],
    ["IS 7307-1:1991", "Brazing Alloys — Specification — Part 1: Silver Brazing Alloys", "Silver brazing alloy composition, melting range and joint strength."],
    ["IS 5009:1979", "Specification for Screw Drivers", "Screwdriver blade sizes, hardness and insulation requirements."],
    ["IS 4503:1967", "Specification for Pressure Gauges", "Pressure gauge accuracy classes, dial sizes and overpressure protection."],
    ["IS 4530:1995", "Specification for Safety Valves for Pressure Vessels", "Safety valve set pressure, blowdown and capacity requirements.", "M"],
    ["IS 10437:1983", "Specification for Pressure Reducing Valves", "Pressure reducing valve sizing and outlet pressure stability."],
    ["IS 10439:1983", "Specification for Steam Traps", "Steam trap capacity, leakage and air venting requirements."],
  ],
};

const GAS_AND_FIRE: Block = {
  category: "mechanical",
  qco: GAS_QCO,
  rows: [
    ["IS 4576:1999", "Liquefied Petroleum Gas (LPG) Cylinders — Specification", "Cylinder shell thickness, valve fitting, testing and marking requirements for LPG cylinders.", "Q:Gas Cylinders (Quality Control) Order", { keywords: ["lpg cylinder", "gas cylinder", "गैस सिलेंडर"] }],
    ["IS 13258:1992", "LPG Pressure Regulators — Specification", "Regulator flow capacity, outlet pressure and leakage requirements.", "Q:Domestic Gas Stoves (Quality Control) Order"],
    ["IS 14899:2000", "LPG Flexible Hoses — Specification", "Hose reinforcement, burst pressure and ageing requirements for gas connections.", "Q:Domestic Gas Stoves (Quality Control) Order"],
    ["IS 1146:1985", "Domestic LPG Stove Burners — Specification", "Burner thermal efficiency, flame stability and safety requirements.", "Q:Domestic Gas Stoves (Quality Control) Order", { keywords: ["gas stove", "lpg stove", "गैस चूल्हा"] }],
    ["IS 2743:1997", "Steel Cylinders for Dissolved Acetylene Gas — Specification", "Acetylene cylinder porous mass, valve and pressure test requirements.", "Q:Gas Cylinders (Quality Control) Order"],
    ["IS 4572:1983", "Steel Cylinders for Compressed Gas — Specification", "Seamless cylinder design, wall thickness and hydrostatic test requirements.", "Q:Gas Cylinders (Quality Control) Order"],
    ["IS 933:1988", "Fire Buckets — Specification", "Fire bucket capacity, material and marking requirements."],
    ["IS 2171:1999", "Fire Hose — Specification", "Hose construction, burst pressure and adhesion requirements for firefighting."],
    ["IS 4989:1988", "Couplings for Fire Hose — Specification", "Instantaneous coupling dimensions and pressure tightness requirements."],
    ["IS 884:1985", "Fire Hydrants — Specification", "Hydrant body, valve and outlet dimensions for municipal fire mains."],
    ["IS 2871:2004", "Branch Pipes for Fire Fighting — Specification", "Branch pipe nozzles, flow rates and jet throw requirements."],
    ["IS 937:1987", "Fire Fighting — Suction Hose and Strainers — Specification", "Suction hose rigidity, couplings and strainer construction."],
    ["IS 10658:1983", "Fire Fighting Equipment — Glossary of Terms", "Standard terminology for firefighting equipment and systems."],
    ["IS 11788:1986", "Hose Reels for Fire Fighting — Specification", "Hose reel drum, swivel and nozzle requirements."],
    ["IS 13039:1991", "Portable Fire Extinguishers — Selection and Use", "Guidance on extinguisher types for different classes of fire."],
  ],
};

const PPE_AND_WORKPLACE: Block = {
  category: "consumer",
  qco: PPE_QCO,
  rows: [
    ["IS 3521:1999", "Industrial Safety Belts and Harnesses — Specification", "Full body harness strength, anchorage and test requirements for fall protection.", "Q:Personal Protective Equipment (Quality Control) Order"],
    ["IS 4770:1991", "Chemical Protective Clothing — Specification", "Material resistance, seam strength and design requirements for chemical suits.", "Q:Personal Protective Equipment (Quality Control) Order"],
    ["IS 4501:1982", "Specification for Eye Protectors for Industrial Workers", "Goggle and face shield optical quality, impact resistance and coverage requirements.", "Q:Personal Protective Equipment (Quality Control) Order"],
    ["IS 15298-1:2010", "Personal Protective Equipment — Safety Footwear — Part 1: Test Method for Whole Footwear", "Whole footwear test methods including ankle protection and sole performance."],
  ],
};

const TEST_METHODS_MECHANICAL: Block = {
  category: "mechanical",
  rows: [
    ["IS 2720-12:1981", "Methods of Test for Soils — Part 12: Determination of Shear Strength Parameters by Unconfined Compression Test", "Unconfined compression strength determination for cohesive soils."],
    ["IS 2720-14:1983", "Methods of Test for Soils — Part 14: Determination of Density Index (Relative Density) of Cohesionless Soils", "Relative density determination for sands and gravels."],
    ["IS 2720-19:1992", "Methods of Test for Soils — Part 19: Determination of Centrifuge Moisture Equivalent", "Centrifuge moisture equivalent determination for soil classification."],
    ["IS 2720-20:1992", "Methods of Test for Soils — Part 20: Determination of Linear Shrinkage", "Linear shrinkage measurement for expansive soils."],
    ["IS 2720-21:1977", "Methods of Test for Soils — Part 21: Determination of Total Soluble Solids", "Total soluble solids determination for soil salinity assessment."],
    ["IS 2720-22:1972", "Methods of Test for Soils — Part 22: Determination of Organic Matter", "Organic matter content determination by dichromate oxidation."],
    ["IS 2720-23:1976", "Methods of Test for Soils — Part 23: Determination of Calcium Carbonate", "Calcium carbonate content determination by calcimeter method."],
    ["IS 2720-24:1976", "Methods of Test for Soils — Part 24: Determination of Cation Exchange Capacity", "CEC determination for soil fertility and stabilization studies."],
    ["IS 2720-25:1982", "Methods of Test for Soils — Part 25: Determination of Silica Sesquioxide Ratio", "Silica sesquioxide ratio determination for lateritic soils."],
    ["IS 2720-30:1980", "Methods of Test for Soils — Part 30: Determination of Dry Density of Soils In-Place by the Core Cutter Method", "In-place dry density determination using core cutters."],
    ["IS 2720-32:1981", "Methods of Test for Soils — Part 32: Determination of Density of Soil In-Place by Nuclear Methods", "Nuclear gauge method for in-place soil density and moisture."],
    ["IS 2720-36-1:1987", "Methods of Test for Soils — Part 36: Laboratory Determination of Permeability of Granular Soils — Constant Head Method", "Constant head permeability testing of granular soils."],
    ["IS 2720-36-2:1987", "Methods of Test for Soils — Part 36: Laboratory Determination of Permeability of Granular Soils — Variable Head Method", "Variable head permeability determination for fine-grained soils."],
    ["IS 2720-37:1976", "Methods of Test for Soils — Part 37: Determination of Sand Equivalent Value", "Sand equivalent test for granular pavement materials."],
    ["IS 2720-38:1976", "Methods of Test for Soils — Part 38: Determination of Compaction Characteristics of Soils by Vibrating Hammer", "Vibratory compaction testing for cohesionless soils."],
    ["IS 2720-42:1994", "Methods of Test for Soils — Part 42: Determination of the Angle of Obliquity", "Angle of obliquity determination for retaining structure design."],
    ["IS 4031-7:1988", "Methods of Physical Tests for Hydraulic Cement — Part 7: Determination of Heat of Hydration", "Heat of hydration measurement for mass concrete and low heat cements."],
    ["IS 4031-8:1988", "Methods of Physical Tests for Hydraulic Cement — Part 8: Determination of Transverse and Compressive Strength of Plastic Mortar", "Plastic mortar strength testing for masonry cement."],
    ["IS 4031-9:1989", "Methods of Physical Tests for Hydraulic Cement — Part 9: Determination of False Set", "False set detection by penetration resistance testing."],
    ["IS 4031-10:1988", "Methods of Physical Tests for Hydraulic Cement — Part 10: Determination of Drying Shrinkage", "Drying shrinkage measurement for cement mortars."],
    ["IS 4031-12:1988", "Methods of Physical Tests for Hydraulic Cement — Part 12: Determination of Air Content of Mortar", "Air content determination in cement mortar mixes."],
    ["IS 6461-2:1972", "Glossary of Terms Relating to Cement Concrete — Part 2: Properties of Concrete", "Terminology for workability, strength and durability properties."],
    ["IS 6461-3:1972", "Glossary of Terms Relating to Cement Concrete — Part 3: Types of Cement", "Terminology for cement types including blended and special cements."],
    ["IS 6461-5:1972", "Glossary of Terms Relating to Cement Concrete — Part 5: Methods of Concrete Construction", "Terminology for placing, compaction, curing and formwork."],
    ["IS 6461-6:1972", "Glossary of Terms Relating to Cement Concrete — Part 6: Types of Concrete Construction", "Terminology for precast, prestressed and in-situ construction."],
    ["IS 6461-7:1972", "Glossary of Terms Relating to Cement Concrete — Part 7: Reinforcement", "Terminology for reinforcement types, detailing and cover."],
    ["IS 6461-8:1973", "Glossary of Terms Relating to Cement Concrete — Part 8: Concrete Constituents", "Terminology for aggregates, admixtures and water."],
    ["IS 6461-9:1973", "Glossary of Terms Relating to Cement Concrete — Part 9: Testing of Concrete", "Terminology for sampling, specimen preparation and test methods."],
    ["IS 6461-10:1973", "Glossary of Terms Relating to Cement Concrete — Part 10: Concrete Mixes", "Terminology for nominal and design mixes."],
    ["IS 6461-11:1973", "Glossary of Terms Relating to Cement Concrete — Part 11: Machinery and Equipment", "Terminology for batching plants, mixers, vibrators and pumps."],
    ["IS 6461-12:1973", "Glossary of Terms Relating to Cement Concrete — Part 12: Special Concretes", "Terminology for lightweight, fibre reinforced and high performance concretes."],
  ],
};

export const STD_WAVE14 = buildBlocks(
  STEEL_PRODUCTS,
  MACHINES_AND_EQUIPMENT,
  GAS_AND_FIRE,
  PPE_AND_WORKPLACE,
  TEST_METHODS_MECHANICAL,
);
