/* Extra catalogue wave 11 — electronics & IT (CRS), medical electrical
 * equipment, EMC, hazardous-area equipment, rotating machine adoptions and
 * optical fibre test methods. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const CRS = "Electronics & IT Goods (CRS) Order, 2012";

const ICT_AND_AV: Block = {
  category: "electronics",
  qco: CRS,
  rows: [
    ["IS 13252-2:2010", "Information Technology Equipment — Safety — Part 2: Particular Requirements for Equipment Installed Outdoors", "Safety requirements for outdoor IT equipment such as wireless access points and enclosures.", "C"],
    ["IS 13252-3:2010", "Information Technology Equipment — Safety — Part 3: Particular Requirements for Equipment Connected to Telecommunication Networks", "Safety requirements for IT equipment connected to telecom networks.", "C"],
    ["IS 13252-4:2013", "Information Technology Equipment — Safety — Part 4: Particular Requirements for Audio/Video, Information and Communication Technology Equipment", "Consolidated safety requirements for converged AV and ICT equipment.", "C"],
    ["IS 16333-1:2015", "Mobile Phone Handsets — Specification — Part 1: Safety Requirements", "Electrical safety requirements for mobile phone handsets and their chargers.", "C"],
    ["IS 16333-2:2015", "Mobile Phone Handsets — Specification — Part 2: Electromagnetic Compatibility Requirements", "EMC requirements for mobile handsets including immunity and emission limits.", "C"],
    ["IS 16333-4:2022", "Mobile Phone Handsets — Specification — Part 4: Requirements for Indian Languages Support", "Indian language text input, fonts and rendering requirements for mobile handsets.", "C"],
    ["IS 16344:2015", "Printers, Plotters and Multifunction Devices — Safety Requirements", "Electrical safety requirements for printers, plotters and multifunction devices.", "C"],
    ["IS 16102-4:2013", "Self-Ballasted LED Lamps — Part 4: Photometric and Electrical Measurement Methods", "Measurement procedures for LED lamp flux, power and colour characteristics."],
    ["IS 16047-1:2012", "External Power Supplies — Part 1: Performance Requirements", "Efficiency and no-load power requirements for external power adapters and chargers."],
    ["IS 16749:2018", "Set-Top Boxes — Safety Requirements", "Safety and performance requirements for set-top boxes with external or internal power supplies.", "C"],
    ["IS 16520:2016", "Power Banks and Portable USB Chargers — Safety Requirements", "Battery, thermal and short circuit safety requirements for portable power banks.", "C"],
    ["IS 16439:2015", "CCTV Systems — Requirements for Cameras and Recording Equipment", "Performance and safety requirements for CCTV cameras and digital video recorders."],
    ["IS 16183:2014", "Video Surveillance — Transmission and Storage Requirements", "Guidance on IP video transmission, storage retention and data protection."],
    ["IS 15100:2002", "Audio, Video and Similar Electronic Apparatus — Safety Requirements", "General safety requirements for AV apparatus including construction and thermal limits.", "C"],
    ["IS 15115:2002", "Audio, Video and Similar Electronic Apparatus — Immunity Requirements", "Immunity requirements for AV equipment against ESD, RF and transient disturbances."],
    ["IS 15398:2003", "Uninterruptible Power Systems — Safety and Performance Requirements", "UPS classification, output quality and safety requirements for ICT installations."],
    ["IS 12603-1:1989", "Radio Interference Measuring Apparatus — Specification", "Measurement receiver requirements for radio interference voltage and field measurements."],
    ["IS 10052-1:1994", "Radio Interference Suppression — Part 1: General Requirements", "Suppression component and filter requirements for limiting conducted interference."],
    ["IS 10100:1982", "Specification for Radio Interference Measuring Sets — Portable Type", "Portable interference measuring set performance and calibration requirements."],
    ["IS 13313:1992", "Guidelines for Electromagnetic Interference Measurement of Industrial Equipment", "Practical guidance for measuring EMI from industrial installations."],
    ["IS 11343:1985", "Code of Practice for Earthing of Electronic Equipment Installations", "Earthing and bonding practice for electronic equipment rooms and data centres."],
    ["IS 16402:2015", "Data Centres — Design and Operation Guidelines", "Guidance on data centre power, cooling, cabling and availability tiers."],
    ["IS 16429:2016", "Solid State Storage Devices and Memory Cards — Requirements", "Performance, endurance and safety requirements for solid state storage media."],
    ["IS 16166:2014", "Electronic Toll Collection Systems — Requirements", "Transponder, reader and transaction requirements for electronic toll collection."],
    ["IS 16167:2014", "Smart Cards — Physical and Electrical Requirements", "Smart card dimensions, contact and electrical characteristics."],
    ["IS 16254:2014", "Electronic Voting Machines — Requirements", "Design, security and reliability requirements for electronic voting machines."],
    ["IS 16650:2017", "Internet of Things (IoT) Devices — Security and Interoperability Guidelines", "Security baseline and interoperability guidance for connected IoT devices."],
    ["IS 16948:2018", "Biometric Authentication Devices — Requirements for Aadhaar Enabled Devices", "Device registration, encryption and certification requirements for Aadhaar authentication devices."],
    ["IS 15825:2009", "Solar Photovoltaic Lighting Systems — Field Testing Guidelines", "Field testing guidance for solar lanterns and home lighting systems."],
    ["IS 15758:2007", "Guidelines for Installation of Rooftop Solar Photovoltaic Systems", "Structural, cabling and protection guidance for rooftop solar installations."],
  ],
};

const MEDICAL_ELECTRICAL: Block = {
  category: "electronics",
  qco: CRS,
  rows: [
    ["IS/IEC 60601-1:2008", "Medical Electrical Equipment — Part 1: General Requirements for Basic Safety and Essential Performance", "The core medical electrical equipment standard — protection against electric shock, mechanical and thermal hazards, and essential performance.", "M", { keywords: ["medical electrical equipment", "medical device safety", "चिकित्सा उपकरण"] }],
    ["IS/IEC 60601-1-2:2014", "Medical Electrical Equipment — Part 1-2: General Requirements — Electromagnetic Disturbances", "EMC requirements for medical electrical equipment including immunity and emissions."],
    ["IS/IEC 60601-1-6:2013", "Medical Electrical Equipment — Part 1-6: Usability", "Usability engineering process requirements for medical electrical equipment."],
    ["IS/IEC 60601-1-11:2011", "Medical Electrical Equipment — Part 1-11: Requirements for Home Healthcare Environment", "Requirements for medical electrical equipment used in home healthcare."],
    ["IS/IEC 60601-2-4:2013", "Medical Electrical Equipment — Part 2-4: Particular Requirements for Cardiac Defibrillators", "Safety and performance requirements for cardiac defibrillators and defibrillator-monitors."],
    ["IS/IEC 60601-2-25:2016", "Medical Electrical Equipment — Part 2-25: Particular Requirements for Electrocardiographs", "Requirements for electrocardiographs including accuracy of ECG reproduction."],
    ["IS/IEC 60601-2-27:2014", "Medical Electrical Equipment — Part 2-27: Particular Requirements for Electrocardiographic Monitoring Equipment", "Requirements for ECG monitoring equipment including alarm and arrhythmia detection."],
    ["IS/IEC 60601-2-1:2014", "Medical Electrical Equipment — Part 2-1: Particular Requirements for Electron Accelerators", "Requirements for electron accelerators in the range 1 MeV to 50 MeV."],
    ["IS/IEC 60601-2-2:2014", "Medical Electrical Equipment — Part 2-2: Particular Requirements for High Frequency Surgical Equipment", "HF surgical and HF surgical accessories safety requirements."],
    ["IS/IEC 60601-2-5:2014", "Medical Electrical Equipment — Part 2-5: Particular Requirements for Ultrasonic Physiotherapy Equipment", "Requirements for ultrasonic physiotherapy equipment including output accuracy."],
    ["IS/IEC 60601-2-8:2015", "Medical Electrical Equipment — Part 2-8: Particular Requirements for Therapeutic X-Ray Equipment", "Therapeutic X-ray equipment from 10 kV to 1 MV — safety and dose control."],
    ["IS/IEC 60601-2-12:2015", "Medical Electrical Equipment — Part 2-12: Particular Requirements for Lung Ventilators", "Ventilator safety, alarm and performance requirements for critical care use."],
    ["IS/IEC 60601-2-16:2014", "Medical Electrical Equipment — Part 2-16: Particular Requirements for Haemodialysis Equipment", "Haemodialysis and haemofiltration equipment safety requirements."],
    ["IS/IEC 60601-2-18:2015", "Medical Electrical Equipment — Part 2-18: Particular Requirements for Endoscopic Equipment", "Endoscopic equipment safety including electrical and thermal hazards."],
    ["IS/IEC 60601-2-19:2016", "Medical Electrical Equipment — Part 2-19: Particular Requirements for Infant Incubators", "Infant incubator temperature control, alarm and safety requirements."],
    ["IS/IEC 60601-2-20:2016", "Medical Electrical Equipment — Part 2-20: Particular Requirements for Transport Incubators", "Transport incubator requirements for ambulance and air transport use."],
    ["IS/IEC 60601-2-22:2014", "Medical Electrical Equipment — Part 2-22: Particular Requirements for Surgical, Cosmetic, Therapeutic and Diagnostic Laser Equipment", "Laser equipment safety requirements including radiation and controls."],
    ["IS/IEC 60601-2-24:2016", "Medical Electrical Equipment — Part 2-24: Particular Requirements for Infusion Pumps and Controllers", "Infusion pump accuracy, occlusion alarm and free-flow protection requirements."],
    ["IS/IEC 60601-2-30:2016", "Medical Electrical Equipment — Part 2-30: Particular Requirements for Automatic Cycling Non-Invasive Blood Pressure Monitors", "NIBP monitor accuracy, cuff pressure limits and safety requirements."],
    ["IS/IEC 60601-2-34:2016", "Medical Electrical Equipment — Part 2-34: Particular Requirements for Invasive Blood Pressure Monitoring Equipment", "Invasive blood pressure monitoring equipment requirements."],
    ["IS/IEC 60601-2-36:2016", "Medical Electrical Equipment — Part 2-36: Particular Requirements for Extracorporeally Induced Lithotripsy Equipment", "Lithotripsy equipment safety and output requirements."],
    ["IS/IEC 60601-2-37:2016", "Medical Electrical Equipment — Part 2-37: Particular Requirements for Ultrasonic Medical Diagnostic and Monitoring Equipment", "Ultrasound diagnostic equipment output limits and safety indices."],
    ["IS/IEC 60601-2-39:2016", "Medical Electrical Equipment — Part 2-39: Particular Requirements for Peritoneal Dialysis Equipment", "Peritoneal dialysis equipment safety and performance requirements."],
    ["IS/IEC 60601-2-40:2016", "Medical Electrical Equipment — Part 2-40: Particular Requirements for Electromyographs and Evoked Response Equipment", "EMG and evoked response equipment accuracy and safety requirements."],
    ["IS/IEC 60601-2-41:2016", "Medical Electrical Equipment — Part 2-41: Particular Requirements for Surgical Luminaires and Luminaires for Diagnosis", "Surgical and diagnostic luminaire illumination and thermal requirements."],
    ["IS/IEC 60601-2-44:2016", "Medical Electrical Equipment — Part 2-44: Particular Requirements for X-Ray Equipment for Computed Tomography", "CT scanner safety, dose indication and image quality requirements."],
    ["IS/IEC 60601-2-45:2016", "Medical Electrical Equipment — Part 2-45: Particular Requirements for Mammographic X-Ray Equipment", "Mammography equipment dose, compression and image quality requirements."],
    ["IS/IEC 60601-2-47:2016", "Medical Electrical Equipment — Part 2-47: Particular Requirements for Ambulatory Electrocardiographic Systems", "Ambulatory ECG system performance and recording requirements."],
    ["IS/IEC 60601-2-49:2016", "Medical Electrical Equipment — Part 2-49: Particular Requirements for Multifunction Patient Monitoring Equipment", "Multifunction patient monitor alarm, accuracy and safety requirements."],
    ["IS/IEC 60601-2-50:2016", "Medical Electrical Equipment — Part 2-50: Particular Requirements for Infant Phototherapy Equipment", "Infant phototherapy irradiance, eye protection and safety requirements."],
    ["IS/ISO 13485:2016", "Medical Devices — Quality Management Systems — Requirements for Regulatory Purposes", "Quality management system requirements for medical device design, manufacture and servicing.", "V", { keywords: ["iso 13485", "quality management", "medical device"] }],
    ["IS 10258-1:2022", "Sterile Hypodermic Syringes for Single Use — Part 1: Syringes for Manual Use", "Design, dimensions, graduation, leak and sterility requirements for single-use manual syringes (identical with ISO 7886-1).", "Q:Medical Devices (Quality Control) Order"],
    ["IS 11196:1985", "Blood Transfusion Sets — Specification", "Transfusion set components, flow rate and sterility requirements.", "Q:Medical Devices (Quality Control) Order"],
    ["IS 11197:1985", "Urine Collection Bags — Specification", "Urine bag capacity, tubing and sterility requirements.", "Q:Medical Devices (Quality Control) Order"],
    ["IS 14658:1999", "Sterile Hypodermic Needles for Single Use — Specification", "Needle dimensions, sharpness and sterility requirements.", "Q:Medical Devices (Quality Control) Order"],
    ["IS 15616:2005", "Disposable Surgical Rubber Gloves — Specification", "Glove dimensions, tensile strength and leak test requirements.", "Q:Medical Devices (Quality Control) Order"],
    ["IS 13186:1992", "Specification for Contraceptive Sheaths (Condoms)", "Condom dimensions, burst volume and burst pressure requirements.", "Q:Medical Devices (Quality Control) Order"],
    ["IS 9886-1:1981", "Specification for Surgical Dressings — Part 1: Absorbent Cotton Wool", "Absorbent cotton properties including absorbency and purity.", "Q:Medical Devices (Quality Control) Order"],
  ],
};

const EMC_AND_ENVIRONMENT: Block = {
  category: "electronics",
  rows: [
    ["IS 14700-3-2:2014", "Electromagnetic Compatibility — Part 3-2: Limits for Harmonic Current Emissions", "Harmonic current emission limits for equipment with input current up to 16 A per phase."],
    ["IS 14700-3-3:2016", "Electromagnetic Compatibility — Part 3-3: Limitation of Voltage Changes, Fluctuations and Flicker", "Voltage fluctuation and flicker limits for low voltage installations."],
    ["IS 14700-4-1:2019", "Electromagnetic Compatibility — Part 4-1: Testing and Measurement Techniques — Overview of Immunity Tests", "Overview and selection guidance for the IEC 61000-4 immunity test series."],
    ["IS 14700-4-2:2019", "Electromagnetic Compatibility — Part 4-2: Testing and Measurement Techniques — Electrostatic Discharge Immunity Test", "ESD immunity test levels and procedure for equipment."],
    ["IS 14700-4-3:2010", "Electromagnetic Compatibility — Part 4-3: Testing and Measurement Techniques — Radiated, Radio-Frequency, Electromagnetic Field Immunity Test", "Radiated RF field immunity testing from 80 MHz to several GHz."],
    ["IS 14700-4-4:2014", "Electromagnetic Compatibility — Part 4-4: Testing and Measurement Techniques — Electrical Fast Transient/Burst Immunity Test", "EFT/burst immunity testing for mains and signal ports."],
    ["IS 14700-4-5:2014", "Electromagnetic Compatibility — Part 4-5: Testing and Measurement Techniques — Surge Immunity Test", "Surge immunity test waveform, coupling and severity levels."],
    ["IS 14700-4-6:2014", "Electromagnetic Compatibility — Part 4-6: Testing and Measurement Techniques — Immunity to Conducted Disturbances Induced by Radio-Frequency Fields", "Conducted RF immunity testing using coupling/decoupling networks."],
    ["IS 14700-4-11:2014", "Electromagnetic Compatibility — Part 4-11: Testing and Measurement Techniques — Voltage Dips, Short Interruptions and Voltage Variations Immunity Tests", "Immunity testing for voltage dips and short interruptions."],
    ["IS 14700-6-1:2019", "Electromagnetic Compatibility — Part 6-1: Generic Standards — Emission Standard for Residential, Commercial and Light-Industrial Environments", "Generic emission limits for equipment in residential and light-industrial environments."],
    ["IS 14700-6-2:2019", "Electromagnetic Compatibility — Part 6-2: Generic Standards — Immunity Standard for Industrial Environments", "Generic immunity requirements for equipment in industrial environments."],
    ["IS 14700-6-3:2014", "Electromagnetic Compatibility — Part 6-3: Generic Standards — Emission Standard for Equipment in Residential Environments", "Generic emission standard used for CRS testing of consumer electronic products."],
    ["IS 14700-6-4:2014", "Electromagnetic Compatibility — Part 6-4: Generic Standards — Emission Standard for Industrial Environments", "Generic emission limits for industrial equipment installations."],
    ["IS/IEC 60079-1:2017", "Explosive Atmospheres — Part 1: Equipment Protection by Flameproof Enclosures 'd'", "Flameproof enclosure requirements and flame transmission tests."],
    ["IS/IEC 60079-2:2011", "Explosive Atmospheres — Part 2: Equipment Protection by Pressurized Enclosure 'p'", "Pressurized enclosure requirements including purging and monitoring."],
    ["IS/IEC 60079-5:2011", "Explosive Atmospheres — Part 5: Equipment Protection by Powder Filling 'q'", "Powder filling protection requirements for electrical equipment."],
    ["IS/IEC 60079-7:2017", "Explosive Atmospheres — Part 7: Equipment Protection by Increased Safety 'e'", "Increased safety protection requirements for motors, luminaires and terminals."],
    ["IS/IEC 60079-11:2011", "Explosive Atmospheres — Part 11: Equipment Protection by Intrinsic Safety 'i'", "Intrinsic safety requirements for circuits and associated apparatus."],
    ["IS/IEC 60079-15:2010", "Explosive Atmospheres — Part 15: Equipment Protection by Type of Protection 'n'", "Non-sparking protection requirements for Zone 2 equipment."],
    ["IS/IEC 60079-18:2011", "Explosive Atmospheres — Part 18: Equipment Protection by Encapsulation 'm'", "Encapsulation protection requirements for electrical equipment."],
    ["IS/IEC 60079-31:2015", "Explosive Atmospheres — Part 31: Equipment Dust Ignition Protection by Enclosure 't'", "Dust ignition protection requirements for equipment in combustible dust areas."],
    ["IS 15999-3:2011", "Rotating Electrical Machines — Part 3: Specific Requirements for Synchronous Generators", "Specific requirements for synchronous generators driven by turbines and engines."],
    ["IS 15999-5:2011", "Rotating Electrical Machines — Part 5: Degrees of Protection Provided by the Integral Design of Rotating Electrical Machines (IP Code)", "IP classification for rotating machines and verification tests."],
    ["IS 15999-6:2011", "Rotating Electrical Machines — Part 6: Methods of Cooling (IC Code)", "Cooling designation and circuit arrangements for rotating machines."],
    ["IS 15999-7:2011", "Rotating Electrical Machines — Part 7: Classification of Types of Construction and Mounting Arrangements (IM Code)", "Mounting arrangement classification for industrial machines."],
    ["IS 15999-8:2011", "Rotating Electrical Machines — Part 8: Terminal Markings and Direction of Rotation", "Terminal designation and rotation conventions for machine connections."],
    ["IS 15999-9:2011", "Rotating Electrical Machines — Part 9: Noise Limits", "Sound power level limits for rotating electrical machines by frame and speed."],
    ["IS 15999-11:2011", "Rotating Electrical Machines — Part 11: Thermal Protection", "Built-in thermal protection requirements for rotating machines."],
    ["IS 15999-12:2011", "Rotating Electrical Machines — Part 12: Starting Performance of Single-Speed Three-Phase Cage Induction Motors", "Starting torque and current classifications for cage induction motors."],
    ["IS 15999-18-1:2011", "Rotating Electrical Machines — Part 18-1: Partial Discharge Resistant Electrical Insulation Systems for Rotating Machines", "Test procedures for partial discharge resistant insulation systems."],
    ["IS 15999-30:2011", "Rotating Electrical Machines — Part 30: Efficiency Classes of Line Operated AC Motors (IE Code)", "IE1 to IE4 efficiency classification and marking requirements for AC motors."],
    ["IS 15999-31:2011", "Rotating Electrical Machines — Part 31: Efficiency Classes of Converter-Fed Motors", "Efficiency classes for variable frequency drive fed motors."],
  ],
};

const FIBRE_AND_TELECOM: Block = {
  category: "electronics",
  rows: [
    ["IS 10810-10:1984", "Methods of Test for Optical Fibre Cables — Part 10: Measurement of Attenuation", "Attenuation measurement by cut-back and backscatter methods."],
    ["IS 10810-11:1986", "Methods of Test for Optical Fibre Cables — Part 11: Measurement of Bandwidth", "Bandwidth and dispersion measurement for multimode fibre cables."],
    ["IS 10810-12:1986", "Methods of Test for Optical Fibre Cables — Part 12: Measurement of Cut-Off Wavelength", "Cut-off wavelength measurement for single-mode fibres."],
    ["IS 10810-13:1986", "Methods of Test for Optical Fibre Cables — Part 13: Tensile Strength Test", "Tensile loading test procedure for optical fibre cables."],
    ["IS 10810-14:1986", "Methods of Test for Optical Fibre Cables — Part 14: Crush Test", "Crush resistance test for duct-laid optical cables."],
    ["IS 10810-15:1986", "Methods of Test for Optical Fibre Cables — Part 15: Impact Test", "Impact test procedure for optical fibre cable mechanical durability."],
    ["IS 10810-16:1986", "Methods of Test for Optical Fibre Cables — Part 16: Repeated Bending Test", "Repeated bending endurance testing of optical cables."],
    ["IS 10810-17:1986", "Methods of Test for Optical Fibre Cables — Part 17: Torsion Test", "Torsion test procedure for aerial and duct cables."],
    ["IS 10810-18:1986", "Methods of Test for Optical Fibre Cables — Part 18: Water Penetration Test", "Water penetration test for cable ingress protection."],
    ["IS 10810-19:1986", "Methods of Test for Optical Fibre Cables — Part 19: Temperature Cycling Test", "Temperature cycling test for attenuation stability."],
    ["IS 10810-20:1986", "Methods of Test for Optical Fibre Cables — Part 20: Dimensional Measurements", "Fibre, tube and sheath dimensional measurement procedures."],
    ["IS 10810-21:1986", "Methods of Test for Optical Fibre Cables — Part 21: Measurement of Numerical Aperture", "Numerical aperture measurement for multimode fibres."],
    ["IS 10810-22:1986", "Methods of Test for Optical Fibre Cables — Part 22: Measurement of Mode Field Diameter", "Mode field diameter measurement for single-mode fibres."],
    ["IS 10810-23:1990", "Methods of Test for Optical Fibre Cables — Part 23: Sheath Integrity and Abrasion Test", "Sheath integrity, abrasion and marking durability testing."],
    ["IS 10810-24:1990", "Methods of Test for Optical Fibre Cables — Part 24: Ageing and Environmental Tests", "Ageing, humidity and UV exposure tests for optical cables."],
    ["IS 10481:1983", "Specification for Optical Fibre Cables for Telecommunications", "Optical cable construction, attenuation and mechanical requirements for telecom networks."],
    ["IS 8437:1993", "Specification for Joint Enclosures and Closures for Optical Fibre Cables", "Splice closure sealing, re-entry and mechanical requirements."],
    ["IS 11726:1986", "Code of Practice for Laying of Optical Fibre Cables", "Trenching, duct laying, pulling tension and protection practice for OFC routes."],
    ["IS 13710-1:1993", "Optical Fibre Splices and Connectors — Part 1: General Requirements", "Splice and connector optical and mechanical requirements."],
    ["IS 14164:1994", "Optical Time Domain Reflectometer — Specification", "OTDR dynamic range, resolution and accuracy requirements for cable testing."],
    ["IS 16010:2012", "Telecommunication Cables — Polyethylene Insulated Jelly Filled Cables — Specification", "Jelly filled copper telecom cable construction and electrical requirements."],
    ["IS 16374:2015", "Telecommunication Equipment — Safety and EMC Requirements", "Consolidated safety and EMC requirements for telecom network equipment."],
    ["IS 16566:2018", "Guidelines for Installation of In-Building Solutions for Mobile Coverage", "Design and installation guidance for in-building mobile signal solutions."],
    ["IS 16658:2017", "Guidelines for Telecom Infrastructure Sharing", "Technical requirements for sharing towers, ducts and active equipment."],
    ["IS 16710:2018", "Public Wi-Fi Access Networks — Requirements", "Requirements for public Wi-Fi hotspots including authentication and security."],
    ["IS 16845:2018", "Mobile Device Chargers — Interoperability Requirements", "Interoperability and safety requirements for mobile chargers and cables."],
    ["IS 16982:2018", "Internet Protocol Television (IPTV) — Requirements", "Service, quality and security requirements for IPTV delivery."],
    ["IS 17101:2019", "Digital Terrestrial Television Receivers — Requirements", "Receiver performance, safety and interface requirements for DTT services."],
    ["IS 16048:2012", "Cable Television Networks — Technical Requirements", "Signal level, carrier-to-noise and installation requirements for CATV networks."],
    ["IS 16331:2015", "Condition Monitoring of Transformers and Reactors — Guidelines", "Online and offline diagnostic techniques for power transformer condition assessment."],
  ],
};

export const STD_WAVE11 = buildBlocks(
  ICT_AND_AV,
  MEDICAL_ELECTRICAL,
  EMC_AND_ENVIRONMENT,
  FIBRE_AND_TELECOM,
);
