/* Extra catalogue wave 9 — structural steel, welding, fasteners, fire safety,
 * building services (HVAC, water supply, drainage) and public health works. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const STEEL_QCO = "Steel & Steel Products (Quality Control) Order";

const STRUCTURAL_STEEL: Block = {
  category: "construction",
  qco: STEEL_QCO,
  rows: [
    ["IS 801:1975", "Code of Practice for Use of Cold-Formed Light Gauge Steel Structural Members in General Building Construction", "Design stresses and detailing for cold-formed light gauge steel members used in sheds and false ceilings."],
    ["IS 802-1:2015", "Use of Structural Steel in Overhead Transmission Line Towers — Code of Practice — Part 1: Materials, Loads and Permissible Stresses", "Load combinations, permissible stresses and material requirements for transmission line towers."],
    ["IS 803:1976", "Code of Practice for Design, Fabrication and Erection of Vertical Mild Steel Cylindrical Welded Oil Storage Tanks", "Design and fabrication of vertical cylindrical welded storage tanks with shell thickness rules."],
    ["IS 804:1967", "Code of Practice for Design, Fabrication and Erection of Rectangular Steel Tanks", "Design and erection of rectangular welded steel tanks for water and liquids."],
    ["IS 805:1968", "Code of Practice for Use of Steel in Gravity Water Supply Schemes", "Steel components in gravity water supply schemes — pipes, tanks and supports."],
    ["IS 806:1968", "Code of Practice for Use of Steel in Water Works", "Steelwork practice for water treatment plants and supply infrastructure."],
    ["IS 1091:1984", "Code of Practice for Riveting of Steel Structures", "Rivet sizes, spacing and workmanship for riveted steel connections."],
    ["IS 817:1966", "Code of Practice for Training and Testing of Metal Arc Welders", "Welder qualification requirements and testing practice for manual metal arc welding."],
    ["IS 1024:1977", "Code of Practice for Use of Welding in Steel Structures (Metal Arc)", "Design and workmanship rules for metal arc welded connections in steel structures."],
    ["IS 1181:1967", "Code of Practice for Welding in Structural Work", "General welding practice for structural and fabrication work."],
    ["IS 1323:1982", "Code of Practice for Oxy-Acetylene Welding in Structural Steel Work", "Oxy-acetylene welding practice and quality requirements for structural steel."],
    ["IS 1367-3:2017", "Technical Supply Conditions for Threaded Steel Fasteners — Part 3: Mechanical Properties of Fasteners Made of Carbon Steel", "Mechanical property classes of bolts, screws and studs under tensile and proof load tests."],
    ["IS 1367-11:2002", "Technical Supply Conditions for Threaded Steel Fasteners — Part 11: Surface Discontinuities", "Acceptable surface discontinuities on threaded fasteners and inspection guidance."],
    ["IS 6639:1972", "Specification for Hexagon Bolts for Steel Structures", "Hexagon bolt dimensions and strength requirements for steel structures."],
    ["IS 6640-1:1972", "Specification for Plain Washers — Part 1: Metric Series", "Metric plain washer dimensions, hardness and finish for bolted connections."],
    ["IS 3063:1994", "Fasteners — Single Coil Rectangular Section Spring Washers — Specification", "Spring washer requirements for preventing loosening in vibrating machinery and structures."],
    ["IS 1570-1:2018", "Steels for Common Engineering Purposes — Part 1: Carbon and Carbon Manganese Steels", "Base steel grades with chemical composition and mechanical property tables for engineering use."],
    ["IS 1570-2:2018", "Steels for Common Engineering Purposes — Part 2: Alloy Steels", "Alloy steel grades for engineering applications such as shafts, gears and pressure parts."],
    ["IS 1875:1992", "Carbon Steel Billets, Blooms, Slabs and Bars for Forging", "Semifinished carbon steel product specification for forging stock."],
    ["IS 8500:1991", "Structural Steel — Microalloyed (Medium and High Strength Qualities) — Specification", "Microalloyed structural steel with improved strength and weldability for buildings and bridges."],
    ["IS 12778:2004", "Hot Rolled Parallel Flange Steel Sections for Structural Use — Specification", "Parallel flange beam, column and channel dimensions for efficient structural framing."],
    ["IS 12779:1988", "Rolling and Welding Tolerances for Structural Steel Sections", "Permissible rolling and fabrication tolerances for structural sections."],
    ["IS 12843:1989", "Tolerances for Erection of Steel Structures", "Erection tolerances for columns, beams and framing in steel construction."],
    ["IS 5647:1970", "Specification for Deep Drawn Steel Plates for Pressure Vessels", "Killed steel plate grades for pressure vessel fabrication."],
    ["IS 2002:1992", "Steel Plates for Pressure Vessels for Use at Moderate and Low Temperatures", "Plate grades with impact toughness requirements for low-temperature pressure vessels."],
    ["IS 2041:1995", "Steel Plates for Pressure Vessels for Use at Low Temperatures — Specification", "Low-temperature pressure vessel plate grades with Charpy impact energy requirements."],
  ],
};

const FIRE_AND_BUILDING_SERVICES: Block = {
  category: "construction",
  rows: [
    ["IS 1641:1988", "Code of Practice for Fire Safety of Buildings (General): General Principles of Fire Grading and Classification", "Fire grading of buildings and the general principles behind fire resistance classification."],
    ["IS 1642:1989", "Code of Practice for Fire Safety of Buildings (General): Details of Construction", "Constructional detailing to limit fire spread — walls, floors, openings and shafts."],
    ["IS 1643:1989", "Code of Practice for Fire Safety of Buildings (General): Exposure Hazard", "Separation distances and fire protection for buildings exposed to adjacent fire hazards."],
    ["IS 1644:1988", "Code of Practice for Fire Safety of Buildings (General): Exit Requirements and Personal Hazard", "Exit width, travel distance and stairway requirements for safe evacuation."],
    ["IS 1646:1997", "Code of Practice for Fire Safety of Buildings (General): Electrical Installations", "Fire safety requirements for electrical installations including cables, protection and signage."],
    ["IS 2189:2008", "Selection, Installation and Maintenance of Automatic Fire Detection and Alarm System — Code of Practice", "Detector selection, zoning and alarm system installation for buildings."],
    ["IS 15105:2002", "Design and Installation of Fixed Automatic Sprinkler Fire Extinguishing Systems — Code of Practice", "Sprinkler system design, hydraulic calculations and installation requirements."],
    ["IS 3844:1989", "Code of Practice for Installation and Maintenance of Internal Fire Hydrants and Hose Reels on Premises", "Internal hydrant and hose reel installation practice with pressure and flow requirements."],
    ["IS 636:2018", "Non-Portable Fire Extinguishers — Specification", "Wheeled and trolley-mounted extinguisher construction, capacity and performance testing."],
    ["IS 15397:2003", "Fire Safety — Vocabulary", "Standard fire safety terminology for buildings, products and systems."],
    ["IS 11889:2009", "Fire Protection — Safety Signs and Symbols", "Photoluminescent fire safety signage requirements for buildings."],
    ["IS 3103:1975", "Code of Practice for Industrial Ventilation", "Ventilation design for industrial buildings controlling heat, fume and dust exposure."],
    ["IS 3362:1977", "Code of Practice for Natural Ventilation of Buildings", "Natural ventilation design using openings, stack effect and cross ventilation."],
    ["IS 655:1963", "Specification for Metal Air Ducts", "Galvanised steel duct gauges, joints and fabrication requirements for HVAC systems."],
    ["IS 3614-1:1966", "Code of Practice for Thermal Insulation of Air-Conditioning Installations — Part 1: General", "Insulation selection and application for air-conditioning ducts and equipment."],
    ["IS 4676:1968", "Code of Practice for Thermal Insulation of Cold Storage Installations", "Vapour barrier and insulation build-up for cold stores."],
    ["IS 3148-1:1985", "Code of Practice for Water Supply, Drainage and Sanitation in High Rise Buildings — Part 1: Water Supply", "Pumping, storage and distribution practice for high rise water supply."],
    ["IS 2470-2:1985", "Code of Practice for Installation of Septic Tanks — Part 2: Secondary Treatment and Disposal of Effluent", "Effluent disposal methods including soak pits, dispersion trenches and filters."],
    ["IS 3006:1979", "Code of Practice for Drainage of Buildings in Areas Subject to Flooding", "Flood-proof drainage detailing and backflow prevention for buildings."],
    ["IS 5329:1983", "Code of Practice for Sanitary Pipework Above Ground", "Above-ground sanitary pipework layout, gradients, vent pipes and jointing."],
    ["IS 15242:2002", "Water Supply and Drainage in Buildings — Guidelines", "Consolidated guidance on building water supply and drainage design."],
    ["IS 3025-1:1987", "Methods of Sampling and Test (Physical and Chemical) for Water and Wastewater — Part 1: Sampling", "Sampling procedures for water and wastewater analysis."],
    ["IS 3025-10:1984", "Methods of Sampling and Test for Water and Wastewater — Part 10: Turbidity", "Turbidity measurement by nephelometric and visual methods."],
    ["IS 3025-11:1983", "Methods of Sampling and Test for Water and Wastewater — Part 11: pH Value", "pH determination for potable water and effluents."],
    ["IS 3306:1974", "Code of Practice for Design, Construction and Maintenance of Slow Sand Filters", "Slow sand filter design and operation for rural and municipal water treatment."],
    ["IS 3307:1974", "Code of Practice for Design, Construction and Maintenance of Rapid Gravity Sand Filters", "Rapid gravity filter design with backwash and underdrain systems."],
    ["IS 8413-1:1977", "Requirements for Biological Treatment of Sewage — Part 1: Trickling Filters", "Trickling filter design, media and loading rates for sewage treatment."],
    ["IS 8413-2:1982", "Requirements for Biological Treatment of Sewage — Part 2: Activated Sludge Units", "Activated sludge process design with aeration and sludge recirculation."],
    ["IS 4764:1974", "Requirements for Handling, Storage and Transport of Sewage Sludge", "Sludge handling, dewatering and disposal requirements."],
    ["IS 10313:1982", "Requirements for Settling Tanks (Clarifiers) in Sewage Treatment Plants", "Clarifier design with surface loading and detention criteria."],
    ["IS 4963:1987", "Recommendations for Buildings and Facilities for Physically Handicapped — Requirements", "Ramp gradients, handrails, toilets and circulation requirements for accessible buildings."],
  ],
};

const TALL_BUILDINGS_AND_SPECIAL: Block = {
  category: "construction",
  rows: [
    ["IS 15917:2011", "Design of Steel Structures in Tall Buildings — Code of Practice", "Load combinations, drift limits and ductile detailing for steel tall buildings."],
    ["IS 16700:2023", "Criteria for Structural Safety of Tall Concrete Buildings", "Structural safety criteria for tall concrete buildings including wind tunnel and seismic verification."],
    ["IS 16133:2018", "Bamboo Based Structures — Code of Practice", "Design and construction of bamboo structures for buildings and sheds."],
    ["IS 15827:2010", "Design and Construction of Bamboo Structures — Guidelines", "Structural use of bamboo including treatment, joints and durability."],
    ["IS 11447:1985", "Code of Practice for Construction of Cased Cast-In-Situ RCC Chimneys", "Construction practice for industrial chimneys with reinforced concrete shells."],
    ["IS 13094:1992", "Code of Practice for Design and Construction of Diaphragm Walls", "Design and construction guidance for diaphragm walls in deep excavations."],
    ["IS 12820:1989", "Code of Practice for Construction of RCC Shell Roofs and Folded Plates", "Design and construction practice for RC shell and folded plate roofs."],
    ["IS 2110:1980", "Code of Practice for In-Situ Construction of RCC Shell Roofs", "Formwork, concreting and curing requirements for RC shell roofs."],
    ["IS 4552:1968", "Code of Practice for Construction of Brick Masonry with Fly Ash Mortar", "Brick masonry practice using fly ash based mortars."],
    ["IS 1663:1972", "Code of Practice for Design, Construction and Maintenance of Mass Masonry Dams", "Design and construction practice for masonry and concrete gravity dams."],
    ["IS 4997:1968", "Criteria for Design of RCC Staging for Overhead Water Tanks", "Staging design criteria for overhead tanks including wind and seismic effects."],
    ["IS 3370-3:2021", "Concrete Structures for Retaining Aqueous Liquids — Part 3: Prestressed Concrete Structures", "Prestressed concrete provisions for liquid retaining structures."],
    ["IS 3480:2019", "Sanitary Fittings for Buildings — Specification", "Tap, waste coupling and fitting requirements for building sanitary installations."],
    ["IS 1712:1983", "Code of Practice for Prestressed Concrete Works", "Workmanship, prestressing operations and grouting practice for prestressed concrete."],
    ["IS 14536:1998", "Code of Practice for Waterproofing of Basements", "Waterproofing systems for basements including drainage and membrane practice."],
    ["IS 5872:1970", "Code of Practice for Construction of Buildings in Coronary Climes", "Construction practice for buildings in coastal and saline environments."],
    ["IS 15037:2002", "Soil and Groundwater Investigation for Remediation of Contaminated Sites — Guidelines", "Investigation guidance for contaminated sites prior to redevelopment."],
    ["IS 15697:2006", "Night Soil Treatment Plants — Guidelines", "Design and operation of night soil treatment plants for unsewered areas."],
    ["IS 10037-1:1981", "Requirements for Sludge Digestion and Disposal — Part 1: Design and Construction of Sludge Digesters", "Anaerobic sludge digester design and construction requirements."],
    ["IS 10037-2:1981", "Requirements for Sludge Digestion and Disposal — Part 2: Disposal of Sludge", "Sludge dewatering, drying beds and disposal practice."],
    ["IS 16242:2014", "Interior Drinking Water Dispensers — Specification", "Water dispenser materials, filtration and hygiene requirements for public premises."],
    ["IS 13496-1:1992", "Waterproofing of Roofs — Guidelines", "Roof waterproofing methods using bitumen felt, membranes and coatings."],
    ["IS 4365:1967", "Code of Practice for Design and Construction of Ramps", "Ramp geometry, gradients and surface treatment for vehicles and pedestrians."],
    ["IS 13668:1993", "Conveyor Safety — Code of Practice", "Safety guarding, emergency stops and inspection practice for belt conveyors."],
    ["IS 3177:1999", "Code of Practice for Electric Overhead Travelling Cranes and Gantry Cranes", "Structural and mechanical design practice for EOT and gantry cranes."],
    ["IS 807:2006", "Design, Erection and Testing of Cranes and Hoists — Code of Practice", "Design load classes, structural requirements and testing of cranes and hoists."],
    ["IS 13834-1:1993", "Electric Wire Rope Hoists — Part 1: Safety Requirements", "Safety requirements for electric wire rope hoists used in industrial handling."],
    ["IS 15419:2003", "Escalators and Moving Walks — Code of Practice", "Escalator installation, step safety and maintenance practice for public buildings."],
    ["IS 14665-1:2000", "Electric Traction Lifts — Part 1: Outline Dimensions", "Lift car, shaft and machine room dimension standards for electric traction lifts."],
    ["IS 14665-4:2000", "Electric Traction Lifts — Part 4: Safety Requirements", "Safety provisions for lift doors, governors and emergency operation."],
    ["IS 4918:2019", "Code of Practice for Design of Lift Shafts in Buildings", "Lift shaft, machine room and pit design requirements in buildings."],
  ],
};

export const STD_WAVE9 = buildBlocks(
  STRUCTURAL_STEEL,
  FIRE_AND_BUILDING_SERVICES,
  TALL_BUILDINGS_AND_SPECIAL,
);
