/* Extra catalogue wave 8 — construction & civil engineering (cement, concrete,
 * aggregates, masonry, timber, finishes, pipes, roads, geotechnics). */
import { buildBlocks, type Block } from "@/db/seed-kit";

const CEMENT_QCO = "Cement (Quality Control) Order";
const WOOD_QCO = "Wood and Wood Products (Quality Control) Order";
const CEMENT_AND_CONCRETE: Block = {
  category: "construction",
  qco: CEMENT_QCO,
  rows: [
    ["IS 455:2015", "Portland Slag Cement — Specification", "Blast furnace slag cement with 35–65% slag — lower heat of hydration, better sulphate resistance and suitability for mass concrete and marine works.", "M", { editions: 5, keywords: ["portland slag cement", "psc", "slag cement", "सीमेंट"], related: ["IS 269:2015", "IS 12089:1987"] }],
    ["IS 8041:1990", "Rapid Hardening Portland Cement — Specification", "Cement that develops high early strength for precast units, cold-weather concreting, road repairs and quick-turnaround formwork.", "M", { editions: 3 }],
    ["IS 8043:1991", "Hydrophobic Portland Cement — Specification", "Water-repellent cement for long storage and humid sites where ordinary cement would deteriorate before use.", "M", { editions: 3 }],
    ["IS 4031-2:1999", "Methods of Physical Tests for Hydraulic Cement — Part 2: Determination of Fineness by Specific Surface (Blaine)", "Blaine air-permeability method for specific surface area of cement — the fineness measure used in licence testing."],
    ["IS 4031-3:1988", "Methods of Physical Tests for Hydraulic Cement — Part 3: Determination of Soundness", "Le-Chatelier and autoclave procedures to detect unsound cement prone to delayed expansion."],
    ["IS 4031-13:1988", "Methods of Physical Tests for Hydraulic Cement — Part 13: Determination of Water Retention of Mortars", "Water-retention measurement for masonry mortars and plasters."],
    ["IS 4031-14:1989", "Methods of Physical Tests for Hydraulic Cement — Part 14: Determination of Strength of Masonry Cement", "Compressive strength testing of masonry cement mortars."],
    ["IS 4031-15:1991", "Methods of Physical Tests for Hydraulic Cement — Part 15: Determination of Fineness by Air Permeability", "Air-permeability determination of cement fineness for routine plant control."],
    ["IS 6909:1990", "Supersulphated Cement — Specification", "Supersulphated cement for severe sulphate and chloride exposure such as marine and sewerage works."],
    ["IS 12600:1989", "Low Heat Portland Cement — Specification", "Low-heat cement for mass concrete dams and thick rafts where thermal cracking must be controlled."],
    ["IS 3812-2:2013", "Pulverized Fuel Ash — Part 2: For Use as Admixture in Cement Mortar and Concrete", "Fly ash used directly as a concrete admixture — fineness, lime reactivity and uniformity clauses."],
    ["IS 12089:1987", "Specification for Granulated Slag for the Manufacture of Portland Slag Cement", "Quality of granulated blast furnace slag acceptable for manufacturing PSC."],
    ["IS 10262:2019", "Concrete Mix Proportioning — Guidelines", "DoE-based mix design procedure with water-cement ratio tables for exposure classes and target mean strength.", "V", { editions: 3, keywords: ["mix design", "concrete mix", "water cement ratio", "कंक्रीट"], related: ["IS 456:2000"] }],
    ["IS 1199-1:2018", "Fresh Concrete — Methods of Sampling, Testing and Analysis", "Sampling of fresh concrete and determination of workability including slump, compaction factor and Vee-Bee time."],
    ["IS 516:2021", "Hardened Concrete — Methods of Test", "Compressive, flexural and split-tensile strength testing of hardened concrete specimens.", "V", { editions: 6, keywords: ["concrete cube", "compressive strength", "flexural", "कंक्रीट परीक्षण"], related: ["IS 456:2000"] }],
    ["IS 5816:1999", "Splitting Tensile Strength of Concrete — Method of Test", "Indirect tensile strength determination by splitting cylinder or cube specimens."],
    ["IS 13311-1:1992", "Non-Destructive Testing of Concrete — Part 1: Ultrasonic Pulse Velocity", "UPV method for assessing homogeneity and quality of in-situ concrete."],
    ["IS 13311-2:1992", "Non-Destructive Testing of Concrete — Part 2: Rebound Hammer", "Rebound hammer procedure for surface hardness-based in-situ strength indication."],
    ["IS 3085:1965", "Method of Test for Permeability of Cement Mortar and Concrete", "Water permeability measurement for concrete durability assessment."],
    ["IS 3370-4:2021", "Concrete Structures for Retaining Aqueous Liquids — Part 4: Design Tables", "Design aids and tables for reinforced concrete liquid-retaining members."],
    ["IS 5525:1969", "Recommendations for Detailing of Reinforcement in Reinforced Concrete Work", "Detailing recommendations for bars, laps, cover, curtailment and openings in RC elements."],
  ],
};

const AGGREGATES_AND_MASONRY: Block = {
  category: "construction",
  rows: [
    ["IS 2386-2:1963", "Methods of Test for Aggregates for Concrete — Part 2: Estimation of Deleterious Materials", "Clay lumps, coal, mica, shale and organic impurity estimation in aggregates."],
    ["IS 2386-5:1963", "Methods of Test for Aggregates for Concrete — Part 5: Soundness", "Sodium and magnesium sulphate soundness testing for weathering resistance."],
    ["IS 2386-8:1963", "Methods of Test for Aggregates for Concrete — Part 8: Petrographic Examination", "Petrographic assessment of aggregate suitability for concrete."],
    ["IS 1542:1992", "Sand for Plaster — Specification", "Grading and quality limits for sand used in internal and external plastering."],
    ["IS 2116:1980", "Sand for Masonry Mortars — Specification", "Sand requirements for cement and lime masonry mortars."],
    ["IS 1077:2023", "Common Burnt Clay Building Bricks — Specification", "Classification of burnt clay bricks into classes by compressive strength, water absorption and efflorescence.", "V", { editions: 6, keywords: ["brick", "clay brick", "ईंट", "masonry"], related: ["IS 3495-1:2019"] }],
    ["IS 3495-3:2019", "Methods of Tests of Burnt Clay Building Bricks — Part 3: Determination of Efflorescence", "Efflorescence rating of bricks on drying and wetting cycles."],
    ["IS 3495-4:2019", "Methods of Tests of Burnt Clay Building Bricks — Part 4: Determination of Warpage", "Warpage measurement for clay building bricks."],
    ["IS 12894:2002", "Pulverized Fuel Ash-Lime Bricks — Specification", "Fly ash-lime bricks for masonry with strength classes and durability clauses.", "V", { editions: 2, keywords: ["fly ash brick", "lime brick", "ईंट"] }],
    ["IS 13757:1993", "Burnt Clay Fly Ash Building Bricks — Specification", "Clay bricks incorporating fly ash — classification and testing requirements."],
    ["IS 2185-2:1983", "Concrete Masonry Units — Part 2: Hollow and Solid Lightweight Concrete Blocks", "Lightweight aggregate concrete blocks for partition and filler walls."],
    ["IS 2572:2005", "Construction of Hollow and Solid Concrete Block Masonry — Code of Practice", "Workmanship, mortar, bonding and curing practice for concrete block masonry."],
    ["IS 6061-1:1971", "Code of Practice for Construction of Stone Masonry — Part 1: Rubble Stone Masonry", "Rubble stone masonry construction practice including bond stones and mortar joints."],
    ["IS 1121-1:1974", "Methods of Test for Determination of Strength Properties of Natural Building Stones — Part 1: Compressive Strength", "Compressive strength testing of building stone specimens."],
    ["IS 1124:1974", "Method of Test for Determination of Water Absorption, Apparent Specific Gravity and Porosity of Natural Building Stones", "Water absorption and porosity determination for stone used in construction."],
    ["IS 2095-1:2011", "Gypsum Plaster Boards — Part 1: Specification", "Gypsum board types, dimensions, flexural strength and surface hardness for drywall construction."],
    ["IS 2548-1:1996", "Gypsum Plaster Board for Walls and Ceilings — Specification", "Plaster board specification covering thickness, strength and fire behaviour."],
    ["IS 12679:1989", "Cellulose Fibre Insulating Board — Specification", "Fibre insulating boards for thermal insulation of roofs and walls."],
  ],
};

const TIMBER_AND_BOARDS: Block = {
  category: "construction",
  qco: WOOD_QCO,
  rows: [
    ["IS 287:1993", "Recommendations for Maximum Permissible Moisture Content of Timber Used for Different Purposes", "Moisture content limits for structural, joinery, furniture and packing timber in different climatic zones."],
    ["IS 883:1994", "Design of Structural Timber in Building — Code of Practice", "Permissible stresses, design of beams, columns and joints in structural timber."],
    ["IS 3629:1986", "Structural Timber in Building — Specification", "Grade requirements, defects and moisture limits for structural timber."],
    ["IS 4014-1:1967", "Code of Practice for Preservation of Timber — Part 1: General", "Preservative treatment selection, methods of application and handling of treated timber."],
    ["IS 303:1989", "Plywood for General Purposes — Specification", "Plywood grades, glue lines, bonding durability and moisture movement for interior use.", "V", { editions: 4, keywords: ["plywood", "ply", "लकड़ी"] }],
    ["IS 1328:1996", "Veneered Decorative Plywood — Specification", "Decorative veneer-faced plywood for panelling and furniture, with veneer and core clauses."],
    ["IS 1895:2015", "Wood Wool Board — Specification", "Cement-bonded wood wool boards for thermal and acoustic insulation."],
    ["IS 3097:2006", "Veneered Particle Boards — Specification", "Decorative veneered particle board requirements for furniture manufacture."],
    ["IS 12406:2022", "Medium Density Fibre Boards for General Purposes — Specification", "MDF grades, screw-holding strength, swelling and formaldehyde emission requirements.", "Q:Wood Based Boards (Quality Control) Order"],
    ["IS 3478:2022", "Particle Board for Wood-Based Panels — Specification", "Particle board specification for interior and exterior panel applications."],
    ["IS 4873:2007", "Methods of Test for Plywood and Other Wood-Based Panels", "Testing procedures for plywood bond quality, glue shear strength and moisture resistance."],
    ["IS 1734-1:1983", "Methods of Test for Plywood — Part 1: Determination of Density and Moisture Content", "Density and moisture content determination for plywood test specimens."],
    ["IS 1734-5:1983", "Methods of Test for Plywood — Part 5: Determination of Glue Shear Strength", "Dry and wet glue shear strength testing of plywood glue lines."],
    ["IS 2553-2:2018", "Safety Glass — Part 2: Laminated Glass", "Laminated safety glass interlayer requirements and impact durability."],
    ["IS 14945:2001", "Frameless Glass Doors and Windows — Specification", "Glass thickness, fittings and safety requirements for frameless glass installations."],
    ["IS 5437:1994", "Textile Reinforced Plastic (FRP) Products — Specification", "FRP sheets and products for roofing, cladding and chemical-resistant applications."],
    ["IS 4393:1981", "Code of Practice for Construction of Bamboo Jetties and Docks", "Bamboo construction guidance for temporary jetties, docks and river structures."],
    ["IS 9096:2006", "Preservation of Bamboo for Structural Purposes — Code of Practice", "Treatment of bamboo with preservatives for structural and scaffolding use."],
  ],
};

const FINISHES_AND_FIXTURES: Block = {
  category: "construction",
  rows: [
    ["IS 15622:2019", "Ceramic Tiles — Specification (ISO 13006 Based)", "Ceramic floor and wall tiles classification by water absorption, dimensions, strength and surface quality.", "V", { editions: 2, keywords: ["ceramic tile", "floor tile", "टाइल"] }],
    ["IS 13630-1:2006", "Ceramic Tiles — Methods of Test — Part 1: Sampling and Basis for Acceptance", "Sampling plan and acceptance basis for ceramic tile consignments."],
    ["IS 13630-8:2006", "Ceramic Tiles — Methods of Test — Part 8: Determination of Chemical Resistance", "Chemical resistance classification of glazed and unglazed tiles."],
    ["IS 4457:2007", "Ceramic Unglazed Stoneware Tiles — Specification", "Unglazed stoneware tiles for industrial flooring and heavy-duty areas."],
    ["IS 13801:1993", "Chequered Cement Concrete Flooring Tiles — Specification", "Chequered concrete tiles for ramps, stairways and slip-resistant flooring."],
    ["IS 777:1988", "Glazed Earthenware Tiles — Specification", "Glazed earthenware tiles for wall cladding and decorative applications."],
    ["IS 2556-1:1994", "Vitreous China Sanitary Appliances — Part 1: Wash Basins", "Wash basin sizes, glazing quality and strength requirements.", "Q:Sanitaryware (Quality Control) Order"],
    ["IS 2556-2:1994", "Vitreous China Sanitary Appliances — Part 2: Water Closets", "Water closet types, flush volume, trap seal and seat requirements.", "Q:Sanitaryware (Quality Control) Order"],
    ["IS 2556-3:1994", "Vitreous China Sanitary Appliances — Part 3: Squatting Pans", "Squatting pan pan type, dimension and hydraulic requirements.", "Q:Sanitaryware (Quality Control) Order"],
    ["IS 2556-4:1994", "Vitreous China Sanitary Appliances — Part 4: Urinals", "Urinal types and flushing requirements for public and commercial installations."],
    ["IS 771-1:1985", "Specification for Flush Pipes — Part 1: Cast Iron Flush Pipes", "Cast iron flush pipe dimensions and jointing requirements."],
    ["IS 651:2007", "Glazed Stoneware Pipes and Fittings — Specification", "Stoneware pipes for drainage and sewerage with strength and water-tightness tests."],
    ["IS 428:2000", "Dry Distemper, Oil-Bound and Acrylic Emulsion — Specification", "Water-based distemper and emulsion paint requirements for interior walls."],
    ["IS 2395-1:1994", "Code of Practice for Painting of Concrete, Masonry and Plaster Surfaces", "Surface preparation, priming and coating schedules for masonry and plaster."],
    ["IS 2074:1992", "Ready Mixed Paint, Air Drying, Red Oxide — Specification", "Red oxide priming paint for ferrous and wooden surfaces."],
    ["IS 5410:1992", "Cement Paint — Specification", "Cement-based paint for exterior masonry, including waterproof and snowcem type paints."],
    ["IS 109:2012", "Ready Mixed Paint, Brushing, Exterior — Specification", "Exterior brushing paint composition and performance requirements."],
    ["IS 6278:1971", "Code of Practice for White Washing and Colour Washing", "Lime wash and colour wash application practice for buildings."],
    ["IS 2645:2003", "Integral Waterproofing Compounds — Specification", "Waterproofing admixtures for cement mortar and concrete, with performance tests."],
    ["IS 3067:1986", "Code of Practice for General Design Details and Preparatory Work for Damp-Proofing and Water-Proofing of Buildings", "Design details for damp-proofing courses, plinths and waterproofing systems."],
    ["IS 13496:1992", "Code of Practice for Water-Proofing of Roofs Using Bitumen Felt", "Bitumen felt roofing waterproofing practice including laps and treatment details."],
    ["IS 1580:1991", "Bituminous Compounds for Waterproofing and Damp-Proofing — Specification", "Bituminous compound grades for waterproofing and damp-proofing applications."],
    ["IS 3384:1986", "Specification for Rubber-Based Adhesives for Tile Fixing", "Rubber-based tile adhesive requirements for fixing ceramic tiles to floors and walls."],
    ["IS 15477:2019", "Adhesives for Tiles — Specification", "Tile adhesive classes by tensile adhesion strength for interior, exterior and wet areas."],
  ],
};

const PIPES_ROADS_GEOTECH: Block = {
  category: "construction",
  rows: [
    ["IS 458:2021", "Precast Concrete Pipes (with and without Reinforcement) — Specification", "Concrete pipe classes NP1 to NP4 for drainage and culverts with hydrostatic and three-edge bearing tests."],
    ["IS 784:2018", "Prestressed Concrete Pipes (Including Fittings) — Specification", "PSC pipes for water supply and pressure mains with pipe class and pressure ratings."],
    ["IS 3597:1985", "Method of Test for Concrete Pipes", "Hydrostatic, three-edge bearing and absorption tests for concrete pipes."],
    ["IS 7319:1996", "Fittings for Concrete Pipes — Specification", "Collars, bends and junction fittings for precast concrete pipeline systems."],
    ["IS 1729:2015", "Cast Iron Manhole Covers and Frames — Specification", "Manhole cover classes by traffic loading with dimensions and load tests."],
    ["IS 1230:2021", "Cast Iron Poles, Brackets and Stay Sets for Overhead Lines — Specification", "Cast iron line hardware specification for distribution poles and stays."],
    ["IS 1742:2022", "Code of Practice for Building Drainage", "Sanitary drainage layout, gradients, ventilation and inspection chamber practice for buildings."],
    ["IS 3114:1993", "Code of Practice for Lay-Out of Drainage and Sanitary Fittings in Buildings", "Layout and fixing heights of sanitary fittings and drainage lines."],
    ["IS 2720-1:1983", "Methods of Test for Soils — Part 1: Preparation of Dry Soil Samples for Various Tests", "Dry soil sample preparation procedures for the IS 2720 test series."],
    ["IS 2720-3-1:1980", "Methods of Test for Soils — Part 3: Determination of Specific Gravity of Fine-Grained Soils", "Specific gravity determination of fine-grained soils by density bottle and pycnometer."],
    ["IS 2720-8:1983", "Methods of Test for Soils — Part 8: Determination of Water Content and Dry Density Relationship Using Heavy Compaction", "Modified Proctor compaction test for highway and runway earthworks."],
    ["IS 2720-11:1993", "Methods of Test for Soils — Part 11: Determination of Shear Strength Parameters (UU, CU, CD)", "Triaxial shear testing procedures for soil shear strength parameters."],
    ["IS 2720-13:1986", "Methods of Test for Soils — Part 13: Direct Shear Test", "Direct shear box testing to obtain cohesion and angle of internal friction."],
    ["IS 2720-16:1987", "Methods of Test for Soils — Part 16: Laboratory Determination of CBR", "California Bearing Ratio testing for pavement subgrade and sub-base design."],
    ["IS 2720-31:1990", "Methods of Test for Soils — Part 31: Field Determination of California Bearing Ratio", "Field CBR testing procedure for in-situ subgrade evaluation."],
    ["IS 1892:2021", "Code of Practice for Subsurface Investigation for Foundations", "Boring, sampling and reporting requirements for foundation investigation."],
    ["IS 1888:1982", "Method of Load Test on Soils", "Plate load test procedure for in-situ bearing capacity and settlement."],
    ["IS 1904:1986", "Code of Practice for Design and Construction of Foundations in Soils — General Requirements", "General foundation design requirements, depth of foundation and allowable pressure."],
    ["IS 2911-1-1:2010", "Design and Construction of Pile Foundations — Part 1: Concrete Piles — Section 1: Driven Cast In-Situ Concrete Piles", "Design and construction of driven cast in-situ concrete piles."],
    ["IS 2911-1-3:2010", "Design and Construction of Pile Foundations — Part 1: Concrete Piles — Section 3: Driven Precast Concrete Piles", "Design and installation of driven precast concrete piles."],
    ["IS 2911-3:1980", "Code of Practice for Design and Construction of Pile Foundations — Part 3: Under-Reamed Piles", "Under-reamed pile design for expansive soils and black cotton strata."],
    ["IS 2950-1:1981", "Code of Practice for Design and Construction of Raft Foundations — Part 1: General", "Raft foundation design and construction for weak or variable soils."],
    ["IS 9451:1994", "Guidelines for Design and Construction of Foundation in Expansive Soils", "Foundation solutions in swelling clays, including under-reamed piles and CNS layers."],
    ["IS 2720-28:1974", "Methods of Test for Soils — Part 28: Determination of Dry Density of Soils In-Place (Sand Replacement Method)", "In-situ dry density determination by the sand replacement method."],
    ["IS 2720-29:1975", "Methods of Test for Soils — Part 29: Determination of Dry Density of Soils In-Place (Core Cutter Method)", "In-situ dry density determination by core cutter for fine-grained soils."],
    ["IS 14621:1998", "Geotextiles — Sampling and Preparation of Test Specimens", "Sampling and specimen preparation guidance for geotextile testing."],
  ],
};

const CONSTRUCTION_SUPPLEMENT: Block = {
  category: "construction",
  rows: [
    ["IS 650:1991", "Standard Sand for Testing of Cement — Specification", "Graded natural sand from the Ennore deposits used as the reference material for cement mortar cube strength testing."],
    ["IS 2131:1981", "Method for Standard Penetration Test for Soils", "SPT procedure for in-situ penetration resistance, the primary field index for foundation design.", "V", { related: ["IS 1892:2021"] }],
    ["IS 2132:1986", "Code of Practice for Thin-Walled Tube Sampling of Soils", "Undisturbed sampling practice with thin-walled tubes for laboratory strength testing."],
    ["IS 6403:1981", "Code of Practice for Determination of Bearing Capacity of Shallow Foundations", "Bearing capacity computation from shear strength parameters with shape, depth and inclination factors."],
    ["IS 8009-1:1976", "Code of Practice for Calculation of Settlements of Foundations — Part 1: Shallow Foundations Subjected to Symmetrical Static Vertical Loads", "Elastic and consolidation settlement computation for shallow foundations."],
    ["IS 4968-2:1976", "Method of Test for Determination of Bearing Capacity of Soil by Dynamic Method — Part 2: Test with Dynamic Cone", "Dynamic cone penetration testing for rapid bearing capacity estimation."],
    ["IS 5249:1992", "Method of Test for Determination of Dynamic Properties of Soil", "Field and laboratory determination of shear modulus and damping for machine foundation design."],
    ["IS 12070:1987", "Code of Practice for Design and Construction of Shallow Foundations on Rock", "Allowable pressures and construction practice for footings founded on rock."],
    ["IS 2911-2:1980", "Code of Practice for Design and Construction of Pile Foundations — Part 2: Timber Piles", "Timber pile design, preservation and driving requirements."],
    ["IS 2911-4:1985", "Code of Practice for Design and Construction of Pile Foundations — Part 4: Load Test on Piles", "Initial and routine pile load test procedures with acceptance settlement criteria."],
    ["IS 15284-1:2003", "Design and Construction for Ground Improvement — Guidelines — Part 1: Stone Columns", "Stone column design for improving bearing capacity and reducing settlement in soft soils."],
    ["IS 2720-6:1972", "Methods of Test for Soils — Part 6: Determination of Shrinkage Factors", "Shrinkage limit and shrinkage ratio determination for expansive soils."],
    ["IS 2720-15:1986", "Methods of Test for Soils — Part 15: Determination of Consolidation Properties", "Oedometer consolidation testing for compression index and coefficient of consolidation."],
    ["IS 2720-17:1986", "Methods of Test for Soils — Part 17: Laboratory Determination of Permeability", "Constant and falling head permeability testing of soils."],
    ["IS 2720-26:1987", "Methods of Test for Soils — Part 26: Determination of pH Value", "Soil pH determination by electrometric and colorimetric methods."],
    ["IS 2720-27:1977", "Methods of Test for Soils — Part 27: Determination of Total Soluble Sulphates", "Sulphate content determination for assessing soil aggressivity to foundations and concrete."],
    ["IS 7861-1:1975", "Code of Practice for Extreme Weather Concreting — Part 1: Recommended Practice for Hot Weather Concreting", "Concreting practice in hot weather — temperature limits, chilling, curing and admixture use."],
    ["IS 7861-2:1975", "Code of Practice for Extreme Weather Concreting — Part 2: Recommended Practice for Cold Weather Concreting", "Concreting practice in cold weather including heating, insulation and protection of fresh concrete."],
    ["IS 9013:1978", "Method of Curing of Concrete", "Curing methods and durations to achieve the specified strength and durability."],
    ["IS 3558:1983", "Code of Practice for Use of Immersion Vibrator for Consolidating Concrete", "Vibrator selection, spacing and duration for proper compaction of concrete."],
    ["IS 6461-1:1972", "Glossary of Terms Relating to Cement Concrete — Part 1: Materials", "Standard terminology for cement, aggregates, water and admixtures used in concrete."],
    ["IS 6461-4:1972", "Glossary of Terms Relating to Cement Concrete — Part 4: Types of Concrete", "Terminology for plain, reinforced, prestressed, lightweight and special concretes."],
    ["IS 4925:2004", "Concrete Batching and Mixing Plant — Specification", "Requirements for batching accuracy and mixing efficiency of concrete plants."],
    ["IS 1661:1972", "Code of Practice for Application of Cement and Cement-Lime Plaster Finishes", "Plaster mixes, thicknesses and application practice for internal and external rendering."],
    ["IS 2571:1970", "Code of Practice for Laying of Cement Concrete Floors", "Sub-base preparation, concreting and finishing practice for cement concrete floors."],
    ["IS 2338-1:1967", "Code of Practice for Finishing of Walls — Part 1: Cement Plaster (Internal)", "Internal cement plaster schedules, surface preparation and finishing requirements."],
    ["IS 2402:1963", "Code of Practice for External Facings and Rendering", "External rendering mixes and detailing for weather protection of walls."],
    ["IS 1122:1974", "Method of Test for True Specific Gravity of Natural Building Stones", "True specific gravity determination of building stone by the pycnometer method."],
    ["IS 2065:1983", "Code of Practice for Water Supply in Buildings", "Storage, distribution and fixture requirements for water supply installations in buildings."],
    ["IS 14687:1999", "Falsework for Concrete Structures — Guidelines", "Design, erection and striking of falsework and formwork support systems."],
    ["IS 875-1:1987", "Code of Practice for Design Loads (Other Than Earthquake) for Buildings and Structures — Part 1: Dead Loads", "Unit weights of building materials and dead load computation for design.", "V", { keywords: ["dead load", "design loads", "unit weight", "structural design"] }],
    ["IS 875-2:1987", "Code of Practice for Design Loads (Other Than Earthquake) — Part 2: Imposed Loads", "Floor, roof and partition imposed loads for different occupancies."],
    ["IS 875-3:2015", "Code of Practice for Design Loads (Other Than Earthquake) — Part 3: Wind Loads", "Basic wind speed, terrain categories, pressure coefficients and dynamic response for structures.", "V", { editions: 3, keywords: ["wind load", "wind speed", "structural design"] }],
    ["IS 875-4:1987", "Code of Practice for Design Loads (Other Than Earthquake) — Part 4: Snow Loads", "Snow load estimation for roofs in Himalayan and other snow-prone regions."],
    ["IS 1893-2:2014", "Criteria for Earthquake Resistant Design of Structures — Part 2: Liquid Retaining Tanks", "Seismic design criteria for elevated and ground-supported liquid storage tanks."],
    ["IS 1893-3:2014", "Criteria for Earthquake Resistant Design of Structures — Part 3: Bridges and Retaining Walls", "Seismic forces and detailing for bridges, culverts and retaining structures."],
    ["IS 1893-4:2015", "Criteria for Earthquake Resistant Design of Structures — Part 4: Industrial Structures", "Seismic design of industrial buildings, stacks, silos and machine foundations."],
    ["IS 13935:2022", "Seismic Assessment and Retrofitting of Buildings — Guidelines", "Assessment, repair and seismic strengthening techniques for existing masonry and RC buildings."],
    ["IS 1626-1:1994", "Asbestos Cement Building Boards — Specification", "Asbestos cement flat sheets for partitions, ceilings and cladding with strength and fire clauses."],
    ["IS 513:2016", "Cold Reduced Carbon Steel Sheets and Strips — Specification", "Grades of cold reduced steel sheet for forming and general engineering use, with mechanical property tables."],
    ["IS 14246:1995", "Continuously Pre-Painted Galvanised Steel Sheets and Coils — Specification", "Pre-painted galvanised sheet for roofing and cladding with coating mass and adhesion requirements."],
    ["IS 3809:1979", "Fire Resistance Test of Structures", "Furnace test method for rating the fire resistance of structural elements and assemblies."],
    ["IS 808:1989", "Dimensions for Hot Rolled Steel Beam, Column, Channel and Angle Sections", "Standard rolled section dimensions, weights and properties used in structural design."],
    ["IS 1367-1:2002", "Technical Supply Conditions for Threaded Steel Fasteners — Part 1: General Requirements", "General requirements for bolts, screws and nuts including thread and tolerance classes.", "Q:Steel & Steel Products (Quality Control) Order"],
    ["IS 4000:1992", "Code of Practice for High Strength Bolts in Steel Structures", "Design and installation of high strength friction grip bolt connections."],
    ["IS 15916:2010", "Building Design and Erection Using Prefabricated Concrete — Code of Practice", "Design, production, transport and erection practice for prefabricated concrete buildings."],
  ],
};

export const STD_WAVE8 = buildBlocks(
  CEMENT_AND_CONCRETE,
  AGGREGATES_AND_MASONRY,
  TIMBER_AND_BOARDS,
  FINISHES_AND_FIXTURES,
  PIPES_ROADS_GEOTECH,
  CONSTRUCTION_SUPPLEMENT,
);
