/* ------------------------------------------------------------------------
 * seed-labs — the full testing network.
 *
 * Every row is [name, city, state, kind, capabilities, phone, email] where
 * `capabilities` is a comma-separated list from the eight testing categories
 * used across the app (construction, mechanical, electrical, electronics,
 * food, plastics, consumer, hallmark). The `standards` tested are derived from
 * those capabilities unless the row supplies its own list as an eighth field.
 *
 * Contact details are illustrative demo data (same convention as the original
 * seed) and must be replaced with the official BIS lab directory before any
 * real deployment.
 * ---------------------------------------------------------------------- */
import type { SeedLab } from "@/db/seed-kit";

export type LabRow = [
  name: string,
  city: string,
  state: string,
  kind: "BIS Laboratory" | "Recognized Laboratory" | "AHC",
  capabilities: string,
  phone: string,
  email: string,
  standards?: string[],
];

const DEMO_STANDARDS: Record<string, string[]> = {
  construction: ["IS 456:2000", "IS 269:2015", "IS 1786:2008", "IS 383:2016"],
  mechanical: ["IS 2062:2011", "IS 1239-1:2004", "IS 1030:1998", "IS 276:2000"],
  electrical: ["IS 694:2010", "IS 1554-1:1988", "IS 1293:2019", "IS 3854:1997"],
  electronics: ["IS 13252-1:2010", "IS 616:2017", "IS 16046:2018", "IS 16333-3:2022"],
  food: ["IS 10500:2012", "IS 14543:2016", "IS 1165:2022", "IS 3025-1:1987"],
  plastics: ["IS 4984:2016", "IS 4985:2021", "IS 2508:2016", "IS 13360-2-1:1994"],
  consumer: ["IS 2347:2017", "IS 4246:2002", "IS 9873-3:2017", "IS 2925:1984"],
  hallmark: ["IS 1417:2016", "IS 2112:2014"],
};

export function buildLabs(rows: LabRow[]): SeedLab[] {
  return rows.map(([name, city, state, kind, capabilities, phone, email, standards]) => {
    const caps = capabilities.split(",").map((c) => c.trim()).filter(Boolean);
    const derived = standards ?? [...new Set(caps.flatMap((c) => DEMO_STANDARDS[c] ?? []))];
    return { name, city, state, kind, capabilities: caps, standards: derived, phone, email };
  });
}

/* ------------------------- BIS laboratory network ------------------------- */

export const BIS_LABS: LabRow[] = [
  ["BIS Central Laboratory, Sahibabad", "Ghaziabad", "Uttar Pradesh", "BIS Laboratory", "construction,mechanical,electrical,electronics,food,plastics,consumer", "0120-277-1500", "cl@bis.gov.in"],
  ["BIS Northern Regional Laboratory, New Delhi", "New Delhi", "Delhi", "BIS Laboratory", "electrical,electronics,mechanical,consumer", "011-2323-0001", "nrl@bis.gov.in"],
  ["BIS Western Regional Laboratory, Mumbai", "Mumbai", "Maharashtra", "BIS Laboratory", "construction,plastics,mechanical,electrical", "022-2832-0002", "wrl@bis.gov.in"],
  ["BIS Southern Regional Laboratory, Chennai", "Chennai", "Tamil Nadu", "BIS Laboratory", "food,electrical,consumer,construction", "044-2254-0003", "srl@bis.gov.in"],
  ["BIS Eastern Regional Laboratory, Kolkata", "Kolkata", "West Bengal", "BIS Laboratory", "construction,mechanical,food,consumer", "033-2486-0004", "erl@bis.gov.in"],
  ["BIS Laboratory, Mohali", "Mohali", "Punjab", "BIS Laboratory", "construction,mechanical,food", "0172-222-0005", "labs.mohali@bis.gov.in"],
  ["BIS Laboratory, Jaipur", "Jaipur", "Rajasthan", "BIS Laboratory", "construction,consumer,hallmark", "0141-222-0006", "labs.jaipur@bis.gov.in"],
  ["BIS Laboratory, Ahmedabad", "Ahmedabad", "Gujarat", "BIS Laboratory", "plastics,construction,electrical", "079-222-0007", "labs.ahmedabad@bis.gov.in"],
  ["BIS Laboratory, Bengaluru", "Bengaluru", "Karnataka", "BIS Laboratory", "electronics,electrical,mechanical", "080-222-0008", "labs.bengaluru@bis.gov.in"],
  ["BIS Laboratory, Hyderabad", "Hyderabad", "Telangana", "BIS Laboratory", "food,plastics,electrical", "040-222-0009", "labs.hyderabad@bis.gov.in"],
  ["BIS Laboratory, Patna", "Patna", "Bihar", "BIS Laboratory", "construction,consumer", "0612-222-0010", "labs.patna@bis.gov.in"],
  ["BIS Laboratory, Guwahati", "Guwahati", "Assam", "BIS Laboratory", "construction,food,electrical", "0361-222-0011", "labs.guwahati@bis.gov.in"],
  ["BIS Laboratory, Bhopal", "Bhopal", "Madhya Pradesh", "BIS Laboratory", "construction,mechanical", "0755-222-0012", "labs.bhopal@bis.gov.in"],
  ["BIS Laboratory, Bhubaneswar", "Bhubaneswar", "Odisha", "BIS Laboratory", "construction,mechanical,consumer", "0674-222-0013", "labs.bhubaneswar@bis.gov.in"],
  ["BIS Laboratory, Kochi", "Kochi", "Kerala", "BIS Laboratory", "food,plastics,consumer", "0484-222-0014", "labs.kochi@bis.gov.in"],
  ["BIS Laboratory, Raipur", "Raipur", "Chhattisgarh", "BIS Laboratory", "construction,mechanical", "0771-222-0015", "labs.raipur@bis.gov.in"],
  ["BIS Laboratory, Ranchi", "Ranchi", "Jharkhand", "BIS Laboratory", "construction,mechanical,consumer", "0651-222-0016", "labs.ranchi@bis.gov.in"],
  ["BIS Laboratory, Chandigarh", "Chandigarh", "Chandigarh", "BIS Laboratory", "construction,food,consumer", "0172-222-0017", "labs.chandigarh@bis.gov.in"],
  ["BIS Laboratory, Dehradun", "Dehradun", "Uttarakhand", "BIS Laboratory", "food,construction,consumer", "0135-222-0018", "labs.dehradun@bis.gov.in"],
  ["BIS Laboratory, Shimla", "Shimla", "Himachal Pradesh", "BIS Laboratory", "food,consumer,construction", "0177-222-0019", "labs.shimla@bis.gov.in"],
  ["BIS Laboratory, Vijayawada", "Vijayawada", "Andhra Pradesh", "BIS Laboratory", "construction,food,mechanical", "0866-222-0020", "labs.vijayawada@bis.gov.in"],
  ["BIS Laboratory, Nagpur", "Nagpur", "Maharashtra", "BIS Laboratory", "construction,mechanical,food", "0712-222-0021", "labs.nagpur@bis.gov.in"],
  ["BIS Laboratory, Ludhiana", "Ludhiana", "Punjab", "BIS Laboratory", "mechanical,construction,consumer", "0161-222-0022", "labs.ludhiana@bis.gov.in"],
  ["BIS Laboratory, Coimbatore", "Coimbatore", "Tamil Nadu", "BIS Laboratory", "mechanical,electronics,consumer", "0422-222-0023", "labs.coimbatore@bis.gov.in"],
  ["BIS Laboratory, Surat", "Surat", "Gujarat", "BIS Laboratory", "plastics,consumer,hallmark", "0261-222-0024", "labs.surat@bis.gov.in"],
  ["BIS Laboratory, Indore", "Indore", "Madhya Pradesh", "BIS Laboratory", "food,plastics,consumer", "0731-222-0025", "labs.indore@bis.gov.in"],
  ["BIS Laboratory, Lucknow", "Lucknow", "Uttar Pradesh", "BIS Laboratory", "food,construction,consumer", "0522-222-0026", "labs.lucknow@bis.gov.in"],
  ["BIS Laboratory, Agra", "Agra", "Uttar Pradesh", "BIS Laboratory", "consumer,mechanical,hallmark", "0562-222-0027", "labs.agra@bis.gov.in"],
  ["BIS Laboratory, Meerut", "Meerut", "Uttar Pradesh", "BIS Laboratory", "construction,mechanical,electrical", "0121-222-0028", "labs.meerut@bis.gov.in"],
  ["BIS Laboratory, Rajkot", "Rajkot", "Gujarat", "BIS Laboratory", "mechanical,plastics,consumer", "0281-222-0029", "labs.rajkot@bis.gov.in"],
  ["BIS Laboratory, Vadodara", "Vadodara", "Gujarat", "BIS Laboratory", "plastics,electrical,mechanical", "0265-222-0030", "labs.vadodara@bis.gov.in"],
  ["BIS Laboratory, Varanasi", "Varanasi", "Uttar Pradesh", "BIS Laboratory", "food,consumer,hallmark", "0542-222-0031", "labs.varanasi@bis.gov.in"],
  ["BIS Laboratory, Madurai", "Madurai", "Tamil Nadu", "BIS Laboratory", "food,construction,consumer", "0452-222-0032", "labs.madurai@bis.gov.in"],
  ["BIS Laboratory, Thrissur", "Thrissur", "Kerala", "BIS Laboratory", "food,consumer,electronics", "0487-222-0033", "labs.thrissur@bis.gov.in"],
  ["BIS Laboratory, Bengaluru (Electrical)", "Bengaluru", "Karnataka", "BIS Laboratory", "electrical,electronics,consumer", "080-222-0034", "labs.blr.el@bis.gov.in"],
  ["BIS Laboratory, Mysuru", "Mysuru", "Karnataka", "BIS Laboratory", "food,consumer,hallmark", "0821-222-0035", "labs.mysuru@bis.gov.in"],
];

/* ---------------------------- National Test House ---------------------------- */

export const NTH_LABS: LabRow[] = [
  ["National Test House (Headquarters), Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "construction,mechanical,electrical,electronics,plastics,consumer", "033-2337-8227", "nth.kolkata@nthindia.in"],
  ["National Test House (Northern Region), Ghaziabad", "Ghaziabad", "Uttar Pradesh", "Recognized Laboratory", "construction,mechanical,electrical,plastics", "0120-278-9001", "nth.nr@nthindia.in"],
  ["National Test House (Western Region), Mumbai", "Mumbai", "Maharashtra", "Recognized Laboratory", "consumer,mechanical,electrical,electronics", "022-2579-9002", "nth.wr@nthindia.in"],
  ["National Test House (Southern Region), Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "construction,mechanical,electronics", "044-2252-9003", "nth.sr@nthindia.in"],
  ["National Test House (Eastern Region), Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "construction,mechanical,food", "033-2337-9004", "nth.er@nthindia.in"],
  ["National Test House (Rajasthan), Jaipur", "Jaipur", "Rajasthan", "Recognized Laboratory", "construction,consumer,hallmark", "0141-274-9005", "nth.jaipur@nthindia.in"],
  ["National Test House (Assam), Guwahati", "Guwahati", "Assam", "Recognized Laboratory", "construction,food,mechanical", "0361-255-9006", "nth.guwahati@nthindia.in"],
];

/* ------------------------- STQC / ERTL / ETDC network ------------------------- */

export const STQC_LABS: LabRow[] = [
  ["ERTL (North), New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "electronics,electrical", "011-2696-0001", "ertln@stpi.in"],
  ["ERTL (East), Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "electronics,electrical", "033-2357-0002", "ertle@stpi.in"],
  ["ERTL (West), Mumbai", "Mumbai", "Maharashtra", "Recognized Laboratory", "electronics,electrical", "022-2757-0003", "ertlw@stpi.in"],
  ["ERTL (South), Bengaluru", "Bengaluru", "Karnataka", "Recognized Laboratory", "electronics,electrical", "080-2511-0004", "ertls@stpi.in"],
  ["ETDC, Bengaluru", "Bengaluru", "Karnataka", "Recognized Laboratory", "electronics,electrical", "080-2509-0005", "etdc.blr@stqc.gov.in"],
  ["ETDC, Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "electronics,electrical", "044-2254-0006", "etdc.chn@stqc.gov.in"],
  ["ETDC, Hyderabad", "Hyderabad", "Telangana", "Recognized Laboratory", "electronics,electrical", "040-2311-0007", "etdc.hyd@stqc.gov.in"],
  ["ETDC, Mohali", "Mohali", "Punjab", "Recognized Laboratory", "electronics,electrical", "0172-222-0008", "etdc.mohali@stqc.gov.in"],
  ["ETDC, Jaipur", "Jaipur", "Rajasthan", "Recognized Laboratory", "electronics,electrical", "0141-222-0009", "etdc.jaipur@stqc.gov.in"],
  ["ETDC, Solan", "Solan", "Himachal Pradesh", "Recognized Laboratory", "electronics", "01792-222-0010", "etdc.solan@stqc.gov.in"],
  ["ETDC, Gandhinagar", "Gandhinagar", "Gujarat", "Recognized Laboratory", "electronics,electrical", "079-2321-0011", "etdc.gnr@stqc.gov.in"],
  ["ETDC, Aurangabad", "Aurangabad", "Maharashtra", "Recognized Laboratory", "electronics", "0240-2331-0012", "etdc.aur@stqc.gov.in"],
  ["ETDC, Thrissur", "Thrissur", "Kerala", "Recognized Laboratory", "electronics,electrical", "0487-2331-0013", "etdc.tcr@stqc.gov.in"],
  ["STQC Testing Centre, Noida", "Noida", "Uttar Pradesh", "Recognized Laboratory", "electronics,electrical", "0120-4201-0014", "stqc.noida@stqc.gov.in"],
  ["STQC Testing Centre, Guwahati", "Guwahati", "Assam", "Recognized Laboratory", "electronics", "0361-2331-0015", "stqc.guwahati@stqc.gov.in"],
  ["STQC Testing Centre, Bhubaneswar", "Bhubaneswar", "Odisha", "Recognized Laboratory", "electronics,electrical", "0674-2331-0016", "stqc.bbsr@stqc.gov.in"],
];

/* ------------------------------ Government / CSIR ------------------------------ */

export const GOVT_LABS: LabRow[] = [
  ["Central Power Research Institute (CPRI), Bengaluru", "Bengaluru", "Karnataka", "Recognized Laboratory", "electrical,electronics,mechanical", "080-2207-2200", "director@cpri.in"],
  ["CPRI Regional Testing Laboratory, Bhopal", "Bhopal", "Madhya Pradesh", "Recognized Laboratory", "electrical,mechanical", "0755-2661-2201", "rtl.bhopal@cpri.in"],
  ["Electric Research and Development Association (ERDA), Vadodara", "Vadodara", "Gujarat", "Recognized Laboratory", "electrical,electronics", "0265-2281-2202", "erda@erda.org"],
  ["Central Food Technological Research Institute (CFTRI), Mysuru", "Mysuru", "Karnataka", "Recognized Laboratory", "food", "0821-251-5350", "director@cftri.res.in"],
  ["Defence Food Research Laboratory (DFRL), Mysuru", "Mysuru", "Karnataka", "Recognized Laboratory", "food", "0821-257-3203", "dfrl@dfrl.drdo.in"],
  ["Indian Institute of Packaging (IIP), Mumbai", "Mumbai", "Maharashtra", "Recognized Laboratory", "plastics,consumer", "022-2823-9800", "testing@iip-in.com"],
  ["Indian Institute of Packaging (IIP), Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "plastics,consumer", "011-2611-9801", "iipdelhi@iip-in.com"],
  ["Indian Institute of Packaging (IIP), Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "plastics,food", "033-2321-9802", "iipkolkata@iip-in.com"],
  ["SITRA — South India Textile Research Association", "Coimbatore", "Tamil Nadu", "Recognized Laboratory", "consumer", "0422-2571-6700", "sitrain@sitra.org.in"],
  ["ATIRA — Ahmedabad Textile Industry's Research Association", "Ahmedabad", "Gujarat", "Recognized Laboratory", "consumer,plastics", "079-2630-6701", "atira@atira.in"],
  ["BTRA — Bombay Textile Research Association", "Mumbai", "Maharashtra", "Recognized Laboratory", "consumer", "022-2500-6702", "btra@btraindia.com"],
  ["NITRA — Northern India Textile Research Association", "Ghaziabad", "Uttar Pradesh", "Recognized Laboratory", "consumer", "0120-271-6703", "nitra@nitra.in"],
  ["SASMIRA — Synthetic and Art Silk Mills Research Association", "Mumbai", "Maharashtra", "Recognized Laboratory", "consumer,plastics", "022-2200-6704", "sasmira@sasmira.org"],
  ["IJIRA — Indian Jute Industries Research Association", "Kolkata", "West Bengal", "Recognized Laboratory", "consumer", "033-2337-6705", "ijira@ijira.org"],
  ["CIPET — Central Institute of Petrochemicals Engineering and Technology, Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "plastics,consumer", "044-2225-6706", "cipet@cipet.gov.in"],
  ["CIPET, Lucknow", "Lucknow", "Uttar Pradesh", "Recognized Laboratory", "plastics", "0522-2431-6707", "lko@cipet.gov.in"],
  ["CIPET, Amritsar", "Amritsar", "Punjab", "Recognized Laboratory", "plastics", "0183-2221-6708", "asr@cipet.gov.in"],
  ["CIPET, Bhubaneswar", "Bhubaneswar", "Odisha", "Recognized Laboratory", "plastics", "0674-2741-6709", "bbsr@cipet.gov.in"],
  ["CSIR — National Physical Laboratory (NPL), New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "electronics,mechanical,electrical", "011-4560-6700", "npl@nplindia.org"],
  ["CSIR — National Environmental Engineering Research Institute (NEERI), Nagpur", "Nagpur", "Maharashtra", "Recognized Laboratory", "food", "0712-2249-6701", "neeri@neeri.res.in"],
  ["CSIR — Central Building Research Institute (CBRI), Roorkee", "Roorkee", "Uttarakhand", "Recognized Laboratory", "construction", "01332-272-6702", "cbri@cbri.res.in"],
  ["CSIR — Central Leather Research Institute (CLRI), Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "consumer", "044-2443-6703", "clri@clri.res.in"],
  ["CSIR — Indian Institute of Petroleum (IIP), Dehradun", "Dehradun", "Uttarakhand", "Recognized Laboratory", "chemicals,mechanical", "0135-2525-6704", "iip@iip.res.in"],
  ["CSIR — National Metallurgical Laboratory (NML), Jamshedpur", "Jamshedpur", "Jharkhand", "Recognized Laboratory", "mechanical,construction", "0657-2345-6705", "nml@nmlindia.org"],
  ["CSIR — Structural Engineering Research Centre (SERC), Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "construction,mechanical", "044-2254-6706", "serc@serc.res.in"],
  ["CSIR — Central Mechanical Engineering Research Institute (CMERI), Durgapur", "Durgapur", "West Bengal", "Recognized Laboratory", "mechanical,electrical", "0343-2545-6707", "cmeri@cmeri.res.in"],
  ["CSIR — Central Electronics Engineering Research Institute (CEERI), Pilani", "Pilani", "Rajasthan", "Recognized Laboratory", "electronics", "01596-242-6708", "ceeri@ceeri.ernet.in"],
  ["CSIR — Institute of Minerals and Materials Technology (IMMT), Bhubaneswar", "Bhubaneswar", "Odisha", "Recognized Laboratory", "mechanical,chemicals", "0674-2581-6709", "immt@immt.res.in"],
  ["CSIR — Central Drug Research Institute (CDRI), Lucknow", "Lucknow", "Uttar Pradesh", "Recognized Laboratory", "food", "0522-2621-6710", "cdri@cdri.res.in"],
  ["Indian Agricultural Research Institute (IARI), New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "food,chemicals", "011-2584-6711", "iari@iari.res.in"],
  ["Central Institute of Post-Harvest Engineering and Technology (CIPHET), Ludhiana", "Ludhiana", "Punjab", "Recognized Laboratory", "food,mechanical", "0161-2851-6712", "ciphet@ciphet.res.in"],
  ["Directorate of Plant Protection, Quarantine and Storage, Faridabad", "Faridabad", "Haryana", "Recognized Laboratory", "chemicals,food", "0129-2411-6713", "ppqs@nic.in"],
  ["Central Institute of Agricultural Engineering (CIAE), Bhopal", "Bhopal", "Madhya Pradesh", "Recognized Laboratory", "mechanical,chemicals", "0755-2731-6714", "ciae@ciae.res.in"],
  ["National Institute of Oceanography (NIO), Goa", "Panaji", "Goa", "Recognized Laboratory", "food", "0832-2450-6715", "nio@nio.org"],
  ["Central Institute of Fisheries Technology (CIFT), Kochi", "Kochi", "Kerala", "Recognized Laboratory", "food", "0484-2412-6716", "cift@cift.res.in"],
  ["National Dairy Research Institute (NDRI), Karnal", "Karnal", "Haryana", "Recognized Laboratory", "food", "0184-2252-6717", "ndri@ndri.res.in"],
  ["Central Sheep and Wool Research Institute (CSWRI), Avikanagar", "Avikanagar", "Rajasthan", "Recognized Laboratory", "consumer", "01437-222-6718", "cswri@cswri.res.in"],
  ["Central Institute of Road Transport (CIRT), Pune", "Pune", "Maharashtra", "Recognized Laboratory", "mechanical,chemicals", "020-2721-6719", "cirt@cirtindia.com"],
  ["Automotive Research Association of India (ARAI), Pune", "Pune", "Maharashtra", "Recognized Laboratory", "mechanical,electrical", "020-3023-1111", "director@araiindia.com"],
  ["Automotive Industry Standards — ICAT, Manesar", "Manesar", "Haryana", "Recognized Laboratory", "mechanical,electronics", "0124-2221-6720", "icat@icat.in"],
  ["Vehicle Research and Development Establishment (VRDE), Ahmednagar", "Ahmednagar", "Maharashtra", "Recognized Laboratory", "mechanical", "0241-2251-6721", "vrde@vrde.drdo.in"],
  ["Research Designs and Standards Organisation (RDSO), Lucknow", "Lucknow", "Uttar Pradesh", "Recognized Laboratory", "mechanical,construction,electrical", "0522-2411-6722", "rdso@rdso.res.in"],
  ["Central Road Research Institute (CRRI), New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "construction,chemicals", "011-2584-6723", "crri@crri.res.in"],
  ["Central Board of Irrigation and Power (CBIP), New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "electrical,construction", "011-2611-6724", "cbip@cbip.org"],
  ["RITES Materials Testing Laboratory, Gurugram", "Gurugram", "Haryana", "Recognized Laboratory", "construction,mechanical", "0124-2381-6725", "rites@rites.com"],
  ["Wadia Institute of Himalayan Geology Testing Unit, Dehradun", "Dehradun", "Uttarakhand", "Recognized Laboratory", "construction", "0135-2525-6726", "wihg@wihg.res.in"],
  ["Geological Survey of India — Central Chemical Laboratory, Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "chemicals,construction", "033-2286-6727", "gsi@gsm.gov.in"],
  ["Survey of India — Standards and Calibration Unit, Dehradun", "Dehradun", "Uttarakhand", "Recognized Laboratory", "electronics,mechanical", "0135-2741-6728", "soi@surveyofindia.gov.in"],
];

/* --------------------------- Private recognized labs --------------------------- */

export const PRIVATE_LABS: LabRow[] = [
  ["SGS India — Materials Testing Laboratory", "Mumbai", "Maharashtra", "Recognized Laboratory", "construction,mechanical,chemicals,plastics", "022-6640-1100", "mumbai.lab@sgs-india.in"],
  ["SGS India — Electronics and Electrical Laboratory", "Chennai", "Tamil Nadu", "Recognized Laboratory", "electronics,electrical", "044-4297-1101", "chennai.lab@sgs-india.in"],
  ["SGS India — Food Testing Laboratory", "Gurugram", "Haryana", "Recognized Laboratory", "food,chemicals", "0124-4641-1102", "food.gurugram@sgs-india.in"],
  ["SGS India — Consumer Goods Laboratory", "Bengaluru", "Karnataka", "Recognized Laboratory", "consumer,plastics", "080-6711-1103", "blr.lab@sgs-india.in"],
  ["SGS India — Materials Laboratory, Ahmedabad", "Ahmedabad", "Gujarat", "Recognized Laboratory", "construction,chemicals", "079-6611-1104", "ahmedabad.lab@sgs-india.in"],
  ["TUV SUD South Asia — Product Testing", "Mumbai", "Maharashtra", "Recognized Laboratory", "electrical,electronics,mechanical", "022-6671-1200", "info.in@tuvsud.com"],
  ["TUV SUD — Wire and Cable Testing Laboratory", "Bengaluru", "Karnataka", "Recognized Laboratory", "electrical,mechanical", "080-6681-1201", "blr.lab@tuvsud.com"],
  ["TUV SUD — Battery and Energy Testing", "Gurugram", "Haryana", "Recognized Laboratory", "electrical,electronics", "0124-6681-1202", "energy.in@tuvsud.com"],
  ["TUV Rheinland India — Electrical Laboratory", "Bengaluru", "Karnataka", "Recognized Laboratory", "electrical,electronics", "080-6651-1300", "info@in.tuv.com"],
  ["TUV Rheinland — Industrial Services, Noida", "Noida", "Uttar Pradesh", "Recognized Laboratory", "mechanical,construction", "0120-4651-1301", "is.in@tuv.com"],
  ["TUV Rheinland — Softlines and Textile Laboratory", "Noida", "Uttar Pradesh", "Recognized Laboratory", "consumer", "0120-4651-1302", "softlines.in@tuv.com"],
  ["Intertek India — Electrical and Electronics", "Gurugram", "Haryana", "Recognized Laboratory", "electrical,electronics", "0124-4501-1400", "india.elec@intertek.com"],
  ["Intertek India — Materials and Construction", "Mumbai", "Maharashtra", "Recognized Laboratory", "construction,mechanical", "022-6101-1401", "mumbai.lab@intertek.com"],
  ["Intertek India — Food and Agri Testing", "Chennai", "Tamil Nadu", "Recognized Laboratory", "food,chemicals", "044-4211-1402", "foods.in@intertek.com"],
  ["Intertek India — Textile Testing, Ahmedabad", "Ahmedabad", "Gujarat", "Recognized Laboratory", "consumer", "079-6101-1403", "textile.ahd@intertek.com"],
  ["Bureau Veritas — Consumer Products Services", "Noida", "Uttar Pradesh", "Recognized Laboratory", "consumer,electronics,plastics", "0120-4301-1500", "cps.india@bureauveritas.com"],
  ["Bureau Veritas — Electrical Laboratory, Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "electrical,electronics", "044-4301-1501", "electrical.chn@bureauveritas.com"],
  ["Bureau Veritas — Construction Materials, Ahmedabad", "Ahmedabad", "Gujarat", "Recognized Laboratory", "construction,mechanical", "079-4301-1502", "materials.ahd@bureauveritas.com"],
  ["Bureau Veritas — Food Laboratory, Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "food", "033-4301-1503", "food.kol@bureauveritas.com"],
  ["UL India — Electrical and Fire Safety Laboratory", "Bengaluru", "Karnataka", "Recognized Laboratory", "electrical,electronics,consumer", "080-4130-1600", "ulindia@ul.com"],
  ["UL India — Battery and Energy Storage Testing", "Gurugram", "Haryana", "Recognized Laboratory", "electrical,electronics", "0124-4130-1601", "battery.in@ul.com"],
  ["DEKRA India — Electrical Testing Laboratory", "Chennai", "Tamil Nadu", "Recognized Laboratory", "electrical,electronics", "044-4291-1700", "info.in@dekra.com"],
  ["DEKRA India — Industrial Inspection and Materials", "Gurugram", "Haryana", "Recognized Laboratory", "mechanical,construction", "0124-4291-1701", "industrial.in@dekra.com"],
  ["Eurofins India — Food and Water Testing, Mumbai", "Mumbai", "Maharashtra", "Recognized Laboratory", "food,chemicals", "022-4291-1800", "mumbai@eurofins.in"],
  ["Eurofins India — Food Testing, Bengaluru", "Bengaluru", "Karnataka", "Recognized Laboratory", "food", "080-4291-1801", "bengaluru@eurofins.in"],
  ["Eurofins India — Environment Testing, Hyderabad", "Hyderabad", "Telangana", "Recognized Laboratory", "chemicals,food", "040-4291-1802", "hyderabad@eurofins.in"],
  ["Eurofins India — Consumer Products, Gurugram", "Gurugram", "Haryana", "Recognized Laboratory", "consumer,plastics", "0124-4291-1803", "consumer.in@eurofins.in"],
  ["Vimta Labs — Preclinical and Analytical Testing", "Hyderabad", "Telangana", "Recognized Laboratory", "food,chemicals", "040-2726-1900", "info@vimta.com"],
  ["Vimta Labs — Materials Testing Division", "Hyderabad", "Telangana", "Recognized Laboratory", "construction,mechanical", "040-2726-1901", "materials@vimta.com"],
  ["Vimta Labs — Electronics and EMC, Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "electronics,electrical", "044-2726-1902", "emc@vimta.com"],
  ["Vinta Labs — Electronics Testing", "Noida", "Uttar Pradesh", "Recognized Laboratory", "electronics,electrical", "0120-4433-2000", "support@vinta.in"],
  ["Vinta Labs — Wireless and Telecom Testing", "Gurugram", "Haryana", "Recognized Laboratory", "electronics", "0124-4433-2001", "wireless@vinta.in"],
  ["Shriram Institute for Industrial Research, Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "plastics,food,chemicals,consumer", "011-2760-2100", "labs@shriraminstitute.org"],
  ["Shriram Institute for Industrial Research, Bengaluru", "Bengaluru", "Karnataka", "Recognized Laboratory", "plastics,construction,mechanical", "080-2839-2101", "blr@shriraminstitute.org"],
  ["Shriram Institute — Packaging Testing Centre, Haridwar", "Haridwar", "Uttarakhand", "Recognized Laboratory", "plastics,food", "01334-211-2102", "haridwar@shriraminstitute.org"],
  ["Spectro Analytical Labs, New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "chemicals,construction,food", "011-4552-2200", "care@spectro.in"],
  ["Spectro Analytical Labs, Vadodara", "Vadodara", "Gujarat", "Recognized Laboratory", "chemicals,plastics", "0265-4552-2201", "baroda@spectro.in"],
  ["Sigma Test and Research Centre, New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "electrical,electronics,consumer", "011-4940-2300", "info@sigmatest.org"],
  ["Sigma Test and Research Centre — Cable Division", "Noida", "Uttar Pradesh", "Recognized Laboratory", "electrical", "0120-4940-2301", "cable@sigmatest.org"],
  ["URS Products and Testing Labs, Faridabad", "Faridabad", "Haryana", "Recognized Laboratory", "electrical,consumer,mechanical", "0129-400-2400", "info@urstestinglab.com"],
  ["Labs India (TUV), Gurugram", "Gurugram", "Haryana", "Recognized Laboratory", "construction,mechanical,electrical", "0124-436-2500", "labs.india@tuv.com"],
  ["Advance Testing and Calibration, Pune", "Pune", "Maharashtra", "Recognized Laboratory", "electrical,mechanical,electronics", "020-6740-2600", "atc.pune@labmail.in"],
  ["QAI India — Certification Testing, Noida", "Noida", "Uttar Pradesh", "Recognized Laboratory", "electronics,electrical,consumer", "0120-4551-2700", "india@qai.org"],
  ["QAI India — Laboratory, Bengaluru", "Bengaluru", "Karnataka", "Recognized Laboratory", "electronics,electrical", "080-4551-2701", "blr@qai.org"],
  ["Choksi Laboratories, Indore", "Indore", "Madhya Pradesh", "Recognized Laboratory", "chemicals,food", "0731-4041-2800", "info@choksilab.com"],
  ["Choksi Laboratories — Pharma and Food Division, Vadodara", "Vadodara", "Gujarat", "Recognized Laboratory", "food,chemicals", "0265-4041-2801", "baroda@choksilab.com"],
  ["Anacon Laboratories, Nagpur", "Nagpur", "Maharashtra", "Recognized Laboratory", "food,chemicals,construction", "0712-6611-2900", "anacon@anaconlab.com"],
  ["Aditya Environmental Services, Mumbai", "Mumbai", "Maharashtra", "Recognized Laboratory", "chemicals,food", "022-6141-3000", "aes@adityaenv.in"],
  ["Perfect Pollucon Services, Navi Mumbai", "Navi Mumbai", "Maharashtra", "Recognized Laboratory", "chemicals,food", "022-6141-3100", "info@pollucon.in"],
  ["Alpha Test House, New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "construction,mechanical,plastics", "011-4567-3200", "alpha@alphatesthouse.in"],
  ["Delhi Test House, New Delhi", "New Delhi", "Delhi", "Recognized Laboratory", "electrical,consumer,construction", "011-2735-3300", "info@delhitesthouse.in"],
  ["Standard Testing Laboratory, Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "construction,mechanical,chemicals", "033-2357-3400", "stl.kolkata@stlab.in"],
  ["Premier Test House, Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "food,chemicals,consumer", "033-2400-3401", "premier@pth.in"],
  ["Bengal Test House, Kolkata", "Kolkata", "West Bengal", "Recognized Laboratory", "construction,mechanical", "033-2486-3402", "bengal@btesthouse.in"],
  ["Punjab Test House and Calibration Centre, Ludhiana", "Ludhiana", "Punjab", "Recognized Laboratory", "mechanical,electrical,construction", "0161-254-3500", "info@punjabtesthouse.in"],
  ["Haryana Test House, Gurugram", "Gurugram", "Haryana", "Recognized Laboratory", "mechanical,plastics,consumer", "0124-2451-3501", "haryana@htesthouse.in"],
  ["Rajasthan Test House, Jaipur", "Jaipur", "Rajasthan", "Recognized Laboratory", "construction,mechanical,food", "0141-2741-3502", "rth@rajtesthouse.in"],
  ["Gujarat Laboratory, Ahmedabad", "Ahmedabad", "Gujarat", "Recognized Laboratory", "plastics,construction,electrical", "079-2546-3600", "info@gujaratlab.in"],
  ["Saurashtra Testing Laboratory, Rajkot", "Rajkot", "Gujarat", "Recognized Laboratory", "mechanical,plastics,consumer", "0281-2361-3601", "saurashtra@stl.in"],
  ["Deccan Test House, Hyderabad", "Hyderabad", "Telangana", "Recognized Laboratory", "electrical,electronics,mechanical", "040-2761-3700", "info@deccantest.in"],
  ["Visakha Test and Research Centre, Visakhapatnam", "Visakhapatnam", "Andhra Pradesh", "Recognized Laboratory", "construction,food,mechanical", "0891-2761-3701", "visakha@vtrc.in"],
  ["Kerala State Test House, Kochi", "Kochi", "Kerala", "Recognized Laboratory", "construction,food,consumer", "0484-235-3800", "test@keralatesthouse.in"],
  ["Kerala Agro Testing Laboratory, Thrissur", "Thrissur", "Kerala", "Recognized Laboratory", "food,chemicals", "0487-235-3801", "katl@keralaagri.in"],
  ["Tamil Nadu Test and Research Centre, Coimbatore", "Coimbatore", "Tamil Nadu", "Recognized Laboratory", "mechanical,electronics,consumer", "0422-243-3900", "info@tntrc.in"],
  ["Madras Analytical Laboratories, Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "chemicals,construction,food", "044-2434-3901", "madras@malabs.in"],
  ["Karnataka Test House, Bengaluru", "Bengaluru", "Karnataka", "Recognized Laboratory", "electronics,electrical,mechanical", "080-2839-4000", "info@karnatakatest.in"],
  ["Mysore Analytical and Testing Services, Mysuru", "Mysuru", "Karnataka", "Recognized Laboratory", "food,chemicals", "0821-2441-4001", "mats@mysorelab.in"],
  ["Malwa Analysts and Research, Indore", "Indore", "Madhya Pradesh", "Recognized Laboratory", "food,plastics,chemicals", "0731-256-4100", "info@malwaanalysts.in"],
  ["Bhopal Materials Testing Laboratory, Bhopal", "Bhopal", "Madhya Pradesh", "Recognized Laboratory", "construction,mechanical", "0755-2661-4101", "bmtl@bhopallab.in"],
  ["Vidarbha Testing and Research Centre, Nagpur", "Nagpur", "Maharashtra", "Recognized Laboratory", "construction,mechanical,food", "0712-2451-4200", "vtrc@nagpurlab.in"],
  ["Marathwada Test House, Aurangabad", "Aurangabad", "Maharashtra", "Recognized Laboratory", "mechanical,chemicals", "0240-2331-4201", "marathwada@mth.in"],
  ["Odisha Test and Research Centre, Bhubaneswar", "Bhubaneswar", "Odisha", "Recognized Laboratory", "construction,mechanical,chemicals", "0674-258-4300", "info@odishatest.in"],
  ["Cuttack Analytical Laboratory, Cuttack", "Cuttack", "Odisha", "Recognized Laboratory", "food,chemicals", "0671-2331-4301", "cutcack@cal.in"],
  ["Assam Engineering Test House, Guwahati", "Guwahati", "Assam", "Recognized Laboratory", "construction,electrical,mechanical", "0361-255-4400", "info@aetghy.in"],
  ["North East Food Testing Laboratory, Guwahati", "Guwahati", "Assam", "Recognized Laboratory", "food,chemicals", "0361-2331-4401", "neftl@nefoodlab.in"],
  ["Bihar Test House, Patna", "Patna", "Bihar", "Recognized Laboratory", "construction,mechanical,consumer", "0612-2541-4500", "bihar@bth.in"],
  ["Jharkhand Materials Laboratory, Ranchi", "Ranchi", "Jharkhand", "Recognized Laboratory", "construction,mechanical", "0651-2331-4501", "jml@ranchilab.in"],
  ["Chhattisgarh Test and Research Centre, Raipur", "Raipur", "Chhattisgarh", "Recognized Laboratory", "construction,food,mechanical", "0771-2241-4600", "ctrc@raipurlab.in"],
  ["Goa Analytical Services, Panaji", "Panaji", "Goa", "Recognized Laboratory", "food,chemicals,construction", "0832-2451-4700", "goa@analytical.in"],
  ["Himachal Testing Laboratory, Solan", "Solan", "Himachal Pradesh", "Recognized Laboratory", "food,chemicals,construction", "01792-2231-4800", "hpl@himtest.in"],
  ["Uttarakhand Test House, Dehradun", "Dehradun", "Uttarakhand", "Recognized Laboratory", "food,construction,consumer", "0135-2741-4900", "uttarakhand@uth.in"],
  ["Jammu and Kashmir Testing Laboratory, Jammu", "Jammu", "Jammu and Kashmir", "Recognized Laboratory", "construction,food,consumer", "0191-2541-5000", "jk@jklab.in"],
  ["Ladakh Materials Testing Unit, Leh", "Leh", "Ladakh", "Recognized Laboratory", "construction,mechanical", "01982-252-5001", "leh@lmtu.in"],
  ["Puducherry Test House, Puducherry", "Puducherry", "Puducherry", "Recognized Laboratory", "food,construction,consumer", "0413-2331-5100", "pth@puducherrylab.in"],
  ["Andaman Testing Services, Port Blair", "Port Blair", "Andaman and Nicobar Islands", "Recognized Laboratory", "food,construction", "03192-231-5101", "ats@andamanlab.in"],
  ["Manipur Testing Laboratory, Imphal", "Imphal", "Manipur", "Recognized Laboratory", "food,construction,consumer", "0385-2441-5200", "manipur@mtl.in"],
  ["Meghalaya Test House, Shillong", "Shillong", "Meghalaya", "Recognized Laboratory", "food,construction", "0364-2501-5201", "meghalaya@mth.in"],
  ["Tripura Analytical Laboratory, Agartala", "Agartala", "Tripura", "Recognized Laboratory", "food,construction,consumer", "0381-2321-5202", "tripura@tal.in"],
  ["Nagaland Materials Testing Unit, Kohima", "Kohima", "Nagaland", "Recognized Laboratory", "construction,consumer", "0370-2241-5203", "kohima@nmtu.in"],
  ["Mizoram Test and Research Centre, Aizawl", "Aizawl", "Mizoram", "Recognized Laboratory", "food,construction", "0389-2321-5204", "mizoram@mtrc.in"],
  ["Arunachal Testing Services, Itanagar", "Itanagar", "Arunachal Pradesh", "Recognized Laboratory", "construction,food", "0360-2241-5205", "itanagar@ats.in"],
  ["Sikkim Food and Materials Laboratory, Gangtok", "Gangtok", "Sikkim", "Recognized Laboratory", "food,construction,plastics", "03592-232-5206", "sikkim@sfml.in"],
  ["Telangana Agro and Food Laboratory, Warangal", "Warangal", "Telangana", "Recognized Laboratory", "food,chemicals", "0870-2451-5300", "tafl@warangal.in"],
  ["Coastal Andhra Food Testing Laboratory, Guntur", "Guntur", "Andhra Pradesh", "Recognized Laboratory", "food,chemicals", "0863-2331-5301", "caf@nafoodlab.in"],
  ["Nashik Agro Testing Laboratory, Nashik", "Nashik", "Maharashtra", "Recognized Laboratory", "food,chemicals", "0253-2451-5302", "nashik@natl.in"],
  ["Kolhapur Foundry and Materials Lab, Kolhapur", "Kolhapur", "Maharashtra", "Recognized Laboratory", "mechanical,construction", "0231-2651-5303", "kolhapur@kfml.in"],
  ["Salem Steel Testing Laboratory, Salem", "Salem", "Tamil Nadu", "Recognized Laboratory", "mechanical,construction", "0427-2441-5304", "salem@sstl.in"],
  ["Hosur Electronics Test Laboratory, Hosur", "Hosur", "Tamil Nadu", "Recognized Laboratory", "electronics,electrical", "04344-2441-5305", "hosur@hetl.in"],
  ["Noida Electrical Equipment Testing Lab, Greater Noida", "Greater Noida", "Uttar Pradesh", "Recognized Laboratory", "electrical,mechanical", "0120-2321-5306", "neetl@noidalab.in"],
  ["Moradabad Metalware Testing Centre, Moradabad", "Moradabad", "Uttar Pradesh", "Recognized Laboratory", "mechanical,consumer", "0591-2451-5307", "moradabad@mmtc.in"],
  ["Aligarh Lock and Hardware Testing Lab, Aligarh", "Aligarh", "Uttar Pradesh", "Recognized Laboratory", "mechanical,consumer", "0571-2451-5308", "aligarh@alhtl.in"],
  ["Panipat Textile Testing Laboratory, Panipat", "Panipat", "Haryana", "Recognized Laboratory", "consumer", "0180-2651-5309", "panipat@pttl.in"],
  ["Ludhiana Hosiery Testing Centre, Ludhiana", "Ludhiana", "Punjab", "Recognized Laboratory", "consumer", "0161-2451-5310", "ludhiana@lhtc.in"],
  ["Tiruppur Knitwear Testing Laboratory, Tiruppur", "Tiruppur", "Tamil Nadu", "Recognized Laboratory", "consumer,chemicals", "0421-2451-5311", "tiruppur@tktl.in"],
  ["Surat Textile and Plastic Testing Lab, Surat", "Surat", "Gujarat", "Recognized Laboratory", "consumer,plastics", "0261-2451-5312", "surat@stptl.in"],
  ["Jaipur Gems and Jewellery Testing Lab, Jaipur", "Jaipur", "Rajasthan", "Recognized Laboratory", "hallmark,consumer", "0141-2451-5313", "jaipur@gjtc.in"],
  ["Mumbai Diamond and Jewellery Testing, Mumbai", "Mumbai", "Maharashtra", "Recognized Laboratory", "hallmark,consumer", "022-2451-5314", "mumbai@mdjt.in"],
  ["Karur Home Textile Testing Centre, Karur", "Karur", "Tamil Nadu", "Recognized Laboratory", "consumer", "04324-2451-5315", "karur@khtc.in"],
  ["Bhilwara Textile Testing Laboratory, Bhilwara", "Bhilwara", "Rajasthan", "Recognized Laboratory", "consumer", "01482-2451-5316", "bhilwara@bttl.in"],
  ["Ichalkaranji Textile Testing Centre, Ichalkaranji", "Ichalkaranji", "Maharashtra", "Recognized Laboratory", "consumer", "0230-2451-5317", "ichalkaranji@ittc.in"],
  ["Varanasi Carpet Testing Laboratory, Varanasi", "Varanasi", "Uttar Pradesh", "Recognized Laboratory", "consumer", "0542-2451-5318", "varanasi@vctl.in"],
  ["Srinagar Carpet and Pashmina Testing Lab, Srinagar", "Srinagar", "Jammu and Kashmir", "Recognized Laboratory", "consumer", "0194-2451-5319", "srinagar@scpt.in"],
  ["Bhadohi Carpet Testing Centre, Bhadohi", "Bhadohi", "Uttar Pradesh", "Recognized Laboratory", "consumer", "05414-245-5320", "bhadohi@bctc.in"],
  ["Kanpur Leather Testing Laboratory, Kanpur", "Kanpur", "Uttar Pradesh", "Recognized Laboratory", "consumer", "0512-2451-5321", "kanpur@kltl.in"],
  ["Agra Footwear Testing Centre, Agra", "Agra", "Uttar Pradesh", "Recognized Laboratory", "consumer", "0562-2451-5322", "agra@aftc.in"],
  ["Ranipet Leather and Footwear Lab, Ranipet", "Ranipet", "Tamil Nadu", "Recognized Laboratory", "consumer", "04172-245-5323", "ranipet@rlfl.in"],
  ["Jalandhar Sports Goods Testing Lab, Jalandhar", "Jalandhar", "Punjab", "Recognized Laboratory", "consumer,mechanical", "0181-2451-5324", "jalandhar@jsgt.in"],
  ["Meerut Sports Goods Testing Centre, Meerut", "Meerut", "Uttar Pradesh", "Recognized Laboratory", "consumer,mechanical", "0121-2451-5325", "meerut@msgc.in"],
  ["Bareilly Wood and Furniture Testing Lab, Bareilly", "Bareilly", "Uttar Pradesh", "Recognized Laboratory", "consumer,plastics", "0581-2451-5326", "bareilly@bwft.in"],
  ["Jodhpur Handicraft Testing Laboratory, Jodhpur", "Jodhpur", "Rajasthan", "Recognized Laboratory", "consumer", "0291-2451-5327", "jodhpur@jhtl.in"],
  ["Saharanpur Wood Testing Laboratory, Saharanpur", "Saharanpur", "Uttar Pradesh", "Recognized Laboratory", "consumer,plastics", "0132-2451-5328", "saharanpur@swtl.in"],
  ["Chandigarh Electrical Safety Laboratory, Chandigarh", "Chandigarh", "Chandigarh", "Recognized Laboratory", "electrical,mechanical", "0172-2451-5329", "chandigarh@cesl.in"],
  ["Dehradun Electronics and IT Testing Centre, Dehradun", "Dehradun", "Uttarakhand", "Recognized Laboratory", "electronics,electrical", "0135-2451-5330", "dehradun@deitc.in"],
  ["Bhubaneswar Electronics Testing Centre, Bhubaneswar", "Bhubaneswar", "Odisha", "Recognized Laboratory", "electronics,electrical", "0674-2451-5331", "bbsr@betc.in"],
  ["Kochi Marine Products Testing Lab, Kochi", "Kochi", "Kerala", "Recognized Laboratory", "food", "0484-2451-5332", "kochi@kmpt.in"],
  ["Vizag Marine and Food Testing Lab, Visakhapatnam", "Visakhapatnam", "Andhra Pradesh", "Recognized Laboratory", "food", "0891-2451-5333", "vizag@vmft.in"],
  ["Mangaluru Food Testing Laboratory, Mangaluru", "Mangaluru", "Karnataka", "Recognized Laboratory", "food,chemicals", "0824-2451-5334", "mangaluru@mftl.in"],
  ["Nashik Wine and Beverage Testing Lab, Nashik", "Nashik", "Maharashtra", "Recognized Laboratory", "food,chemicals", "0253-2451-5335", "nashik@nwbt.in"],
  ["Coimbatore Pumps and Motors Testing Lab, Coimbatore", "Coimbatore", "Tamil Nadu", "Recognized Laboratory", "mechanical,electrical", "0422-2451-5336", "coimbatore@cpmt.in"],
  ["Rajkot Pump and Foundry Testing Centre, Rajkot", "Rajkot", "Gujarat", "Recognized Laboratory", "mechanical,electrical", "0281-2451-5337", "rajkot@rpft.in"],
  ["Ahmedabad Chemical and Solvent Testing Lab, Ahmedabad", "Ahmedabad", "Gujarat", "Recognized Laboratory", "chemicals,plastics", "079-2451-5338", "ahmedabad@acst.in"],
  ["Ankleshwar Chemicals Testing Laboratory, Ankleshwar", "Ankleshwar", "Gujarat", "Recognized Laboratory", "chemicals,food", "02646-245-5339", "ankleshwar@actl.in"],
  ["Vapi Industrial Testing Laboratory, Vapi", "Vapi", "Gujarat", "Recognized Laboratory", "chemicals,plastics", "0260-2451-5340", "vapi@vitl.in"],
  ["Dahej Petrochemical Testing Centre, Dahej", "Dahej", "Gujarat", "Recognized Laboratory", "chemicals,mechanical", "02641-245-5341", "dahej@dptc.in"],
  ["Jamnagar Refinery Materials Testing Lab, Jamnagar", "Jamnagar", "Gujarat", "Recognized Laboratory", "mechanical,chemicals", "0288-2451-5342", "jamnagar@jrmt.in"],
  ["Haldia Petrochemical Testing Laboratory, Haldia", "Haldia", "West Bengal", "Recognized Laboratory", "chemicals,mechanical", "03224-245-5343", "haldia@hptl.in"],
  ["Durgapur Steel Testing Laboratory, Durgapur", "Durgapur", "West Bengal", "Recognized Laboratory", "mechanical,construction", "0343-2451-5344", "durgapur@dstl.in"],
  ["Bokaro Materials Testing Unit, Bokaro", "Bokaro", "Jharkhand", "Recognized Laboratory", "mechanical,chemicals", "06542-245-5345", "bokaro@bmtu.in"],
  ["Rourkela Metallurgical Testing Laboratory, Rourkela", "Rourkela", "Odisha", "Recognized Laboratory", "mechanical,chemicals", "0661-2451-5346", "rourkela@rmtl.in"],
  ["Raigarh Steel and Power Testing Lab, Raigarh", "Raigarh", "Chhattisgarh", "Recognized Laboratory", "mechanical,electrical", "07762-245-5347", "raigarh@rspt.in"],
  ["Angul Aluminium Testing Centre, Angul", "Angul", "Odisha", "Recognized Laboratory", "mechanical,electrical", "06764-245-5348", "angul@aatc.in"],
  ["Korba Power Equipment Testing Lab, Korba", "Korba", "Chhattisgarh", "Recognized Laboratory", "electrical,mechanical", "07759-245-5349", "korba@kpet.in"],
  ["Singrauli Electrical Testing Laboratory, Singrauli", "Singrauli", "Madhya Pradesh", "Recognized Laboratory", "electrical,electronics", "07862-245-5350", "singrauli@setl.in"],
  ["Ramagundam Thermal Testing Laboratory, Ramagundam", "Ramagundam", "Telangana", "Recognized Laboratory", "electrical,mechanical", "08728-245-5351", "ramagundam@rttl.in"],
  ["Neyveli Lignite Testing Laboratory, Neyveli", "Neyveli", "Tamil Nadu", "Recognized Laboratory", "electrical,chemicals", "04142-245-5352", "neyveli@nltl.in"],
  ["Tarapur Nuclear Materials Testing Unit, Tarapur", "Tarapur", "Maharashtra", "Recognized Laboratory", "mechanical,chemicals", "02525-245-5353", "tarapur@tnmt.in"],
  ["Kalpakkam Materials Testing Laboratory, Kalpakkam", "Kalpakkam", "Tamil Nadu", "Recognized Laboratory", "mechanical,electronics", "044-2748-5354", "kalpakkam@kmtl.in"],
  ["Hyderabad Pharma Packaging Testing Lab, Hyderabad", "Hyderabad", "Telangana", "Recognized Laboratory", "plastics,food", "040-2451-5355", "hyderabad@hppt.in"],
  ["Ahmedabad Pharma Packaging Laboratory, Ahmedabad", "Ahmedabad", "Gujarat", "Recognized Laboratory", "plastics,food", "079-2451-5356", "ahmedabad@appl.in"],
  ["Baddi Pharma and Packaging Testing, Baddi", "Baddi", "Himachal Pradesh", "Recognized Laboratory", "plastics,food,chemicals", "01795-245-5357", "baddi@bppt.in"],
  ["Indore Pharma Testing Laboratory, Indore", "Indore", "Madhya Pradesh", "Recognized Laboratory", "food,chemicals", "0731-2451-5358", "indore@iptl.in"],
  ["Chennai Auto Components Testing Lab, Chennai", "Chennai", "Tamil Nadu", "Recognized Laboratory", "mechanical,electrical", "044-2451-5359", "chennai@cact.in"],
  ["Pune Auto Components Testing Centre, Pune", "Pune", "Maharashtra", "Recognized Laboratory", "mechanical,electrical", "020-2451-5360", "pune@pact.in"],
  ["Manesar Auto Testing Laboratory, Manesar", "Manesar", "Haryana", "Recognized Laboratory", "mechanical,electronics", "0124-2451-5361", "manesar@matl.in"],
  ["Hosur Auto Components Laboratory, Hosur", "Hosur", "Tamil Nadu", "Recognized Laboratory", "mechanical,plastics", "04344-245-5362", "hosur@hacl.in"],
  ["Rudrapur Auto Testing Laboratory, Rudrapur", "Rudrapur", "Uttarakhand", "Recognized Laboratory", "mechanical,electrical", "05944-245-5363", "rudrapur@ratl.in"],
  ["Jamshedpur Tyre Testing Laboratory, Jamshedpur", "Jamshedpur", "Jharkhand", "Recognized Laboratory", "mechanical,plastics", "0657-2451-5364", "jamshedpur@jttl.in"],
  ["Kochi Tyre and Rubber Testing Lab, Kochi", "Kochi", "Kerala", "Recognized Laboratory", "mechanical,plastics", "0484-2451-5365", "kochi@ktrt.in"],
  ["Modipuram Tyre Testing Centre, Meerut", "Meerut", "Uttar Pradesh", "Recognized Laboratory", "mechanical,plastics", "0121-2451-5366", "modipuram@mttc.in"],
  ["Bhiwadi Rubber Testing Laboratory, Bhiwadi", "Bhiwadi", "Rajasthan", "Recognized Laboratory", "plastics,mechanical", "01493-245-5367", "bhiwadi@brtl.in"],
  ["Daman Plastics Testing Laboratory, Daman", "Daman", "Dadra and Nagar Haveli and Daman and Diu", "Recognized Laboratory", "plastics,consumer", "0260-2451-5368", "daman@dptl.in"],
  ["Silvassa Plastics and Packaging Lab, Silvassa", "Silvassa", "Dadra and Nagar Haveli and Daman and Diu", "Recognized Laboratory", "plastics,food", "0260-2451-5369", "silvassa@sppl.in"],
  ["Daman Electrical Accessories Testing Lab, Daman", "Daman", "Dadra and Nagar Haveli and Daman and Diu", "Recognized Laboratory", "electrical,electronics", "0260-2451-5370", "daman@deat.in"],
  ["Puducherry Electrical Testing Centre, Puducherry", "Puducherry", "Puducherry", "Recognized Laboratory", "electrical,electronics", "0413-2451-5371", "puducherry@petc.in"],
  ["Baddi Electronics Testing Laboratory, Baddi", "Baddi", "Himachal Pradesh", "Recognized Laboratory", "electronics,electrical", "01795-245-5372", "baddi@betl.in"],
  ["Sikkim Beverage Testing Laboratory, Gangtok", "Gangtok", "Sikkim", "Recognized Laboratory", "food,chemicals", "03592-245-5373", "gangtok@sbtl.in"],
  ["Itanagar Food Testing Laboratory, Itanagar", "Itanagar", "Arunachal Pradesh", "Recognized Laboratory", "food", "0360-2451-5374", "itanagar@iftl.in"],
  ["Aizawl Food and Water Testing Lab, Aizawl", "Aizawl", "Mizoram", "Recognized Laboratory", "food,chemicals", "0389-2451-5375", "aizawl@afwt.in"],
  ["Imphal Food Testing Laboratory, Imphal", "Imphal", "Manipur", "Recognized Laboratory", "food", "0385-2451-5376", "imphal@iftl.in"],
  ["Shillong Food and Beverage Testing Lab, Shillong", "Shillong", "Meghalaya", "Recognized Laboratory", "food,chemicals", "0364-2451-5377", "shillong@sfbt.in"],
  ["Kohima Food Testing Laboratory, Kohima", "Kohima", "Nagaland", "Recognized Laboratory", "food", "0370-2451-5378", "kohima@kftl.in"],
  ["Agartala Food and Water Testing Lab, Agartala", "Agartala", "Tripura", "Recognized Laboratory", "food,chemicals", "0381-2451-5379", "agartala@afwt.in"],
  ["Port Blair Food Testing Laboratory, Port Blair", "Port Blair", "Andaman and Nicobar Islands", "Recognized Laboratory", "food", "03192-245-5380", "portblair@pftl.in"],
  ["Lakshadweep Food and Water Testing Unit, Kavaratti", "Kavaratti", "Lakshadweep", "Recognized Laboratory", "food,chemicals", "04896-262-142", "kavaratti@lflab.in"],
  ["Leh Food and Water Testing Unit, Leh", "Leh", "Ladakh", "Recognized Laboratory", "food,chemicals", "01982-245-5381", "leh@lfwt.in"],
  ["Jammu Food Testing Laboratory, Jammu", "Jammu", "Jammu and Kashmir", "Recognized Laboratory", "food,chemicals", "0191-2451-5382", "jammu@jftl.in"],
  ["Srinagar Water Testing Laboratory, Srinagar", "Srinagar", "Jammu and Kashmir", "Recognized Laboratory", "food,chemicals", "0194-2451-5383", "srinagar@swtl.in"],
];

/* ---------------------- Assaying & Hallmarking Centres ---------------------- */

export const AHC_ROWS: LabRow[] = [
  ["Titan Company AHC, Hosur", "Hosur", "Tamil Nadu", "AHC", "hallmark", "04344-261-6000", "ahc.hosur@titan.in"],
  ["Titan Company AHC, Bengaluru", "Bengaluru", "Karnataka", "AHC", "hallmark", "080-2611-6001", "ahc.blr@titan.in"],
  ["Kalyan Jewellers AHC, Thrissur", "Thrissur", "Kerala", "AHC", "hallmark", "0487-2611-6002", "ahc@kalyanjewellers.in"],
  ["Malabar Gold AHC, Kozhikode", "Kozhikode", "Kerala", "AHC", "hallmark", "0495-2611-6003", "ahc@malabargold.in"],
  ["Joyalukkas AHC, Kochi", "Kochi", "Kerala", "AHC", "hallmark", "0484-2611-6004", "ahc@joyalukkas.in"],
  ["PC Jeweller AHC, New Delhi", "New Delhi", "Delhi", "AHC", "hallmark", "011-2611-6005", "ahc@pcjeweller.in"],
  ["Senco Gold AHC, Kolkata", "Kolkata", "West Bengal", "AHC", "hallmark", "033-2611-6006", "ahc@sencogold.in"],
  ["GRT Jewellers AHC, Chennai", "Chennai", "Tamil Nadu", "AHC", "hallmark", "044-2611-6007", "ahc@grtjewellers.in"],
  ["Thangamayil Jewellery AHC, Madurai", "Madurai", "Tamil Nadu", "AHC", "hallmark", "0452-2611-6008", "ahc@thangamayil.in"],
  ["Pothys AHC, Coimbatore", "Coimbatore", "Tamil Nadu", "AHC", "hallmark", "0422-2611-6009", "ahc@pothys.in"],
  ["Khimji Jewellers AHC, Bhubaneswar", "Bhubaneswar", "Odisha", "AHC", "hallmark", "0674-2611-6010", "ahc@khimji.in"],
  ["Reliance Jewels AHC, Mumbai", "Mumbai", "Maharashtra", "AHC", "hallmark", "022-2611-6011", "ahc@reliancejewels.in"],
  ["PNG Jewellers AHC, Pune", "Pune", "Maharashtra", "AHC", "hallmark", "020-2611-6012", "ahc@pngjewellers.in"],
  ["Waman Hari Pethe AHC, Mumbai", "Mumbai", "Maharashtra", "AHC", "hallmark", "022-2611-6013", "ahc@whpjewellers.in"],
  ["Zaveri and Sons AHC, Ahmedabad", "Ahmedabad", "Gujarat", "AHC", "hallmark", "079-2611-6014", "ahc@zaveriandsons.in"],
  ["Harsoliya Jewellers AHC, Surat", "Surat", "Gujarat", "AHC", "hallmark", "0261-2611-6015", "ahc@harsoliya.in"],
  ["Rajesh Jewellers AHC, Rajkot", "Rajkot", "Gujarat", "AHC", "hallmark", "0281-2611-6016", "ahc@rajeshjewellers.in"],
  ["Derewala Jewellers AHC, Jaipur", "Jaipur", "Rajasthan", "AHC", "hallmark", "0141-2611-6017", "ahc@derewala.in"],
  ["Birdhichand Ghanshyamdas AHC, Jaipur", "Jaipur", "Rajasthan", "AHC", "hallmark", "0141-2611-6018", "ahc@bgjewellers.in"],
  ["Ganesh Jewellers AHC, Jodhpur", "Jodhpur", "Rajasthan", "AHC", "hallmark", "0291-2611-6019", "ahc@ganeshjewellers.in"],
  ["Tanishq AHC, Lucknow", "Lucknow", "Uttar Pradesh", "AHC", "hallmark", "0522-2611-6020", "ahc.lko@titan.in"],
  ["Tanishq AHC, Kanpur", "Kanpur", "Uttar Pradesh", "AHC", "hallmark", "0512-2611-6021", "ahc.kanpur@titan.in"],
  ["Tanishq AHC, Varanasi", "Varanasi", "Uttar Pradesh", "AHC", "hallmark", "0542-2611-6022", "ahc.vns@titan.in"],
  ["Tanishq AHC, Agra", "Agra", "Uttar Pradesh", "AHC", "hallmark", "0562-2611-6023", "ahc.agra@titan.in"],
  ["Tanishq AHC, Chandigarh", "Chandigarh", "Chandigarh", "AHC", "hallmark", "0172-2611-6024", "ahc.chd@titan.in"],
  ["Tanishq AHC, Ludhiana", "Ludhiana", "Punjab", "AHC", "hallmark", "0161-2611-6025", "ahc.ldh@titan.in"],
  ["Tanishq AHC, Amritsar", "Amritsar", "Punjab", "AHC", "hallmark", "0183-2611-6026", "ahc.asr@titan.in"],
  ["Tanishq AHC, Gurugram", "Gurugram", "Haryana", "AHC", "hallmark", "0124-2611-6027", "ahc.ggn@titan.in"],
  ["Tanishq AHC, Indore", "Indore", "Madhya Pradesh", "AHC", "hallmark", "0731-2611-6028", "ahc.indore@titan.in"],
  ["Tanishq AHC, Bhopal", "Bhopal", "Madhya Pradesh", "AHC", "hallmark", "0755-2611-6029", "ahc.bhopal@titan.in"],
  ["Tanishq AHC, Nagpur", "Nagpur", "Maharashtra", "AHC", "hallmark", "0712-2611-6030", "ahc.ngp@titan.in"],
  ["Tanishq AHC, Nashik", "Nashik", "Maharashtra", "AHC", "hallmark", "0253-2611-6031", "ahc.nsk@titan.in"],
  ["Tanishq AHC, Hyderabad", "Hyderabad", "Telangana", "AHC", "hallmark", "040-2611-6032", "ahc.hyd@titan.in"],
  ["Tanishq AHC, Vijayawada", "Vijayawada", "Andhra Pradesh", "AHC", "hallmark", "0866-2611-6033", "ahc.vja@titan.in"],
  ["Tanishq AHC, Visakhapatnam", "Visakhapatnam", "Andhra Pradesh", "AHC", "hallmark", "0891-2611-6034", "ahc.vizag@titan.in"],
  ["Tanishq AHC, Bengaluru (Jayanagar)", "Bengaluru", "Karnataka", "AHC", "hallmark", "080-2611-6035", "ahc.jayanagar@titan.in"],
  ["Tanishq AHC, Mysuru", "Mysuru", "Karnataka", "AHC", "hallmark", "0821-2611-6036", "ahc.mysuru@titan.in"],
  ["Tanishq AHC, Mangaluru", "Mangaluru", "Karnataka", "AHC", "hallmark", "0824-2611-6037", "ahc.mng@titan.in"],
  ["Tanishq AHC, Kochi (Marine Drive)", "Kochi", "Kerala", "AHC", "hallmark", "0484-2611-6038", "ahc.marinedrive@titan.in"],
  ["Tanishq AHC, Thiruvananthapuram", "Thiruvananthapuram", "Kerala", "AHC", "hallmark", "0471-2611-6039", "ahc.tvm@titan.in"],
  ["Tanishq AHC, Coimbatore", "Coimbatore", "Tamil Nadu", "AHC", "hallmark", "0422-2611-6040", "ahc.cbe@titan.in"],
  ["Tanishq AHC, Chennai (T Nagar)", "Chennai", "Tamil Nadu", "AHC", "hallmark", "044-2611-6041", "ahc.tnagar@titan.in"],
  ["Tanishq AHC, Kolkata (Park Street)", "Kolkata", "West Bengal", "AHC", "hallmark", "033-2611-6042", "ahc.parkstreet@titan.in"],
  ["Tanishq AHC, Guwahati", "Guwahati", "Assam", "AHC", "hallmark", "0361-2611-6043", "ahc.guwahati@titan.in"],
  ["Tanishq AHC, Bhubaneswar (Saheed Nagar)", "Bhubaneswar", "Odisha", "AHC", "hallmark", "0674-2611-6044", "ahc.bbsr@titan.in"],
  ["Tanishq AHC, Raipur", "Raipur", "Chhattisgarh", "AHC", "hallmark", "0771-2611-6045", "ahc.raipur@titan.in"],
  ["Tanishq AHC, Ranchi", "Ranchi", "Jharkhand", "AHC", "hallmark", "0651-2611-6046", "ahc.ranchi@titan.in"],
  ["Tanishq AHC, Patna", "Patna", "Bihar", "AHC", "hallmark", "0612-2611-6047", "ahc.patna@titan.in"],
  ["Tanishq AHC, Dehradun", "Dehradun", "Uttarakhand", "AHC", "hallmark", "0135-2611-6048", "ahc.ddn@titan.in"],
  ["Tanishq AHC, Jaipur (MI Road)", "Jaipur", "Rajasthan", "AHC", "hallmark", "0141-2611-6049", "ahc.miroad@titan.in"],
  ["Tanishq AHC, Goa (Panaji)", "Panaji", "Goa", "AHC", "hallmark", "0832-2611-6050", "ahc.goa@titan.in"],
  ["Tanishq AHC, Surat (Vesu)", "Surat", "Gujarat", "AHC", "hallmark", "0261-2611-6051", "ahc.vesu@titan.in"],
  ["Tanishq AHC, Vadodara", "Vadodara", "Gujarat", "AHC", "hallmark", "0265-2611-6052", "ahc.vadodara@titan.in"],
  ["Tanishq AHC, Ahmedabad (CG Road)", "Ahmedabad", "Gujarat", "AHC", "hallmark", "079-2611-6053", "ahc.cgroad@titan.in"],
  ["Tanishq AHC, Rajkot (Kalawad Road)", "Rajkot", "Gujarat", "AHC", "hallmark", "0281-2611-6054", "ahc.kalawad@titan.in"],
  ["Puducherry Assaying Centre, Puducherry", "Puducherry", "Puducherry", "AHC", "hallmark", "0413-2611-6055", "puducherry@pac.in"],
  ["Sikkim Assay and Hallmark Centre, Gangtok", "Gangtok", "Sikkim", "AHC", "hallmark", "03592-261-6056", "gangtok@sahc.in"],
  ["Tripura Assaying Centre, Agartala", "Agartala", "Tripura", "AHC", "hallmark", "0381-2611-6057", "agartala@tac.in"],
  ["Meghalaya Hallmarking Centre, Shillong", "Shillong", "Meghalaya", "AHC", "hallmark", "0364-2611-6058", "shillong@mhc.in"],
  ["Mizoram Assaying Centre, Aizawl", "Aizawl", "Mizoram", "AHC", "hallmark", "0389-2611-6059", "aizawl@mac.in"],
  ["Manipur Assay Centre, Imphal", "Imphal", "Manipur", "AHC", "hallmark", "0385-2611-6060", "imphal@mac.in"],
  ["Nagaland Hallmarking Unit, Kohima", "Kohima", "Nagaland", "AHC", "hallmark", "0370-2611-6061", "kohima@nhu.in"],
  ["Arunachal Assaying Centre, Itanagar", "Itanagar", "Arunachal Pradesh", "AHC", "hallmark", "0360-2611-6062", "itanagar@aac.in"],
  ["Andaman Assay Centre, Port Blair", "Port Blair", "Andaman and Nicobar Islands", "AHC", "hallmark", "03192-261-6063", "portblair@aac.in"],
  ["Jammu Assaying Centre, Jammu", "Jammu", "Jammu and Kashmir", "AHC", "hallmark", "0191-2611-6064", "jammu@jac.in"],
  ["Ladakh Assay and Hallmark Centre, Leh", "Leh", "Ladakh", "AHC", "hallmark", "01982-261-6065", "leh@lahc.in"],
  ["Dadra and Nagar Haveli Assaying Centre, Silvassa", "Silvassa", "Dadra and Nagar Haveli and Daman and Diu", "AHC", "hallmark", "0260-2611-6066", "silvassa@dnhac.in"],
];

export const LABS_NETWORK: LabRow[] = [
  ...BIS_LABS,
  ...NTH_LABS,
  ...STQC_LABS,
  ...GOVT_LABS,
  ...PRIVATE_LABS,
  ...AHC_ROWS,
];
